In [6]:
# link: https://www.ebi.ac.uk/metagenomics/studies/MGYS00001442?analyses-page_size=50#overview
Analyses_table_from_website = """ERS1509315	human gut metagenome	ERR1809124	3.0	MGYA00096976
ERS1509329	human gut metagenome	ERR1809156	3.0	MGYA00096977
ERS1509322	human gut metagenome	ERR1809148	3.0	MGYA00096978
ERS1509328	human gut metagenome	ERR1809155	3.0	MGYA00096979
ERS1509320	human gut metagenome	ERR1809142	3.0	MGYA00096980
ERS1509315	human gut metagenome	ERR1809119	3.0	MGYA00096981
ERS1509326	human gut metagenome	ERR1809153	3.0	MGYA00096982
ERS1509318	human gut metagenome	ERR1809136	3.0	MGYA00096983
ERS1509321	human gut metagenome	ERR1809146	3.0	MGYA00096984
ERS1509315	human gut metagenome	ERR1809123	3.0	MGYA00096985
ERS1509327	human gut metagenome	ERR1809154	3.0	MGYA00096986
ERS1509320	human gut metagenome	ERR1809141	3.0	MGYA00096987
ERS1509316	human gut metagenome	ERR1809127	3.0	MGYA00096988
ERS1509318	human gut metagenome	ERR1809133	3.0	MGYA00096989
ERS1509315	human gut metagenome	ERR1809121	3.0	MGYA00096990
ERS1509316	human gut metagenome	ERR1809126	3.0	MGYA00096991
ERS1509321	human gut metagenome	ERR1809145	3.0	MGYA00096992
ERS1509319	human gut metagenome	ERR1809140	3.0	MGYA00096993
ERS1509319	human gut metagenome	ERR1809139	3.0	MGYA00096994
ERS1509325	human gut metagenome	ERR1809151	3.0	MGYA00096995
ERS1509317	human gut metagenome	ERR1809130	3.0	MGYA00096996
ERS1509317	human gut metagenome	ERR1809132	3.0	MGYA00096997
ERS1509317	human gut metagenome	ERR1809129	3.0	MGYA00096998
ERS1509319	human gut metagenome	ERR1809138	3.0	MGYA00096999
ERS1509316	human gut metagenome	ERR1809125	3.0	MGYA00097000
ERS1509318	human gut metagenome	ERR1809137	3.0	MGYA00097001
ERS1509325	human gut metagenome	ERR1809152	3.0	MGYA00097002
ERS1509317	human gut metagenome	ERR1809128	3.0	MGYA00097003
ERS1509315	human gut metagenome	ERR1809122	3.0	MGYA00097004
ERS1509318	human gut metagenome	ERR1809135	3.0	MGYA00097005
ERS1509317	human gut metagenome	ERR1809131	3.0	MGYA00097006
ERS1509315	human gut metagenome	ERR1809120	3.0	MGYA00097007
ERS1509320	human gut metagenome	ERR1809143	3.0	MGYA00097008
ERS1509320	human gut metagenome	ERR1809144	3.0	MGYA00097009
ERS1509318	human gut metagenome	ERR1809134	3.0	MGYA00097010
ERS1509324	human gut metagenome	ERR1809150	3.0	MGYA00097011
ERS1509321	human gut metagenome	ERR1809147	3.0	MGYA00097012
ERS1509323	human gut metagenome	ERR1809149	3.0	MGYA00097013"""

ERS_list = Analyses_table_from_website.split("\n")
ERS_list = [i.split("\t") for i in ERS_list]
ERS_list = [i[0] for i in ERS_list]

ERR_list = Analyses_table_from_website.split("\n")
ERR_list = [i.split("\t") for i in ERR_list]
ERR_list = [i[2] for i in ERR_list]

MGY_list = Analyses_table_from_website.split("\n")
MGY_list = [i.split("\t") for i in MGY_list]
MGY_list = [i[-1] for i in MGY_list]

print("ERS_count")
print(ERS_list)
print(len(ERS_list))
print(len(set(ERS_list)))

print("ERR_count")
print(ERR_list)
print(len(ERR_list))
print(len(set(ERR_list)))

print("MGY_count")
print(MGY_list)
print(len(MGY_list))
print(len(set(MGY_list)))


samples_from_go_slim_annotation_file = "ERR1809119	ERR1809120	ERR1809121	ERR1809122	ERR1809123	ERR1809124	ERR1809125	ERR1809127	ERR1809128	ERR1809129	ERR1809130	ERR1809131	ERR1809132	ERR1809133	ERR1809134	ERR1809135	ERR1809136	ERR1809137	ERR1809138	ERR1809139	ERR1809140	ERR1809141	ERR1809142	ERR1809143	ERR1809144	ERR1809145	ERR1809146	ERR1809147	ERR1809148	ERR1809149	ERR1809150	ERR1809151	ERR1809152	ERR1809153	ERR1809154	ERR1809155	ERR1809156"
y = samples_from_go_slim_annotation_file.split("\t")

print(y)
print(len(y))
print(len(set(y)))


print(set(ERR_list) - set(y))

ERS_count
['ERS1509315', 'ERS1509329', 'ERS1509322', 'ERS1509328', 'ERS1509320', 'ERS1509315', 'ERS1509326', 'ERS1509318', 'ERS1509321', 'ERS1509315', 'ERS1509327', 'ERS1509320', 'ERS1509316', 'ERS1509318', 'ERS1509315', 'ERS1509316', 'ERS1509321', 'ERS1509319', 'ERS1509319', 'ERS1509325', 'ERS1509317', 'ERS1509317', 'ERS1509317', 'ERS1509319', 'ERS1509316', 'ERS1509318', 'ERS1509325', 'ERS1509317', 'ERS1509315', 'ERS1509318', 'ERS1509317', 'ERS1509315', 'ERS1509320', 'ERS1509320', 'ERS1509318', 'ERS1509324', 'ERS1509321', 'ERS1509323']
38
15
ERR_count
['ERR1809124', 'ERR1809156', 'ERR1809148', 'ERR1809155', 'ERR1809142', 'ERR1809119', 'ERR1809153', 'ERR1809136', 'ERR1809146', 'ERR1809123', 'ERR1809154', 'ERR1809141', 'ERR1809127', 'ERR1809133', 'ERR1809121', 'ERR1809126', 'ERR1809145', 'ERR1809140', 'ERR1809139', 'ERR1809151', 'ERR1809130', 'ERR1809132', 'ERR1809129', 'ERR1809138', 'ERR1809125', 'ERR1809137', 'ERR1809152', 'ERR1809128', 'ERR1809122', 'ERR1809135', 'ERR1809131', 'ERR1809120', 'ERR1809143', 'ERR1809144', 'ERR1809134', 'ERR1809150', 'ERR1809147', 'ERR1809149']
38
38
MGY_count
['MGYA00096976', 'MGYA00096977', 'MGYA00096978', 'MGYA00096979', 'MGYA00096980', 'MGYA00096981', 'MGYA00096982', 'MGYA00096983', 'MGYA00096984', 'MGYA00096985', 'MGYA00096986', 'MGYA00096987', 'MGYA00096988', 'MGYA00096989', 'MGYA00096990', 'MGYA00096991', 'MGYA00096992', 'MGYA00096993', 'MGYA00096994', 'MGYA00096995', 'MGYA00096996', 'MGYA00096997', 'MGYA00096998', 'MGYA00096999', 'MGYA00097000', 'MGYA00097001', 'MGYA00097002', 'MGYA00097003', 'MGYA00097004', 'MGYA00097005', 'MGYA00097006', 'MGYA00097007', 'MGYA00097008', 'MGYA00097009', 'MGYA00097010', 'MGYA00097011', 'MGYA00097012', 'MGYA00097013']
38
38
['ERR1809119', 'ERR1809120', 'ERR1809121', 'ERR1809122', 'ERR1809123', 'ERR1809124', 'ERR1809125', 'ERR1809127', 'ERR1809128', 'ERR1809129', 'ERR1809130', 'ERR1809131', 'ERR1809132', 'ERR1809133', 'ERR1809134', 'ERR1809135', 'ERR1809136', 'ERR1809137', 'ERR1809138', 'ERR1809139', 'ERR1809140', 'ERR1809141', 'ERR1809142', 'ERR1809143', 'ERR1809144', 'ERR1809145', 'ERR1809146', 'ERR1809147', 'ERR1809148', 'ERR1809149', 'ERR1809150', 'ERR1809151', 'ERR1809152', 'ERR1809153', 'ERR1809154', 'ERR1809155', 'ERR1809156']
37
37
{'ERR1809126'}

In [ ]:
import pandas as pd

MGYS00001980_v4 = pd.read_table("../MGYS00001980(two_pipelines)/ERP103961_GO_abundances_v4.0.tsv", usecols=["GO", "description", "category"])
MGYS00001980_v5 = pd.read_table("../MGYS00001980(two_pipelines)/ERP103961_GO_abundances_v5.0.tsv", usecols=["GO", "description", "category"])

v4_descriptions = MGYS00001980_v4["description"]
v5_descriptions = MGYS00001980_v5["description"]
print("difference in descriptions")
print(set(v4_descriptions) - set(v5_descriptions))
print(set(v5_descriptions) - set(v4_descriptions))

v4_GO = MGYS00001980_v4["GO"]
v5_GO = MGYS00001980_v5["GO"]
print("difference in GO")
print(set(v4_GO) - set(v5_GO))
print(set(v5_GO) - set(v4_GO))

FileNotFoundError: [Errno 2] No such file or directory: 'data/MGYS00001980(two_pipelines)/ERP103961_GO_abundances_v4.0.tsv'

#### checking out downloads

In [ ]:
base_api = "https://www.ebi.ac.uk/metagenomics/api/latest/"
study_id = "MGYS00001980"

from jsonapi_client import Session

with Session(base_api) as mgnify:
    downloads_path = f"studies/{study_id}/downloads"
    downloads = mgnify.get(downloads_path).resources
    print(downloads[0].url)

https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00001980/pipelines/4.0/file/ERP103961_GO-slim_abundances_v4.0.tsv

#### Checking out samples of a study

In [100]:
base_api = "https://www.ebi.ac.uk/metagenomics/api/latest"
study_id = "MGYS00003619"

from requests import Session

with Session() as mgnify:
    downloads_path = f"{base_api}/studies/{study_id}/samples?fields[samples]=id,biosample,latitude,longitude,species,sample_metadata&page_size=50"
    downloads = mgnify.get(downloads_path)
    downloads = downloads.json()
    print(downloads["data"][0]["attributes"]["biosample"])

{'pagination': {'page': 1, 'pages': 16, 'count': 764}}
SAMN05827026

#### Checking out Elixir Contextual Data Clearnin House metadata hosted on MGnify

In [54]:
base_api = "https://www.ebi.ac.uk/metagenomics/api/latest"
import requests

sample = "SRS1719399"

with requests.get(f"{base_api}/samples/{sample}/contextual_data_clearing_house_metadata") as request:
    print(request.json())

base_api = "https://www.ebi.ac.uk/ena/clearinghouse/api"
with requests.get(f"{base_api}/curations/{sample}") as request:
    print(request.json()["curations"])

TypeError: 'Response' object is not subscriptable

#### cheching out biosamples api

In [41]:
BASE_API_URL = "https://www.ebi.ac.uk/biosamples"

import requests
metadata = {}
with requests.get(f"{BASE_API_URL}/samples/SAMN05826524") as response:
    print(response.json())
    print(response.json()["accession"])
    print(response.json()["characteristics"])
    characteristics = response.json()["characteristics"]
    metadata = {x: characteristics[x][0]["text"] for x in characteristics if characteristics[x][0].get("tag", "") == "attribute"} 
    print(metadata)

{'name': 'G69188', 'accession': 'SAMN05826524', 'domain': 'self.BiosampleImportNCBI', 'taxId': 408170, 'status': 'PUBLIC', 'release': '2016-09-26T16:32:03.253Z', 'update': '2022-03-29T21:36:03.797Z', 'submitted': '2016-09-26T16:32:08.617Z', 'characteristics': {'External Id': [{'text': 'SAMN05826524', 'tag': 'Namespace:BioSample'}], 'INSDC center name': [{'text': 'Broad Institute'}], 'INSDC first public': [{'text': '2016-09-26T16:32:03.253Z'}], 'INSDC last update': [{'text': '2016-10-01T09:22:58.923Z'}], 'INSDC secondary accession': [{'text': 'SRS1719399'}], 'INSDC status': [{'text': 'live'}], 'NCBI submission model': [{'text': 'MIMS.me'}, {'text': 'MIGS/MIMS/MIMARKS.human-gut'}], 'NCBI submission package': [{'text': 'MIMS.me.human-gut.5.0'}], 'SRA accession': [{'text': 'SRS1719399'}], 'description': [{'text': 'Keywords: GSC:MIxS;MIMS:5.0'}], 'env biome': [{'text': 'ENVO:2100002', 'tag': 'attribute'}], 'env feature': [{'text': 'ENVO:00000062', 'tag': 'attribute'}], 'env_material': [{'text': 'ENVO:00002003', 'tag': 'attribute'}], 'geo loc name': [{'text': 'Finland:Espoo', 'tag': 'attribute'}], 'host': [{'text': 'Homo sapiens', 'ontologyTerms': ['http://purl.obolibrary.org/obo/NCBITaxon_9606'], 'tag': 'attribute'}], 'host age': [{'text': '663', 'tag': 'attribute'}], 'host subject id': [{'text': 'E018421', 'tag': 'attribute'}], 'organism': [{'text': 'human gut metagenome', 'ontologyTerms': ['http://purl.obolibrary.org/obo/NCBITaxon_408170']}], 'ref_biomaterial': [{'text': 'PMID:27259157', 'tag': 'attribute'}], 'title': [{'text': 'MIMS Environmental/Metagenome sample from human gut metagenome'}]}, 'externalReferences': [{'url': 'https://www.ebi.ac.uk/ena/data/view/SAMN05826524', 'duo': []}], 'submittedVia': 'JSON_API', 'create': '2016-09-26T16:32:08.617Z', '_links': {'self': {'href': 'https://www.ebi.ac.uk/biosamples/samples/SAMN05826524'}, 'curationDomain': {'href': 'https://www.ebi.ac.uk/biosamples/samples/SAMN05826524{?curationdomain}', 'templated': True}, 'curationLinks': {'href': 'https://www.ebi.ac.uk/biosamples/samples/SAMN05826524/curationlinks'}, 'curationLink': {'href': 'https://www.ebi.ac.uk/biosamples/samples/SAMN05826524/curationlinks/{hash}', 'templated': True}, 'structuredData': {'href': 'https://www.ebi.ac.uk/biosamples/structureddata/SAMN05826524'}}}
SAMN05826524
{'External Id': [{'text': 'SAMN05826524', 'tag': 'Namespace:BioSample'}], 'INSDC center name': [{'text': 'Broad Institute'}], 'INSDC first public': [{'text': '2016-09-26T16:32:03.253Z'}], 'INSDC last update': [{'text': '2016-10-01T09:22:58.923Z'}], 'INSDC secondary accession': [{'text': 'SRS1719399'}], 'INSDC status': [{'text': 'live'}], 'NCBI submission model': [{'text': 'MIMS.me'}, {'text': 'MIGS/MIMS/MIMARKS.human-gut'}], 'NCBI submission package': [{'text': 'MIMS.me.human-gut.5.0'}], 'SRA accession': [{'text': 'SRS1719399'}], 'description': [{'text': 'Keywords: GSC:MIxS;MIMS:5.0'}], 'env biome': [{'text': 'ENVO:2100002', 'tag': 'attribute'}], 'env feature': [{'text': 'ENVO:00000062', 'tag': 'attribute'}], 'env_material': [{'text': 'ENVO:00002003', 'tag': 'attribute'}], 'geo loc name': [{'text': 'Finland:Espoo', 'tag': 'attribute'}], 'host': [{'text': 'Homo sapiens', 'ontologyTerms': ['http://purl.obolibrary.org/obo/NCBITaxon_9606'], 'tag': 'attribute'}], 'host age': [{'text': '663', 'tag': 'attribute'}], 'host subject id': [{'text': 'E018421', 'tag': 'attribute'}], 'organism': [{'text': 'human gut metagenome', 'ontologyTerms': ['http://purl.obolibrary.org/obo/NCBITaxon_408170']}], 'ref_biomaterial': [{'text': 'PMID:27259157', 'tag': 'attribute'}], 'title': [{'text': 'MIMS Environmental/Metagenome sample from human gut metagenome'}]}
{'env biome': 'ENVO:2100002', 'env feature': 'ENVO:00000062', 'env_material': 'ENVO:00002003', 'geo loc name': 'Finland:Espoo', 'host': 'Homo sapiens', 'host age': '663', 'host subject id': 'E018421', 'ref_biomaterial': 'PMID:27259157'}

#### Test metadata getting function

In [5]:
import sys
import os
%load_ext autoreload
%autoreload 2

# Add the parent directory to sys.path
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(parent_dir)

import src.mgnify_helper as mh

mg = mh.MGnifyData("./")
metadata = mg.get_metadata_for_study("MGYS00003733")

2025-01-07 13:53:36.929 | SUCCESS  | src.mgnify_helper:get_metadata_for_study:418 - Metadata for 1307 samples in study MGYS00003733 already downloaded.

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
(metadata.T["Health state__elixir"].value_counts())
# indices = list(metadata.index)
# indices = [i for i in indices if "health" in i.lower()]
# print(indices)

Health state__elixir
Healthy    1307
Name: count, dtype: int64

#### Checking out study analyses

In [43]:
base_api = "https://www.ebi.ac.uk/metagenomics/api/latest"
study_id = "MGYS00003481"

from requests import Session

with Session() as mgnify:
    downloads_path = f"{base_api}/studies/{study_id}/analyses?page_size=50&page=1"
    downloads = mgnify.get(downloads_path)
    downloads = downloads.json()
    print(downloads["links"]["next"])

    print(downloads["data"][0]["relationships"]["assembly"]["data"]["id"])
    print(downloads["data"][0]["relationships"]["sample"]["data"]["id"])

https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00003481/analyses?page=2&page_size=50
ERZ653427
SRS1914055

In [ ]:
import sys
import os
%load_ext autoreload
%autoreload 2

# Add the parent directory to sys.path
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(parent_dir)

import src.mgnify_helper_functions as mhf

mg = mhf.MGnifyData("../data/iteration_one_data/")
res = mg.get_assembly_id_to_sample_id_dict("MGYS00003481")
print(res)
print(len(res))

samples = set(res.values())
print(len(samples))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

#### merging metdata and summary; how to check

In [ ]:
import json
import numpy as np
import pandas as pd
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.max_colwidth = None
pd.options.display.width = None

import sys
%load_ext autoreload
%autoreload 2
sys.path.append("../")

from src.mgnify_helper_functions import MGnifyData
import time

summary = pd.read_table("../data/MGYS00003481-ERP108957/ERP108957_GO_abundances_v4.1.tsv", index_col=["GO", "description", "category"])
display(summary.head())
rows = np.where(summary["ERZ653429"] < summary["ERZ654086"])    # Find rows where ERZ653429 < ERZ654086, although ERZ653429 has larger read and base count
display(summary.iloc[rows][["ERZ653429", "ERZ654086"]])


with open("../data/MGYS00003481-ERP108957/MGYS00003481_metadata.json") as f:
    metadata = json.load(f)

metadata = metadata["metadata"]
metadata = pd.DataFrame(metadata)
display(metadata.head())

assembly_id_to_sample_id = MGnifyData("../data/MGYS00003481-ERP108957").get_assembly_id_to_sample_id_dict("MGYS00003481")
print(assembly_id_to_sample_id)
print(len(assembly_id_to_sample_id.values()))
print(len(set(assembly_id_to_sample_id.values())))

mapping = {}
for key, value in assembly_id_to_sample_id.items():
    if value not in mapping:
        mapping[value] = []
    mapping[value].append(key)

new_columns = {new_name: metadata[old_name] for old_name, new_names in mapping.items() for new_name in new_names}
metadata = metadata.drop(columns=list(mapping.keys()))
metadata = metadata.join(pd.DataFrame(new_columns))

display(metadata.head())

summary = summary.droplevel(["GO", "category"])
summary = summary.T
metadata = metadata.T

combined_data = summary.join(metadata, how="left")

display(combined_data.head(5))
display(len(combined_data))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,,,ERZ1026920,ERZ1026930,ERZ1026940,ERZ1026950,ERZ1026960,ERZ1026970,ERZ1026980,ERZ1026990,ERZ1027000,ERZ1027010,ERZ1027040,ERZ1027050,ERZ1027060,ERZ1027070,ERZ1027090,ERZ1027100,ERZ1027110,ERZ1027120,ERZ1027130,ERZ1027140,ERZ1027150,ERZ1027160,ERZ1027180,ERZ1027190,ERZ1027200,ERZ1027210,ERZ1027220,ERZ1027230,ERZ1027240,ERZ1027250,ERZ1027260,ERZ1027270,ERZ1027280,ERZ1026911,ERZ1026921,ERZ1026931,ERZ1026941,ERZ1026951,ERZ1026961,ERZ1026971,ERZ1026981,ERZ1027001,ERZ1027011,ERZ1027041,ERZ1027051,ERZ1027061,ERZ1027071,ERZ1027101,ERZ1027111,ERZ1027121,ERZ1027131,ERZ1027141,ERZ1027171,ERZ1027181,ERZ1027191,ERZ1027201,ERZ1027221,ERZ1027241,ERZ1027251,ERZ1027261,ERZ1027271,ERZ1026912,ERZ1026922,ERZ1026932,ERZ1026942,ERZ1026952,ERZ1026962,ERZ1026972,ERZ1026982,ERZ1026992,ERZ1027002,ERZ1027012,ERZ1027032,ERZ1027042,ERZ1027052,ERZ1027062,ERZ1027072,ERZ1027092,ERZ1027102,ERZ1027112,ERZ1027122,ERZ1027132,ERZ1027142,ERZ1027182,ERZ1027192,ERZ1027202,ERZ1027212,ERZ1027222,ERZ1027232,ERZ1027242,ERZ1027252,ERZ1027262,ERZ1027272,ERZ1027282,ERZ1026913,ERZ1026923,ERZ1026933,ERZ1026943,ERZ1026953,ERZ1026963,ERZ1026973,ERZ1026983,ERZ1026993,ERZ1027003,ERZ1027013,ERZ1027033,ERZ1027043,ERZ1027053,ERZ1027063,ERZ1027093,ERZ1027103,ERZ1027113,ERZ1027123,ERZ1027133,ERZ1027153,ERZ1027163,ERZ1027183,ERZ1027193,ERZ1027203,ERZ1027213,ERZ1027223,ERZ1027233,ERZ1027243,ERZ1027253,ERZ1027263,ERZ1027273,ERZ1027283,ERZ1026774,ERZ1026914,ERZ1026924,ERZ1026934,ERZ1026944,ERZ1026954,ERZ1026964,ERZ1026974,ERZ1026984,ERZ1026994,ERZ1027004,ERZ1027014,ERZ1027034,ERZ1027044,ERZ1027054,ERZ1027064,ERZ1027074,ERZ1027084,ERZ1027094,ERZ1027104,ERZ1027114,ERZ1027124,ERZ1027134,ERZ1027144,ERZ1027154,ERZ1027174,ERZ1027184,ERZ1027194,ERZ1027204,ERZ1027214,ERZ1027224,ERZ1027244,ERZ1027254,ERZ1027264,ERZ1027274,ERZ1027284,ERZ1026915,ERZ1026925,ERZ1026935,ERZ1026945,ERZ1026955,ERZ1026965,ERZ1026975,ERZ1026985,ERZ1026995,ERZ1027005,ERZ1027015,ERZ1027035,ERZ1027045,ERZ1027055,ERZ1027065,ERZ1027085,ERZ1027095,ERZ1027105,ERZ1027115,ERZ1027125,ERZ1027135,ERZ1027145,ERZ1027175,ERZ1027195,ERZ1027205,ERZ1027215,ERZ1027225,ERZ1027235,ERZ1027245,ERZ1027255,ERZ1027265,ERZ1027275,ERZ1027285,ERZ1026906,ERZ1026916,ERZ1026926,ERZ1026936,ERZ1026946,ERZ1026956,ERZ1026966,ERZ1026976,ERZ1026986,ERZ1026996,ERZ1027006,ERZ1027016,ERZ1027036,ERZ1027046,ERZ1027056,ERZ1027066,ERZ1027076,ERZ1027086,ERZ1027096,ERZ1027106,ERZ1027116,ERZ1027126,ERZ1027136,ERZ1027146,ERZ1027176,ERZ1027186,ERZ1027196,ERZ1027206,ERZ1027216,ERZ1027226,ERZ1027236,ERZ1027246,ERZ1027256,ERZ1027266,ERZ1027276,ERZ1026777,ERZ1026907,ERZ1026917,ERZ1026927,ERZ1026937,ERZ1026947,ERZ1026957,ERZ1026967,ERZ1026977,ERZ1026997,ERZ1027007,ERZ1027037,ERZ1027047,ERZ1027057,ERZ1027067,ERZ1027077,ERZ1027087,ERZ1027097,ERZ1027107,ERZ1027117,ERZ1027127,ERZ1027137,ERZ1027147,ERZ1027157,ERZ1027167,ERZ1027177,ERZ1027197,ERZ1027207,ERZ1027217,ERZ1027227,ERZ1027237,ERZ1027247,ERZ1027257,ERZ1027267,ERZ1027277,ERZ1026908,ERZ1026918,ERZ1026928,ERZ1026938,ERZ1026948,ERZ1026958,ERZ1026968,ERZ1026978,ERZ1026988,ERZ1026998,ERZ1027008,ERZ1027038,ERZ1027048,ERZ1027058,ERZ1027068,ERZ1027078,ERZ1027098,ERZ1027108,ERZ1027118,ERZ1027128,ERZ1027138,ERZ1027148,ERZ1027168,ERZ1027178,ERZ1027188,ERZ1027198,ERZ1027218,ERZ1027228,ERZ1027238,ERZ1027248,ERZ1027258,ERZ1027268,ERZ1027278,ERZ1026909,ERZ1026919,ERZ1026929,ERZ1026939,ERZ1026949,ERZ1026959,ERZ1026969,ERZ1026979,ERZ1026989,ERZ1026999,ERZ1027009,ERZ1027039,ERZ1027049,ERZ1027059,ERZ1027069,ERZ1027089,ERZ1027099,ERZ1027109,ERZ1027119,ERZ1027129,ERZ1027139,ERZ1027149,ERZ1027179,ERZ1027189,ERZ1027199,ERZ1027209,ERZ1027219,ERZ1027229,ERZ1027239,ERZ1027249,ERZ1027259,ERZ1027269,ERZ1027279,ERZ652703,ERZ652704,ERZ652705,ERZ652706,ERZ652707,ERZ652708,ERZ652709,ERZ652710,ERZ652711,ERZ652712,ERZ652713,ERZ652714,ERZ652715,ERZ652716,ERZ652717,ERZ652718,ERZ652719,ERZ652720,ERZ652721,ERZ652722,ERZ652723,ERZ652724,ERZ652725,ERZ652726,ERZ652727,ERZ652728,ERZ652729,ERZ652730,ERZ652731,ERZ652732,ERZ652733,ERZ652734,ERZ652735,ERZ652736,ERZ652737,ERZ652738,ERZ652739,ERZ652740,ERZ652741,ERZ652742,ERZ652743,ERZ652744,ERZ652745,ERZ652746,ERZ652747,ERZ652748,ERZ652749,ERZ652750,ERZ652751,ERZ652752,ERZ652753,ERZ652754,ERZ652755,ERZ652756,ERZ652757,ERZ652758,ERZ652759,ERZ652760,ERZ652761,ERZ652762,ERZ652763,ERZ652764,ERZ652765,ERZ652766,ERZ652767,ERZ652768,ERZ652769,ERZ652770,ERZ652771,ERZ652772,ERZ652773,ERZ652774,ERZ652775,ERZ652776,ERZ652777,ERZ652778,ERZ652779,ERZ652780,ERZ652781,ERZ652782,ERZ652783,ERZ652784,ERZ652785,ERZ652786,ERZ652787,ERZ652788,ERZ652789,ERZ652790,ERZ652791,ERZ652792,ERZ652793,ERZ652794,ERZ652795,ERZ652796,ERZ652797,ERZ652798,ERZ652799,ERZ652800,ERZ652801,ERZ652802,ERZ652803,ERZ652804,ERZ652805,ERZ652806,ERZ652807,ERZ652808,ERZ652809,ERZ652810,ERZ652811,ERZ652812,ERZ652813,ERZ652814,ERZ652815,ERZ652816,ERZ652817,ERZ652818,ERZ652819,ERZ652820,ERZ652821,ERZ652822,ERZ652823,ERZ652824,ERZ652825,ERZ652826,ERZ652827,ERZ652828,ERZ652829,ERZ652830,ERZ652831,ERZ652832,ERZ652833,ERZ652834,ERZ652835,ERZ652836,ERZ652837,ERZ652838,ERZ652839,ERZ652840,ERZ652841,ERZ652842,ERZ652843,ERZ652844,ERZ652845,ERZ652846,ERZ652847,ERZ652848,ERZ652849,ERZ652850,ERZ652851,ERZ652852,ERZ652853,ERZ652854,ERZ652855,ERZ652856,ERZ652857,ERZ652858,ERZ652859,ERZ652860,ERZ652861,ERZ652862,ERZ652863,ERZ652864,ERZ652865,ERZ652866,ERZ652867,ERZ652868,ERZ652869,ERZ652870,ERZ652871,ERZ652872,ERZ652873,ERZ652874,ERZ652875,ERZ652876,ERZ652877,ERZ652878,ERZ652879,ERZ652880,ERZ652881,ERZ652882,ERZ652883,ERZ652884,ERZ652885,ERZ652886,ERZ652887,ERZ652888,ERZ652889,ERZ652890,ERZ652891,ERZ652892,ERZ652893,ERZ652894,ERZ652895,ERZ652896,ERZ652897,ERZ652898,ERZ652899,ERZ652900,ERZ652901,ERZ652902,ERZ652903,ERZ652904,ERZ652905,ERZ652906,ERZ652907,ERZ652908,ERZ652909,ERZ652910,ERZ652911,ERZ652912,ERZ652913,ERZ652914,ERZ652915,ERZ652916,ERZ652917,ERZ652918,ERZ652919,ERZ652920,ERZ652921,ERZ652922,ERZ652923,ERZ652924,ERZ652925,ERZ652926,ERZ652927,ERZ652928,ERZ652929,ERZ652930,ERZ652931,ERZ652932,ERZ652933,ERZ652934,ERZ652935,ERZ652936,ERZ652937,ERZ652938,ERZ652939,ERZ652940,ERZ652941,ERZ652942,ERZ652943,ERZ652944,ERZ652945,ERZ652946,ERZ652947,ERZ652948,ERZ652949,ERZ652950,ERZ652951,ERZ652952,ERZ652953,ERZ652954,ERZ652955,ERZ652956,ERZ652957,ERZ652958,ERZ652959,ERZ652960,ERZ652961,ERZ652962,ERZ652963,ERZ652964,ERZ652965,ERZ652966,ERZ652967,ERZ652968,ERZ652969,ERZ652970,ERZ652971,ERZ652972,ERZ652973,ERZ652974,ERZ652975,ERZ652976,ERZ652977,ERZ652978,ERZ652979,ERZ652980,ERZ652981,ERZ652982,ERZ652983,ERZ652984,ERZ652985,ERZ652986,ERZ652987,ERZ652988,ERZ652989,ERZ652990,ERZ652991,ERZ652992,ERZ652993,ERZ652994,ERZ652995,ERZ652996,ERZ652997,ERZ652998,ERZ652999,ERZ653000,ERZ653001,ERZ653002,ERZ653003,ERZ653004,ERZ653005,ERZ653006,ERZ653007,ERZ653008,ERZ653009,ERZ653010,ERZ653011,ERZ653012,ERZ653013,ERZ653014,ERZ653015,ERZ653016,ERZ653017,ERZ653018,ERZ653019,ERZ653020,ERZ653021,ERZ653022,ERZ653023,ERZ653024,ERZ653025,ERZ653026,ERZ653027,ERZ653028,ERZ653029,ERZ653030,ERZ653031,ERZ653032,ERZ653033,ERZ653034,ERZ653035,ERZ653036,ERZ653037,ERZ653038,ERZ653039,ERZ653040,ERZ653041,ERZ653042,ERZ653043,ERZ653044,ERZ653045,ERZ653046,ERZ653047,ERZ653048,ERZ653049,ERZ653050,ERZ653051,ERZ653052,ERZ653053,ERZ653054,ERZ653055,ERZ653056,ERZ653057,ERZ653058,ERZ653059,ERZ653060,ERZ653061,ERZ653062,ERZ653063,ERZ653064,ERZ653065,ERZ653066,ERZ653067,ERZ653068,ERZ653069,ERZ653070,ERZ653071,ERZ653072,ERZ653073,ERZ653074,ERZ653075,ERZ653076,ERZ653077,ERZ653078,ERZ653079,ERZ653081,ERZ653082,ERZ653083,ERZ653084,ERZ653085,ERZ653086,ERZ653087,ERZ653088,ERZ653089,ERZ653090,ERZ653091,ERZ653092,ERZ653093,ERZ653094,ERZ653095,ERZ653096,ERZ653097,ERZ653098,ERZ653099,ERZ653100,ERZ653101,ERZ653102,ERZ653103,ERZ653104,ERZ653105,ERZ653106,ERZ653107,ERZ653108,ERZ653109,ERZ653110,ERZ653111,ERZ653112,ERZ653113,ERZ653114,ERZ653115,ERZ653116,ERZ653117,ERZ653118,ERZ653119,ERZ653120,ERZ653121,ERZ653122,ERZ653123,ERZ653124,ERZ653125,ERZ653126,ERZ653127,ERZ653128,ERZ653129,ERZ653130,ERZ653131,ERZ653132,ERZ653133,ERZ653135,ERZ653136,ERZ653137,ERZ653138,ERZ653139,ERZ653140,ERZ653141,ERZ653142,ERZ653143,ERZ653144,ERZ653145,ERZ653146,ERZ653147,ERZ653148,ERZ653149,ERZ653150,ERZ653151,ERZ653152,ERZ653153,ERZ653154,ERZ653155,ERZ653156,ERZ653157,ERZ653158,ERZ653159,ERZ653160,ERZ653161,ERZ653162,ERZ653163,ERZ653164,ERZ653165,ERZ653166,ERZ653167,ERZ653168,ERZ653169,ERZ653170,ERZ653171,ERZ653172,ERZ653173,ERZ653174,ERZ653175,ERZ653176,ERZ653177,ERZ653178,ERZ653179,ERZ653180,ERZ653181,ERZ653182,ERZ653183,ERZ653184,ERZ653185,ERZ653186,ERZ653187,ERZ653188,ERZ653189,ERZ653190,ERZ653191,ERZ653192,ERZ653193,ERZ653194,ERZ653195,ERZ653196,ERZ653197,ERZ653198,ERZ653199,ERZ653200,ERZ653201,ERZ653202,ERZ653203,ERZ653204,ERZ653205,ERZ653206,ERZ653207,ERZ653208,ERZ653209,ERZ653210,ERZ653211,ERZ653212,ERZ653213,ERZ653214,ERZ653215,ERZ653216,ERZ653217,ERZ653218,ERZ653219,ERZ653220,ERZ653221,ERZ653222,ERZ653223,ERZ653224,ERZ653225,ERZ653226,ERZ653227,ERZ653228,ERZ653229,ERZ653230,ERZ653231,ERZ653232,ERZ653233,ERZ653234,ERZ653235,ERZ653236,ERZ653237,ERZ653238,ERZ653239,ERZ653240,ERZ653241,ERZ653242,ERZ653243,ERZ653244,ERZ653245,ERZ653246,ERZ653247,ERZ653248,ERZ653249,ERZ653250,ERZ653251,ERZ653252,ERZ653253,ERZ653254,ERZ653255,ERZ653256,ERZ653257,ERZ653258,ERZ653259,ERZ653260,ERZ653261,ERZ653262,ERZ653263,ERZ653264,ERZ653265,ERZ653266,ERZ653267,ERZ653268,ERZ653269,ERZ653270,ERZ653271,ERZ653272,ERZ653273,ERZ653274,ERZ653275,ERZ653276,ERZ653277,ERZ653278,ERZ653279,ERZ653280,ERZ653281,ERZ653282,ERZ653283,ERZ653284,ERZ653285,ERZ653286,ERZ653287,ERZ653288,ERZ653289,ERZ653290,ERZ653291,ERZ653292,ERZ653293,ERZ653294,ERZ653295,ERZ653296,ERZ653297,ERZ653298,ERZ653299,ERZ653300,ERZ653301,ERZ653302,ERZ653303,ERZ653304,ERZ653305,ERZ653306,ERZ653307,ERZ653308,ERZ653309,ERZ653310,ERZ653311,ERZ653312,ERZ653313,ERZ653314,ERZ653315,ERZ653316,ERZ653317,ERZ653318,ERZ653319,ERZ653320,ERZ653321,ERZ653322,ERZ653323,ERZ653324,ERZ653325,ERZ653326,ERZ653327,ERZ653328,ERZ653329,ERZ653330,ERZ653331,ERZ653332,ERZ653333,ERZ653334,ERZ653335,ERZ653336,ERZ653337,ERZ653338,ERZ653339,ERZ653340,ERZ653341,ERZ653342,ERZ653343,ERZ653344,ERZ653345,ERZ653346,ERZ653347,ERZ653348,ERZ653349,ERZ653350,ERZ653351,ERZ653352,ERZ653354,ERZ653355,ERZ653356,ERZ653357,ERZ653358,ERZ653359,ERZ653360,ERZ653361,ERZ653362,ERZ653363,ERZ653364,ERZ653365,ERZ653366,ERZ653367,ERZ653368,ERZ653369,ERZ653370,ERZ653371,ERZ653372,ERZ653373,ERZ653374,ERZ653375,ERZ653376,ERZ653377,ERZ653378,ERZ653379,ERZ653380,ERZ653381,ERZ653382,ERZ653383,ERZ653384,ERZ653385,ERZ653386,ERZ653387,ERZ653388,ERZ653389,ERZ653390,ERZ653391,ERZ653392,ERZ653393,ERZ653394,ERZ653395,ERZ653396,ERZ653397,ERZ653398,ERZ653399,ERZ653400,ERZ653401,ERZ653402,ERZ653403,ERZ653404,ERZ653405,ERZ653406,ERZ653407,ERZ653408,ERZ653409,ERZ653410,ERZ653411,ERZ653412,ERZ653413,ERZ653414,ERZ653415,ERZ653416,ERZ653417,ERZ653418,ERZ653419,ERZ653420,ERZ653421,ERZ653422,ERZ653423,ERZ653424,ERZ653425,ERZ653426,ERZ653427,ERZ653428,ERZ653429,ERZ653430,ERZ653431,ERZ653432,ERZ653433,ERZ653434,ERZ653435,ERZ653436,ERZ653437,ERZ653438,ERZ653439,ERZ653440,ERZ653441,ERZ653442,ERZ653443,ERZ653444,ERZ653446,ERZ653447,ERZ653448,ERZ653449,ERZ653450,ERZ653451,ERZ653452,ERZ653453,ERZ653454,ERZ653455,ERZ653456,ERZ653457,ERZ653459,ERZ653460,ERZ653461,ERZ653462,ERZ653463,ERZ653464,ERZ653465,ERZ653466,ERZ653467,ERZ653468,ERZ653469,ERZ653470,ERZ653471,ERZ653472,ERZ653473,ERZ653474,ERZ653475,ERZ653476,ERZ653477,ERZ653478,ERZ653479,ERZ653480,ERZ653481,ERZ653482,ERZ653483,ERZ653484,ERZ653486,ERZ653487,ERZ653488,ERZ653489,ERZ653490,ERZ653491,ERZ653492,ERZ653493,ERZ653494,ERZ653495,ERZ653496,ERZ653497,ERZ653498,ERZ653499,ERZ653500,ERZ653501,ERZ653502,ERZ653503,ERZ653504,ERZ653505,ERZ653506,ERZ653507,ERZ653508,ERZ653509,ERZ653510,ERZ653511,ERZ653512,ERZ653513,ERZ653514,ERZ653515,ERZ653516,ERZ653517,ERZ653518,ERZ653519,ERZ653520,ERZ653521,ERZ653522,ERZ653523,ERZ653524,ERZ653525,ERZ653526,ERZ653527,ERZ653528,ERZ653529,ERZ653530,ERZ653531,ERZ653532,ERZ653533,ERZ653535,ERZ653536,ERZ653537,ERZ653538,ERZ653539,ERZ653540,ERZ653541,ERZ653542,ERZ653543,ERZ653544,ERZ653545,ERZ653546,ERZ653547,ERZ653548,ERZ653549,ERZ653550,ERZ653551,ERZ653553,ERZ653554,ERZ653555,ERZ653556,ERZ653557,ERZ653558,ERZ653559,ERZ653560,ERZ653561,ERZ653562,ERZ653563,ERZ653564,ERZ653565,ERZ653566,ERZ653567,ERZ653568,ERZ653569,ERZ653570,ERZ653571,ERZ653572,ERZ653573,ERZ653574,ERZ653575,ERZ653576,ERZ653577,ERZ653578,ERZ653579,ERZ653580,ERZ653581,ERZ653582,ERZ653583,ERZ653584,ERZ653585,ERZ653586,ERZ653587,ERZ653588,ERZ653589,ERZ653590,ERZ653591,ERZ653592,ERZ653593,ERZ653594,ERZ653595,ERZ653596,ERZ653597,ERZ653598,ERZ653599,ERZ653600,ERZ653601,ERZ653602,ERZ653603,ERZ653604,ERZ653605,ERZ653606,ERZ653607,ERZ653608,ERZ653609,ERZ653610,ERZ653611,ERZ653612,ERZ653613,ERZ653614,ERZ653615,ERZ653616,ERZ653617,ERZ653618,ERZ653619,ERZ653620,ERZ653621,ERZ653622,ERZ653623,ERZ653624,ERZ653625,ERZ653626,ERZ653627,ERZ653628,ERZ653629,ERZ653630,ERZ653631,ERZ653632,ERZ653633,ERZ653634,ERZ653635,ERZ653636,ERZ653637,ERZ653638,ERZ653639,ERZ653640,ERZ653641,ERZ653642,ERZ653643,ERZ653644,ERZ653645,ERZ653646,ERZ653647,ERZ653648,ERZ653649,ERZ653650,ERZ653651,ERZ653652,ERZ653653,ERZ653654,ERZ653655,ERZ653656,ERZ653657,ERZ653658,ERZ653659,ERZ653660,ERZ653661,ERZ653662,ERZ653663,ERZ653664,ERZ653665,ERZ653666,ERZ653667,ERZ653668,ERZ653669,ERZ653670,ERZ653671,ERZ653672,ERZ653673,ERZ653674,ERZ653675,ERZ653676,ERZ653677,ERZ653678,ERZ653679,ERZ653680,ERZ653681,ERZ653682,ERZ653683,ERZ653684,ERZ653685,ERZ653686,ERZ653687,ERZ653688,ERZ653689,ERZ653690,ERZ653691,ERZ653692,ERZ653693,ERZ653694,ERZ653695,ERZ653696,ERZ653697,ERZ653698,ERZ653699,ERZ653700,ERZ653701,ERZ653702,ERZ653703,ERZ653704,ERZ653705,ERZ653706,ERZ653707,ERZ653708,ERZ653709,ERZ653710,ERZ653711,ERZ653712,ERZ653713,ERZ653714,ERZ653715,ERZ653716,ERZ653717,ERZ653718,ERZ653719,ERZ653720,ERZ653721,ERZ653722,ERZ653723,ERZ653724,ERZ653725,ERZ653726,ERZ653727,ERZ653728,ERZ653729,ERZ653730,ERZ653731,ERZ653732,ERZ653733,ERZ653734,ERZ653735,ERZ653736,ERZ653737,ERZ653738,ERZ653739,ERZ653740,ERZ653741,ERZ653742,ERZ653743,ERZ653744,ERZ653745,ERZ653746,ERZ653747,ERZ653748,ERZ653749,ERZ653750,ERZ653751,ERZ653752,ERZ653753,ERZ653754,ERZ653755,ERZ653756,ERZ653757,ERZ653758,ERZ653759,ERZ653760,ERZ653761,ERZ653762,ERZ653763,ERZ653764,ERZ653765,ERZ653766,ERZ653767,ERZ653768,ERZ653769,ERZ653770,ERZ653771,ERZ653772,ERZ653773,ERZ653774,ERZ653775,ERZ653776,ERZ653777,ERZ653778,ERZ653779,ERZ653780,ERZ653781,ERZ653782,ERZ653783,ERZ653784,ERZ653785,ERZ653786,ERZ653787,ERZ653788,ERZ653789,ERZ653790,ERZ653791,ERZ653792,ERZ653793,ERZ653794,ERZ653795,ERZ653796,ERZ653797,ERZ653798,ERZ653799,ERZ653800,ERZ653801,ERZ653802,ERZ653803,ERZ653804,ERZ653805,ERZ653806,ERZ653807,ERZ653808,ERZ653809,ERZ653810,ERZ653811,ERZ653812,ERZ653813,ERZ653814,ERZ653815,ERZ653816,ERZ653817,ERZ653818,ERZ653819,ERZ653820,ERZ653821,ERZ653822,ERZ653823,ERZ653824,ERZ653825,ERZ653826,ERZ653827,ERZ653828,ERZ653829,ERZ653830,ERZ653831,ERZ653832,ERZ653833,ERZ653834,ERZ653835,ERZ653836,ERZ653837,ERZ653838,ERZ653839,ERZ653840,ERZ653841,ERZ653842,ERZ653843,ERZ653844,ERZ653845,ERZ653846,ERZ653847,ERZ653848,ERZ653849,ERZ653850,ERZ653851,ERZ653852,ERZ653853,ERZ653854,ERZ653855,ERZ653856,ERZ653857,ERZ653858,ERZ653859,ERZ653860,ERZ653861,ERZ653862,ERZ653863,ERZ653864,ERZ653865,ERZ653866,ERZ653867,ERZ653868,ERZ653869,ERZ653870,ERZ653871,ERZ653872,ERZ653873,ERZ653874,ERZ653875,ERZ653876,ERZ653877,ERZ653878,ERZ653879,ERZ653880,ERZ653881,ERZ653882,ERZ653883,ERZ653884,ERZ653885,ERZ653886,ERZ653887,ERZ653888,ERZ653889,ERZ653890,ERZ653891,ERZ653892,ERZ653893,ERZ653894,ERZ653895,ERZ653896,ERZ653897,ERZ653898,ERZ653899,ERZ653900,ERZ653901,ERZ653902,ERZ653903,ERZ653904,ERZ653905,ERZ653906,ERZ653907,ERZ653908,ERZ653909,ERZ653910,ERZ653911,ERZ653912,ERZ653913,ERZ653914,ERZ653915,ERZ653916,ERZ653917,ERZ653918,ERZ653919,ERZ653920,ERZ653921,ERZ653922,ERZ653923,ERZ653924,ERZ653925,ERZ653926,ERZ653927,ERZ653928,ERZ653929,ERZ653930,ERZ653931,ERZ653932,ERZ653933,ERZ653934,ERZ653935,ERZ653936,ERZ653937,ERZ653938,ERZ653939,ERZ653940,ERZ653941,ERZ653942,ERZ653943,ERZ653944,ERZ653945,ERZ653946,ERZ653947,ERZ653948,ERZ653949,ERZ653950,ERZ653951,ERZ653952,ERZ653953,ERZ653954,ERZ653955,ERZ653956,ERZ653958,ERZ653959,ERZ653960,ERZ653961,ERZ653962,ERZ653963,ERZ653964,ERZ653965,ERZ653966,ERZ653967,ERZ653968,ERZ653969,ERZ653970,ERZ653971,ERZ653972,ERZ653973,ERZ653974,ERZ653975,ERZ653976,ERZ653977,ERZ653978,ERZ653979,ERZ653980,ERZ653981,ERZ653982,ERZ653983,ERZ653984,ERZ653985,ERZ653986,ERZ653987,ERZ653988,ERZ653989,ERZ653990,ERZ653991,ERZ653992,ERZ653993,ERZ653994,ERZ653995,ERZ653996,ERZ653997,ERZ653998,ERZ653999,ERZ654000,ERZ654001,ERZ654002,ERZ654003,ERZ654004,ERZ654005,ERZ654006,ERZ654007,ERZ654008,ERZ654009,ERZ654010,ERZ654011,ERZ654012,ERZ654013,ERZ654015,ERZ654016,ERZ654017,ERZ654018,ERZ654019,ERZ654020,ERZ654021,ERZ654022,ERZ654023,ERZ654024,ERZ654025,ERZ654026,ERZ654027,ERZ654028,ERZ654029,ERZ654030,ERZ654031,ERZ654032,ERZ654033,ERZ654034,ERZ654035,ERZ654036,ERZ654037,ERZ654038,ERZ654039,ERZ654040,ERZ654041,ERZ654042,ERZ654043,ERZ654044,ERZ654045,ERZ654046,ERZ654047,ERZ654048,ERZ654049,ERZ654050,ERZ654051,ERZ654052,ERZ654053,ERZ654054,ERZ654055,ERZ654056,ERZ654057,ERZ654058,ERZ654059,ERZ654060,ERZ654061,ERZ654062,ERZ654063,ERZ654064,ERZ654065,ERZ654066,ERZ654067,ERZ654068,ERZ654069,ERZ654070,ERZ654071,ERZ654072,ERZ654073,ERZ654074,ERZ654075,ERZ654076,ERZ654077,ERZ654078,ERZ654079,ERZ654080,ERZ654081,ERZ654082,ERZ654083,ERZ654084,ERZ654085,ERZ654086,ERZ654087,ERZ654088,ERZ654089,ERZ654090,ERZ654091,ERZ654092,ERZ654093,ERZ654094,ERZ654095,ERZ654096,ERZ654097,ERZ654098,ERZ654099,ERZ654100,ERZ654101,ERZ654102,ERZ654103,ERZ654104,ERZ654105,ERZ654106,ERZ654107,ERZ654108,ERZ654109,ERZ654110,ERZ654111,ERZ654112,ERZ654113,ERZ654114,ERZ654115,ERZ654116,ERZ654117,ERZ654118,ERZ654119,ERZ654120,ERZ654121,ERZ654122,ERZ654123,ERZ654124,ERZ654125,ERZ654126,ERZ654127,ERZ654128,ERZ654129,ERZ654130,ERZ654131,ERZ654132,ERZ654133,ERZ654134,ERZ654135,ERZ654136,ERZ654137,ERZ654138,ERZ654139,ERZ654140,ERZ654141,ERZ654142,ERZ654143,ERZ654144,ERZ654145,ERZ654146,ERZ654147,ERZ654148,ERZ654149,ERZ654150,ERZ654151,ERZ654152,ERZ654153,ERZ654154,ERZ654155,ERZ654156,ERZ654157,ERZ654158,ERZ654159,ERZ654160,ERZ654161,ERZ654162,ERZ654163,ERZ654164,ERZ654165,ERZ654166,ERZ654167,ERZ654168,ERZ654169,ERZ654170,ERZ654171,ERZ654172,ERZ654173,ERZ654174,ERZ654175,ERZ654176,ERZ654177,ERZ654178,ERZ654179,ERZ654180,ERZ654181,ERZ654182,ERZ654183,ERZ654184,ERZ654185,ERZ654186,ERZ654187,ERZ654188,ERZ654189,ERZ654190,ERZ654191,ERZ654192,ERZ654193,ERZ654194,ERZ654195,ERZ654196,ERZ654197,ERZ654198,ERZ654199,ERZ654200,ERZ654201,ERZ654202,ERZ654203,ERZ654204,ERZ654205,ERZ654206,ERZ654207,ERZ654208,ERZ654209,ERZ654210,ERZ654211,ERZ654212,ERZ654213,ERZ654214,ERZ654215,ERZ654216,ERZ654217,ERZ654218,ERZ654219,ERZ654220,ERZ654221,ERZ654222,ERZ654223,ERZ654224,ERZ654225,ERZ654226,ERZ654227,ERZ654228,ERZ654229,ERZ654230,ERZ654231,ERZ654232,ERZ654233,ERZ654234,ERZ654235,ERZ654236,ERZ654237,ERZ654238,ERZ654239,ERZ654240,ERZ654241,ERZ654242,ERZ654243,ERZ654244,ERZ654245,ERZ654246,ERZ654247,ERZ654248,ERZ654249,ERZ654250,ERZ654251,ERZ654252,ERZ654253,ERZ654254,ERZ654255,ERZ654256,ERZ654257,ERZ654258,ERZ654259,ERZ654260,ERZ654261,ERZ654262,ERZ654263,ERZ654264,ERZ654265,ERZ654266,ERZ654267,ERZ654268,ERZ654269,ERZ654270,ERZ654271,ERZ654272,ERZ654273,ERZ654274,ERZ654275,ERZ654276,ERZ654277,ERZ654278,ERZ654279,ERZ654280,ERZ654281,ERZ654282,ERZ654283,ERZ654284,ERZ654285,ERZ654286,ERZ654287,ERZ654288,ERZ654289,ERZ654290,ERZ654291,ERZ654292,ERZ654293,ERZ654294,ERZ654295,ERZ654296,ERZ654297,ERZ654298,ERZ654299,ERZ654300,ERZ654301,ERZ654302,ERZ654303,ERZ654304,ERZ654305,ERZ654306,ERZ654308,ERZ654309,ERZ654310,ERZ654311,ERZ654312,ERZ654313,ERZ654314,ERZ654315,ERZ654316,ERZ654317,ERZ654318,ERZ654319,ERZ654320,ERZ654321,ERZ654322,ERZ654323,ERZ654324,ERZ654325,ERZ654326,ERZ654327,ERZ654328,ERZ654329,ERZ654330,ERZ654331,ERZ654332,ERZ654333,ERZ654334,ERZ654335,ERZ654336,ERZ654337,ERZ654338,ERZ654339,ERZ654340,ERZ654341,ERZ654342,ERZ654343,ERZ654344,ERZ654345,ERZ654346,ERZ654347,ERZ65

,,,ERZ653429,ERZ654086
GO,description,category,,
GO:0004106,chorismate mutase activity,molecular function,0,1
GO:0004129,cytochrome-c oxidase activity,molecular function,1,2
GO:0005783,endoplasmic reticulum,cellular component,0,1
GO:0008218,bioluminescence,biological process,3,4
GO:0008667,2@3-dihydro-2@3-dihydroxybenzoate dehydrogenase activity,molecular function,1,5
GO:0008792,arginine decarboxylase activity,molecular function,10,11
GO:0008909,isochorismate synthase activity,molecular function,2,3
GO:0009045,xylose isomerase activity,molecular function,6,7
GO:0010468,regulation of gene expression,biological process,1,2
GO:0015232,heme transporter activity,molecular function,0,2
GO:0015886,heme transport,biological process,0,2
GO:0016163,nitrogenase activity,molecular function,0,1
GO:0019290,siderophore biosynthetic process,biological process,1,5
GO:0019684,photosynthesis@ light reaction,biological process,1,2
GO:0030077,plasma membrane light-harvesting complex,cellular component,0,1
GO:0045156,electron transporter@ transferring electrons within the cyclic electron transport pathway of photosynthesis activity,molecular function,0,1

,SRS1913960,SRS1914286,SRS1905678,SRS1905630,SRS1905878,SRS1905862,SRS1905877,SRS1905627,SRS1914276,SRS1905682,SRS1905858,SRS1905706,SRS1905526,SRS1905635,SRS1906000,SRS1905722,SRS1905902,SRS1905998,SRS1905581,SRS1905748,SRS1905608,SRS1905693,SRS1905937,SRS1905684,SRS1905662,SRS1905995,SRS1905798,SRS1905754,SRS1905936,SRS1905580,SRS1905675,SRS1905892,SRS1905750,SRS1905795,SRS1905720,SRS1905636,SRS1905590,SRS1905757,SRS1905579,SRS1905703,SRS1905852,SRS1905620,SRS1905903,SRS1905730,SRS1905719,SRS1905744,SRS1905776,SRS1905650,SRS1905939,SRS1905689,SRS1905841,SRS1905574,SRS1905822,SRS1905729,SRS1905784,SRS1905666,SRS1905851,SRS1905832,SRS1912850,SRS1913963,SRS1914284,SRS1905533,SRS1905747,SRS1905944,SRS1905899,SRS1905537,SRS1905752,SRS1905672,SRS1905738,SRS1905724,SRS1905626,SRS1905986,SRS1905589,SRS1905824,SRS1905742,SRS1905956,SRS1905585,SRS1905547,SRS1905566,SRS1905865,SRS1905913,SRS1905673,SRS1905656,SRS1905711,SRS1905791,SRS1905855,SRS1905984,SRS1905697,SRS1905522,SRS1905644,SRS1905963,SRS1905957,SRS1905994,SRS1905665,SRS1905557,SRS1905658,SRS1905671,SRS1905953,SRS1905536,SRS1905701,SRS1905619,SRS1905690,SRS1905670,SRS1905774,SRS1905727,SRS1914028,SRS1914281,SRS1914285,SRS1905926,SRS1905534,SRS1905606,SRS1905988,SRS1905805,SRS1905559,SRS1905572,SRS1905577,SRS1905761,SRS1905618,SRS1905657,SRS1905544,SRS1905726,SRS1905764,SRS1905687,SRS1905826,SRS1905799,SRS1905709,SRS1905599,SRS1914277,SRS1914278,SRS1905643,SRS1905717,SRS1905712,SRS1905804,SRS1905837,SRS1905906,SRS1905857,SRS1905587,SRS1905872,SRS1905849,SRS1905558,SRS1905714,SRS1905741,SRS1905940,SRS1905835,SRS1905705,SRS1905918,SRS1905519,SRS1905601,SRS1905782,SRS1905894,SRS1905789,SRS1905840,SRS1905987,SRS1905715,SRS1905564,SRS1905879,SRS1905847,SRS1905535,SRS1905659,SRS1905683,SRS1905527,SRS1905695,SRS1905539,SRS1905681,SRS1905777,SRS1905674,SRS1905646,SRS1905815,SRS1905803,SRS1905591,SRS1905573,SRS1905578,SRS1905964,SRS1905679,SRS1905633,SRS1905770,SRS1905938,SRS1905772,SRS1905614,SRS1905610,SRS1905629,SRS1905625,SRS1905969,SRS1905943,SRS1905952,SRS1905694,SRS1905807,SRS1905860,SRS1905592,SRS1905588,SRS1905816,SRS1905961,SRS1905552,SRS1905698,SRS1905575,SRS1905900,SRS1905827,SRS1905868,SRS1905949,SRS1905767,SRS1905634,SRS1905950,SRS1905622,SRS1905996,SRS1905992,SRS1905886,SRS1905758,SRS1905871,SRS1905762,SRS1905883,SRS1905890,SRS1905696,SRS1905977,SRS1905966,SRS1905859,SRS1905828,SRS1905648,SRS1905904,SRS1905808,SRS1905611,SRS1905876,SRS1905647,SRS1905516,SRS1905820,SRS1905783,SRS1905570,SRS1905920,SRS1905540,SRS1905801,SRS1905962,SRS1905603,SRS1905731,SRS1905725,SRS1905560,SRS1905556,SRS1905785,SRS1905542,SRS1905728,SRS1905800,SRS1905989,SRS1905652,SRS1905600,SRS1905881,SRS1905528,SRS1905641,SRS1905942,SRS1914040,SRS1914153,SRS1912909,SRS1913090,SRS1914211,SRS1914223,SRS1914239,SRS1914283,SRS1914282,SRS1905653,SRS1905787,SRS1905680,SRS1905546,SRS1905882,SRS1905834,SRS1905867,SRS1905654,SRS1905755,SRS1905778,SRS1905975,SRS1905870,SRS1905905,SRS1905983,SRS1905812,SRS1905676,SRS1905981,SRS1905605,SRS1905524,SRS1905702,SRS1905595,SRS1905971,SRS1905685,SRS1905951,SRS1905779,SRS1905749,SRS1905968,SRS1905888,SRS1905925,SRS1905873,SRS1905596,SRS1905632,SRS1905571,SRS1905997,SRS1905928,SRS1905897,SRS1905773,SRS1905818,SRS1905745,SRS1905980,SRS1905668,SRS1906002,SRS1905561,SRS1905889,SRS1905880,SRS1905972,SRS1905821,SRS1905518,SRS1905898,SRS1905598,SRS1905802,SRS1905594,SRS1905954,SRS1905763,SRS1905895,SRS1905991,SRS1905978,SRS1905814,SRS1913981,SRS1905531,SRS1905645,SRS1905864,SRS1905713,SRS1905691,SRS1905739,SRS1905999,SRS1905563,SRS1905982,SRS1905602,SRS1905721,SRS1905875,SRS1914091,SRS1914147,SRS1905765,SRS1905845,SRS1913089,SRS1913092,SRS1913095,SRS1913096,SRS1913097,SRS1913098,SRS1913099,SRS1913103,SRS1913104,SRS1913107,SRS1913111,SRS1913877,SRS1913878,SRS1913879,SRS1913880,SRS1913881,SRS1913882,SRS1913883,SRS1913884,SRS1913885,SRS1913886,SRS1913887,SRS1913888,SRS1913889,SRS1913890,SRS1913891,SRS1913892,SRS1913893,SRS1913894,SRS1913895,SRS1913896,SRS1913898,SRS1913899,SRS1913900,SRS1913901,SRS1913902,SRS1913903,SRS1913904,SRS1913905,SRS1913906,SRS1913907,SRS1913908,SRS1913909,SRS1913910,SRS1913911,SRS1913912,SRS1913913,SRS1913914,SRS1913915,SRS1913916,SRS1913917,SRS1913918,SRS1913919,SRS1913920,SRS1913921,SRS1913922,SRS1913923,SRS1913924,SRS1913925,SRS1913926,SRS1913927,SRS1913928,SRS1913929,SRS1913930,SRS1913931,SRS1913932,SRS1913933,SRS1913934,SRS1913935,SRS1913936,SRS1913937,SRS1913938,SRS1913939,SRS1913940,SRS1913941,SRS1913942,SRS1913943,SRS1913944,SRS1913945,SRS1913946,SRS1913947,SRS1913948,SRS1913949,SRS1913950,SRS1913951,SRS1913952,SRS1913953,SRS1913954,SRS1913955,SRS1913956,SRS1913957,SRS1913958,SRS1913959,SRS1913961,SRS1913962,SRS1913964,SRS1913965,SRS1913966,SRS1913967,SRS1913968,SRS1913969,SRS1913970,SRS1913971,SRS1913972,SRS1913973,SRS1913974,SRS1913975,SRS1913976,SRS1913977,SRS1913978,SRS1913979,SRS1913980,SRS1913982,SRS1913983,SRS1913984,SRS1913985,SRS1913986,SRS1913987,SRS1913988,SRS1913989,SRS1913990,SRS1913991,SRS1913992,SRS1913993,SRS1913994,SRS1913995,SRS1913996,SRS1913997,SRS1913998,SRS1913999,SRS1914000,SRS1914001,SRS1914002,SRS1914003,SRS1914004,SRS1914005,SRS1914006,SRS1914007,SRS1914008,SRS1914009,SRS1914010,SRS1914011,SRS1914012,SRS1914013,SRS1914014,SRS1914015,SRS1914016,SRS1914017,SRS1914018,SRS1914019,SRS1914020,SRS1914021,SRS1914022,SRS1914023,SRS1914024,SRS1914025,SRS1914026,SRS1914027,SRS1914029,SRS1914030,SRS1914031,SRS1914032,SRS1914033,SRS1914034,SRS1914035,SRS1914036,SRS1914037,SRS1914038,SRS1914039,SRS1914041,SRS1914042,SRS1914043,SRS1914044,SRS1914045,SRS1914046,SRS1914047,SRS1914048,SRS1914049,SRS1914050,SRS1914051,SRS1914052,SRS1914053,SRS1914054,SRS1914055,SRS1914056,SRS1914057,SRS1914058,SRS1914059,SRS1914060,SRS1914061,SRS1914062,SRS1914063,SRS1914064,SRS1914065,SRS1914066,SRS1914067,SRS1914068,SRS1914069,SRS1914070,SRS1914071,SRS1914072,SRS1914073,SRS1914074,SRS1914075,SRS1914076,SRS1914077,SRS1914078,SRS1914079,SRS1914080,SRS1914081,SRS1914082,SRS1914083,SRS1914084,SRS1914085,SRS1914086,SRS1914087,SRS1914088,SRS1914089,SRS1914090,SRS1914092,SRS1914093,SRS1914094,SRS1914095,SRS1914096,SRS1914097,SRS1914098,SRS1914099,SRS1914100,SRS1914101,SRS1914102,SRS1914103,SRS1914104,SRS1914105,SRS1914106,SRS1914107,SRS1914108,SRS1914109,SRS1914110,SRS1914111,SRS1914112,SRS1914113,SRS1914114,SRS1914115,SRS1914116,SRS1914117,SRS1914118,SRS1914119,SRS1914120,SRS1914121,SRS1914122,SRS1914123,SRS1914124,SRS1914125,SRS1914126,SRS1914127,SRS1914128,SRS1914129,SRS1914130,SRS1914131,SRS1914132,SRS1914133,SRS1914134,SRS1914135,SRS1914136,SRS1914137,SRS1914138,SRS1914139,SRS1914140,SRS1914141,SRS1914142,SRS1914143,SRS1914144,SRS1914145,SRS1914146,SRS1914148,SRS1914149,SRS1914150,SRS1914151,SRS1914152,SRS1914154,SRS1914155,SRS1914156,SRS1914157,SRS1914158,SRS1914159,SRS1914160,SRS1914161,SRS1914162,SRS1914163,SRS1914164,SRS1914165,SRS1914166,SRS1914167,SRS1914168,SRS1914169,SRS1914170,SRS1914171,SRS1914172,SRS1914173,SRS1914174,SRS1914175,SRS1914176,SRS1914177,SRS1914178,SRS1914179,SRS1914180,SRS1914181,SRS1914182,SRS1914183,SRS1914184,SRS1914185,SRS1914186,SRS1914187,SRS1914188,SRS1914189,SRS1914190,SRS1914191,SRS1914192,SRS1914193,SRS1914194,SRS1914195,SRS1914196,SRS1914197,SRS1914198,SRS1914199,SRS1914200,SRS1914201,SRS1914202,SRS1914203,SRS1914204,SRS1914205,SRS1914206,SRS1914207,SRS1914208,SRS1914209,SRS1914210,SRS1914212,SRS1914213,SRS1914214,SRS1914215,SRS1914216,SRS1914217,SRS1914218,SRS1914219,SRS1914220,SRS1914221,SRS1914222,SRS1914224,SRS1914225,SRS1914226,SRS1914227,SRS1914228,SRS1914229,SRS1914230,SRS1914231,SRS1914232,SRS1914233,SRS1914235,SRS1914236,SRS1914237,SRS1914238,SRS1914240,SRS1914241,SRS1914242,SRS1914243,SRS1914244,SRS1914245,SRS1914246,SRS1914247,SRS1914248,SRS1914249,SRS1914250,SRS1914251,SRS1914252,SRS1914253,SRS1914255,SRS1914256,SRS1914257,SRS1914258,SRS1914259,SRS1914260,SRS1914261,SRS1914262,SRS1914263,SRS1914264,SRS1914265,SRS1914266,SRS1914267,SRS1914268,SRS1914269,SRS1914270,SRS1914271,SRS1914272,SRS1914273,SRS1914274,SRS1914275,SRS1914279,SRS1914280,SRS1905515,SRS1905517,SRS1905520,SRS1905521,SRS1905523,SRS1905529,SRS1905530,SRS1905532,SRS1905538,SRS1905541,SRS1905543,SRS1905545,SRS1905548,SRS1905550,SRS1905551,SRS1905553,SRS1905554,SRS1905555,SRS1905562,SRS1905565,SRS1905568,SRS1905569,SRS1905576,SRS1905582,SRS1905583,SRS1905584,SRS1905586,SRS1905593,SRS1905597,SRS1905604,SRS1905607,SRS1905609,SRS1905612,SRS1905613,SRS1905615,SRS1905616,SRS1905617,SRS1905621,SRS1905623,SRS1905624,SRS1905628,SRS1905631,SRS1905637,SRS1905638,SRS1905639,SRS1905640,SRS1905642,SRS1905649,SRS1905651,SRS1905655,SRS1905660,SRS1905661,SRS1905664,SRS1905667,SRS1905669,SRS1905677,SRS1905686,SRS1905688,SRS1905692,SRS1905699,SRS1905700,SRS1905704,SRS1905707,SRS1905708,SRS1905710,SRS1905716,SRS1905718,SRS1905723,SRS1905732,SRS1905733,SRS1905734,SRS1905735,SRS1905736,SRS1905737,SRS1905740,SRS1905743,SRS1905746,SRS1905751,SRS1905753,SRS1905756,SRS1905759,SRS1905760,SRS1905766,SRS1905768,SRS1905769,SRS1905771,SRS1905775,SRS1905780,SRS1905781,SRS1905786,SRS1905788,SRS1905790,SRS1905792,SRS1905793,SRS1905794,SRS1905796,SRS1905797,SRS1905806,SRS1905809,SRS1905810,SRS1905811,SRS1905813,SRS1905817,SRS1905819,SRS1905823,SRS1905825,SRS1905829,SRS1905830,SRS1905831,SRS1905833,SRS1905836,SRS1905838,SRS1905839,SRS1905843,SRS1905844,SRS1905846,SRS1905848,SRS1905850,SRS1905853,SRS1905854,SRS1905856,SRS1905861,SRS1905863,SRS1905866,SRS1905869,SRS1905874,SRS1905884,SRS1905885,SRS1905887,SRS1905891,SRS1905893,SRS1905896,SRS1905901,SRS1905907,SRS1905908,SRS1905909,SRS1905910,SRS1905911,SRS1905912,SRS1905914,SRS1905915,SRS1905916,SRS1905917,SRS1905919,SRS1905921,SRS1905922,SRS1905923,SRS1905924,SRS1905929,SRS1905930,SRS1905931,SRS1905932,SRS1905933,SRS1905934,SRS1905935,SRS1905941,SRS1905945,SRS1905946,SRS1905947,SRS1905948,SRS1905955,SRS1905958,SRS1905959,SRS1905960,SRS1905965,SRS1905967,SRS1905970,SRS1905973,SRS1905974,SRS1905976,SRS1905979,SRS1905985,SRS1905990,SRS1905993,SRS1906001,SRS1912703,SRS1912704,SRS1912705,SRS1912706,SRS1912707,SRS1912709,SRS1912710,SRS1912711,SRS1912712,SRS1912713,SRS1912717,SRS1912719,SRS1912720,SRS1912721,SRS1912722,SRS1912725,SRS1912726,SRS1912728,SRS1912729,SRS1912731,SRS1912732,SRS1912733,SRS1912734,SRS1912736,SRS1912738,SRS1912739,SRS1912741,SRS1912743,SRS1912746,SRS1912747,SRS1912748,SRS1912749,SRS1912750,SRS1912754,SRS1912755,SRS1912756,SRS1912757,SRS1912758,SRS1912759,SRS1912760,SRS1912762,SRS1912763,SRS1912764,SRS1912766,SRS1912767,SRS1912768,SRS1912769,SRS1912770,SRS1912771,SRS1912772,SRS1912773,SRS1912777,SRS1912778,SRS1912780,SRS1912781,SRS1912782,SRS1912783,SRS1912784,SRS1912785,SRS1912786,SRS1912787,SRS1912788,SRS1912789,SRS1912790,SRS1912791,SRS1912792,SRS1912794,SRS1912795,SRS1912796,SRS1912798,SRS1912799,SRS1912801,SRS1912802,SRS1912803,SRS1912804,SRS1912807,SRS1912808,SRS1912809,SRS1912810,SRS1912811,SRS1912813,SRS1912814,SRS1912815,SRS1912816,SRS1912817,SRS1912818,SRS1912819,SRS1912820,SRS1912824,SRS1912826,SRS1912827,SRS1912828,SRS1912829,SRS1912830,SRS1912831,SRS1912832,SRS1912834,SRS1912836,SRS1912838,SRS1912840,SRS1912841,SRS1912844,SRS1912845,SRS1912848,SRS1912849,SRS1912854,SRS1912855,SRS1912856,SRS1912858,SRS1912859,SRS1912860,SRS1912861,SRS1912864,SRS1912865,SRS1912866,SRS1912869,SRS1912871,SRS1912872,SRS1912873,SRS1912874,SRS1912875,SRS1912876,SRS1912877,SRS1912878,SRS1912880,SRS1912882,SRS1912884,SRS1912886,SRS1912887,SRS1912891,SRS1912892,SRS1912893,SRS1912894,SRS1912895,SRS1912896,SRS1912897,SRS1912898,SRS1912899,SRS1912903,SRS1912904,SRS1912910,SRS1912912,SRS1912915,SRS1912916,SRS1912920,SRS1912921,SRS1912923,SRS1912924,SRS1912926,SRS1912928,SRS1912931,SRS1912932,SRS1912935,SRS1912937,SRS1912938,SRS1912939,SRS1912940,SRS1912941,SRS1912942,SRS1912944,SRS1912945,SRS1912948,SRS1912949,SRS1912952,SRS1912954,SRS1912955,SRS1912956,SRS1912957,SRS1912958,SRS1912959,SRS1912961,SRS1912962,SRS1912963,SRS1912967,SRS1912970,SRS1912971,SRS1912972,SRS1912973,SRS1912975,SRS1912976,SRS1912978,SRS1912979,SRS1912980,SRS1912981,SRS1912982,SRS1912985,SRS1912986,SRS1912988,SRS1912989,SRS1912990,SRS1912991,SRS1912992,SRS1912993,SRS1912994,SRS1912995,SRS1912997,SRS1912998,SRS1912999,SRS1913000,SRS1913001,SRS1913003,SRS1913004,SRS1913007,SRS1913009,SRS1913010,SRS1913011,SRS1913012,SRS1913013,SRS1913016,SRS1913017,SRS1913019,SRS1913020,SRS1913021,SRS1913022,SRS1913024,SRS1913026,SRS1913028,SRS1913029,SRS1913030,SRS1913033,SRS1913034,SRS1913035,SRS1913037,SRS1913040,SRS1913041,SRS1913044,SRS1913045,SRS1913046,SRS1913049,SRS1913050,SRS1913051,SRS1913052,SRS1913053,SRS1913055,SRS1913056,SRS1913058,SRS1913061,SRS1913063,SRS1913064,SRS1913069,SRS1913071,SRS1913072,SRS1913073,SRS1913074,SRS1913075,SRS1913076,SRS1913080,SRS1913082,SRS1913083,SRS1913084,SRS1913086,SRS1913088
"geographic location (country and/or sea,region)",USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA

{'ERZ653427': 'SRS1914055', 'ERZ653429': 'SRS1914207', 'ERZ653431': 'SRS1913984', 'ERZ653433': 'SRS1914038', 'ERZ653435': 'SRS1914053', 'ERZ653437': 'SRS1914035', 'ERZ653439': 'SRS1914137', 'ERZ653441': 'SRS1914110', 'ERZ653443': 'SRS1914155', 'ERZ653447': 'SRS1914135', 'ERZ653449': 'SRS1914006', 'ERZ653451': 'SRS1913989', 'ERZ653453': 'SRS1913991', 'ERZ653455': 'SRS1914225', 'ERZ653457': 'SRS1914074', 'ERZ653459': 'SRS1914213', 'ERZ653461': 'SRS1913985', 'ERZ653463': 'SRS1913992', 'ERZ653465': 'SRS1914227', 'ERZ653467': 'SRS1914154', 'ERZ653469': 'SRS1914252', 'ERZ654246': 'SRS1914144', 'ERZ654248': 'SRS1914172', 'ERZ653931': 'SRS1905696', 'ERZ653933': 'SRS1905598', 'ERZ653935': 'SRS1905620', 'ERZ653937': 'SRS1905601', 'ERZ653939': 'SRS1905595', 'ERZ653941': 'SRS1905537', 'ERZ653943': 'SRS1905702', 'ERZ653945': 'SRS1905569', 'ERZ653947': 'SRS1905609', 'ERZ653949': 'SRS1905692', 'ERZ653951': 'SRS1905628', 'ERZ653953': 'SRS1905740', 'ERZ653955': 'SRS1905547', 'ERZ653959': 'SRS1905566', 'ERZ653961': 'SRS1905716', 'ERZ653963': 'SRS1905532', 'ERZ653965': 'SRS1905742', 'ERZ653967': 'SRS1905752', 'ERZ653969': 'SRS1905519', 'ERZ653971': 'SRS1905536', 'ERZ653973': 'SRS1905562', 'ERZ654497': 'SRS1905700', 'ERZ654499': 'SRS1905947', 'ERZ654501': 'SRS1905639', 'ERZ654505': 'SRS1905839', 'ERZ654507': 'SRS1905548', 'ERZ653471': 'SRS1914264', 'ERZ653473': 'SRS1914261', 'ERZ653475': 'SRS1914162', 'ERZ653477': 'SRS1914141', 'ERZ653479': 'SRS1914049', 'ERZ653481': 'SRS1914070', 'ERZ653483': 'SRS1914010', 'ERZ653487': 'SRS1914239', 'ERZ653489': 'SRS1914067', 'ERZ653491': 'SRS1914011', 'ERZ653493': 'SRS1913987', 'ERZ653495': 'SRS1914258', 'ERZ653497': 'SRS1914209', 'ERZ653499': 'SRS1914126', 'ERZ653501': 'SRS1914097', 'ERZ653503': 'SRS1914116', 'ERZ653505': 'SRS1914240', 'ERZ653507': 'SRS1914250', 'ERZ653509': 'SRS1914088', 'ERZ653511': 'SRS1914000', 'ERZ654319': 'SRS1913918', 'ERZ653975': 'SRS1905759', 'ERZ653977': 'SRS1905615', 'ERZ653979': 'SRS1905580', 'ERZ653981': 'SRS1905758', 'ERZ653983': 'SRS1905526', 'ERZ653985': 'SRS1905694', 'ERZ653987': 'SRS1905584', 'ERZ653989': 'SRS1905674', 'ERZ653991': 'SRS1905539', 'ERZ653993': 'SRS1905710', 'ERZ653995': 'SRS1905518', 'ERZ653997': 'SRS1905550', 'ERZ653999': 'SRS1905662', 'ERZ654001': 'SRS1905751', 'ERZ654003': 'SRS1905632', 'ERZ654005': 'SRS1905668', 'ERZ654007': 'SRS1905552', 'ERZ654009': 'SRS1905546', 'ERZ654011': 'SRS1905579', 'ERZ654013': 'SRS1905638', 'ERZ654015': 'SRS1905551', 'ERZ654017': 'SRS1905605', 'ERZ654509': 'SRS1905664', 'ERZ654511': 'SRS1905866', 'ERZ654513': 'SRS1906001', 'ERZ654515': 'SRS1905915', 'ERZ654517': 'SRS1905990', 'ERZ654519': 'SRS1905843', 'ERZ654521': 'SRS1905737', 'ERZ654523': 'SRS1905917', 'ERZ654525': 'SRS1905631', 'ERZ654527': 'SRS1905655', 'ERZ654529': 'SRS1905908', 'ERZ654531': 'SRS1905769', 'ERZ654533': 'SRS1905930', 'ERZ654535': 'SRS1905562', 'ERZ654537': 'SRS1905621', 'ERZ654539': 'SRS1905993', 'ERZ654541': 'SRS1905965', 'ERZ654543': 'SRS1905970', 'ERZ654545': 'SRS1914280', 'ERZ654547': 'SRS1905530', 'ERZ654549': 'SRS1905836', 'ERZ654551': 'SRS1905788', 'ERZ653513': 'SRS1914008', 'ERZ653515': 'SRS1914085', 'ERZ653517': 'SRS1914181', 'ERZ653519': 'SRS1914224', 'ERZ653521': 'SRS1914025', 'ERZ653523': 'SRS1914150', 'ERZ653525': 'SRS1914208', 'ERZ653527': 'SRS1914255', 'ERZ653529': 'SRS1914172', 'ERZ653531': 'SRS1913980', 'ERZ653533': 'SRS1914204', 'ERZ653535': 'SRS1914112', 'ERZ653537': 'SRS1914194', 'ERZ653539': 'SRS1914086', 'ERZ653541': 'SRS1914048', 'ERZ653543': 'SRS1914257', 'ERZ653545': 'SRS1914083', 'ERZ653547': 'SRS1914215', 'ERZ653549': 'SRS1913976', 'ERZ653551': 'SRS1914156', 'ERZ653267': 'SRS1912771', 'ERZ653269': 'SRS1912710', 'ERZ653271': 'SRS1912817', 'ERZ653273': 'SRS1913099', 'ERZ653275': 'SRS1912869', 'ERZ653277': 'SRS1912777', 'ERZ653279': 'SRS1912897', 'ERZ653281': 'SRS1912738', 'ERZ653283': 'SRS1913052', 'ERZ653285': 'SRS1912804', 'ERZ653287': 'SRS1912880', 'ERZ653289': 'SRS1912824', 'ERZ653291': 'SRS1912784', 'ERZ653293': 'SRS1913055', 'ERZ653295': 'SRS1912972', 'ERZ653297': 'SRS1913024', 'ERZ653299': 'SRS1912982', 'ERZ653301': 'SRS1912997', 'ERZ653303': 'SRS1912818', 'ERZ653305': 'SRS1912834', 'ERZ653307': 'SRS1912861', 'ERZ653309': 'SRS1912840', 'ERZ654320': 'SRS1913986', 'ERZ654321': 'SRS1913962', 'ERZ654322': 'SRS1914246', 'ERZ654323': 'SRS1914153', 'ERZ654324': 'SRS1913951', 'ERZ654325': 'SRS1914085', 'ERZ654326': 'SRS1914114', 'ERZ654327': 'SRS1914063', 'ERZ654328': 'SRS1913995', 'ERZ654329': 'SRS1914027', 'ERZ654332': 'SRS1914235', 'ERZ654334': 'SRS1914052', 'ERZ654336': 'SRS1914043', 'ERZ654338': 'SRS1914112', 'ERZ654340': 'SRS1914068', 'ERZ654342': 'SRS1914102', 'ERZ654344': 'SRS1913950', 'ERZ654346': 'SRS1914018', 'ERZ654348': 'SRS1914083', 'ERZ654350': 'SRS1914032', 'ERZ654352': 'SRS1914094', 'ERZ654354': 'SRS1914005', 'ERZ652798': 'SRS1905960', 'ERZ652800': 'SRS1905790', 'ERZ652802': 'SRS1905921', 'ERZ652804': 'SRS1905986', 'ERZ652806': 'SRS1905983', 'ERZ652808': 'SRS1905923', 'ERZ652810': 'SRS1905853', 'ERZ652812': 'SRS1905930', 'ERZ652814': 'SRS1905799', 'ERZ652816': 'SRS1905881', 'ERZ652818': 'SRS1905847', 'ERZ652820': 'SRS1905938', 'ERZ652822': 'SRS1905972', 'ERZ652824': 'SRS1905848', 'ERZ652826': 'SRS1905784', 'ERZ654019': 'SRS1905541', 'ERZ654021': 'SRS1905704', 'ERZ654023': 'SRS1905762', 'ERZ654025': 'SRS1905640', 'ERZ654027': 'SRS1905720', 'ERZ654029': 'SRS1914270', 'ERZ654031': 'SRS1914282', 'ERZ654033': 'SRS1914286', 'ERZ654035': 'SRS1914279', 'ERZ654037': 'SRS1914272', 'ERZ654039': 'SRS1914273', 'ERZ654041': 'SRS1914285', 'ERZ654043': 'SRS1914280', 'ERZ654045': 'SRS1914274', 'ERZ654047': 'SRS1914281', 'ERZ654049': 'SRS1914259', 'ERZ654051': 'SRS1914257', 'ERZ654053': 'SRS1914038', 'ERZ654055': 'SRS1914258', 'ERZ654057': 'SRS1914152', 'ERZ654059': 'SRS1914104', 'ERZ654061': 'SRS1914029', 'ERZ652875': 'SRS1905979', 'ERZ652877': 'SRS1905819', 'ERZ652879': 'SRS1905953', 'ERZ652881': 'SRS1905781', 'ERZ652883': 'SRS1905823', 'ERZ652885': 'SRS1905918', 'ERZ652887': 'SRS1905793', 'ERZ652889': 'SRS1905845', 'ERZ652891': 'SRS1905974', 'ERZ652893': 'SRS1905997', 'ERZ652895': 'SRS1905774', 'ERZ652897': 'SRS1905952', 'ERZ652899': 'SRS1905937', 'ERZ654553': 'SRS1914279', 'ERZ654555': 'SRS1905582', 'ERZ654557': 'SRS1905896', 'ERZ654559': 'SRS1905565', 'ERZ654561': 'SRS1905732', 'ERZ654562': 'SRS1905781', 'ERZ654563': 'SRS1905924', 'ERZ654565': 'SRS1905538', 'ERZ654567': 'SRS1905809', 'ERZ654569': 'SRS1905756', 'ERZ654571': 'SRS1905941', 'ERZ654573': 'SRS1905911', 'ERZ654575': 'SRS1905907', 'ERZ654577': 'SRS1905885', 'ERZ654579': 'SRS1905850', 'ERZ654581': 'SRS1905861', 'ERZ653553': 'SRS1914096', 'ERZ653555': 'SRS1914029', 'ERZ653557': 'SRS1914212', 'ERZ653559': 'SRS1914101', 'ERZ653561': 'SRS1914228', 'ERZ653563': 'SRS1913978', 'ERZ653564': 'SRS1914111', 'ERZ653847': 'SRS1905555', 'ERZ653848': 'SRS1905726', 'ERZ653850': 'SRS1905698', 'ERZ653852': 'SRS1905766', 'ERZ653854': 'SRS1905666', 'ERZ653856': 'SRS1905635', 'ERZ653858': 'SRS1905557', 'ERZ653860': 'SRS1905749', 'ERZ653862': 'SRS1905553', 'ERZ653864': 'SRS1905646', 'ERZ653866': 'SRS1905590', 'ERZ653868': 'SRS1905599', 'ERZ653870': 'SRS1905596', 'ERZ653872': 'SRS1905737', 'ERZ653874': 'SRS1905665', 'ERZ654356': 'SRS1913994', 'ERZ654358': 'SRS1913929', 'ERZ654360': 'SRS1914217', 'ERZ654362': 'SRS1914214', 'ERZ654364': 'SRS1914203', 'ERZ654366': 'SRS1914265', 'ERZ654368': 'SRS1914253', 'ERZ654370': 'SRS1914233', 'ERZ654372': 'SRS1914255', 'ERZ654374': 'SRS1913928', 'ERZ654376': 'SRS1914208', 'ERZ654378': 'SRS1914187', 'ERZ654380': 'SRS1914092', 'ERZ654382': 'SRS1913965', 'ERZ654384': 'SRS1913890', 'ERZ654386': 'SRS1913908', 'ERZ654388': 'SRS1914002', 'ERZ654390': 'SRS1914188', 'ERZ654394': 'SRS1914004', 'ERZ654396': 'SRS1913892', 'ERZ654398': 'SRS1913924', 'ERZ654063': 'SRS1914080', 'ERZ654065': 'SRS1914095', 'ERZ654067': 'SRS1914177', 'ERZ654069': 'SRS1914045', 'ERZ654071': 'SRS1914137', 'ERZ654073': 'SRS1914206', 'ERZ654075': 'SRS1913880', 'ERZ654077': 'SRS1914081', 'ERZ654079': 'SRS1914171', 'ERZ654081': 'SRS1914046', 'ERZ654085': 'SRS1914074', 'ERZ654087': 'SRS1914180', 'ERZ654089': 'SRS1914119', 'ERZ654091': 'SRS1914170', 'ERZ654093': 'SRS1914040', 'ERZ654095': 'SRS1913919', 'ERZ654097': 'SRS1913885', 'ERZ654099': 'SRS1913974', 'ERZ654101': 'SRS1914121', 'ERZ654103': 'SRS1914238', 'ERZ654105': 'SRS1914111', 'ERZ654107': 'SRS1913927', 'ERZ652901': 'SRS1905841', 'ERZ652903': 'SRS1905786', 'ERZ652905': 'SRS1905920', 'ERZ652907': 'SRS1905867', 'ERZ652909': 'SRS1905908', 'ERZ652911': 'SRS1905830', 'ERZ652913': 'SRS1905933', 'ERZ652915': 'SRS1905897', 'ERZ652917': 'SRS1905777', 'ERZ652919': 'SRS1905866', 'ERZ652921': 'SRS1905868', 'ERZ652923': 'SRS1905955', 'ERZ652925': 'SRS1905922', 'ERZ652927': 'SRS1905780', 'ERZ652929': 'SRS1905829', 'ERZ652931': 'SRS1905900', 'ERZ652933': 'SRS1912783', 'ERZ652935': 'SRS1912952', 'ERZ653876': 'SRS1905521', 'ERZ653878': 'SRS1905578', 'ERZ653880': 'SRS1905561', 'ERZ653882': 'SRS1905641', 'ERZ653884': 'SRS1905695', 'ERZ653886': 'SRS1905589', 'ERZ653888': 'SRS1905650', 'ERZ653890': 'SRS1905719', 'ERZ653892': 'SRS1905651', 'ERZ653894': 'SRS1905647', 'ERZ653896': 'SRS1905645', 'ERZ653898': 'SRS1905660', 'ERZ653900': 'SRS1905592', 'ERZ653902': 'SRS1905538', 'ERZ653904': 'SRS1905534', 'ERZ653311': 'SRS1912733', 'ERZ653344': 'SRS1913072', 'ERZ653345': 'SRS1913021', 'ERZ653347': 'SRS1912937', 'ERZ653349': 'SRS1912816', 'ERZ653351': 'SRS1912892', 'ERZ654400': 'SRS1914091', 'ERZ654402': 'SRS1914226', 'ERZ654404': 'SRS1914244', 'ERZ654406': 'SRS1914149', 'ERZ654408': 'SRS1913882', 'ERZ654410': 'SRS1913891', 'ERZ654412': 'SRS1914176', 'ERZ654414': 'SRS1913953', 'ERZ654416': 'SRS1914256', 'ERZ654418': 'SRS1914055', 'ERZ654420': 'SRS1914219', 'ERZ654422': 'SRS1914237', 'ERZ654424': 'SRS1914036', 'ERZ654426': 'SRS1913902', 'ERZ654428': 'SRS1913937', 'ERZ654430': 'SRS1905766', 'ERZ654432': 'SRS1914273', 'ERZ654434': 'SRS1905854', 'ERZ654436': 'SRS1905532', 'ERZ654438': 'SRS1905607', 'ERZ654440': 'SRS1905710', 'ERZ654442': 'SRS1905734', 'ERZ652828': 'SRS1905772', 'ERZ652830': 'SRS1905903', 'ERZ652832': 'SRS1905838', 'ERZ652834': 'SRS1905796', 'ERZ652836': 'SRS1905878', 'ERZ652838': 'SRS1905839', 'ERZ652840': 'SRS1905884', 'ERZ652842': 'SRS1905957', 'ERZ652844': 'SRS1905851', 'ERZ652846': 'SRS1905852', 'ERZ652848': 'SRS1905969', 'ERZ652850': 'SRS1905861', 'ERZ652852': 'SRS1905818', 'ERZ652854': 'SRS1905820', 'ERZ652856': 'SRS1905929', 'ERZ652858': 'SRS1905890', 'ERZ652860': 'SRS1905875', 'ERZ654109': 'SRS1913939', 'ERZ654111': 'SRS1914009', 'ERZ654113': 'SRS1914047', 'ERZ654115': 'SRS1914023', 'ERZ654117': 'SRS1914250', 'ERZ654119': 'SRS1914189', 'ERZ654121': 'SRS1914050', 'ERZ654123': 'SRS1914098', 'ERZ654125': 'SRS1913884', 'ERZ654127': 'SRS1914241', 'ERZ654129': 'SRS1913933', 'ERZ654131': 'SRS1914212', 'ERZ654133': 'SRS1914049', 'ERZ654135': 'SRS1914165', 'ERZ654137': 'SRS1914120', 'ERZ654139': 'SRS1913961', 'ERZ654141': 'SRS1914252', 'ERZ654143': 'SRS1913966', 'ERZ654145': 'SRS1913915', 'ERZ654147': 'SRS1913909', 'ERZ654149': 'SRS1914264', 'ERZ654151': 'SRS1914011', 'ERZ652937': 'SRS1913037', 'ERZ652939': 'SRS1912814', 'ERZ652941': 'SRS1912720', 'ERZ652943': 'SRS1912993', 'ERZ652945': 'SRS1912910', 'ERZ652947': 'SRS1913098', 'ERZ652951': 'SRS1913010', 'ERZ652953': 'SRS1912712', 'ERZ652955': 'SRS1912811', 'ERZ652957': 'SRS1913069', 'ERZ652959': 'SRS1912813', 'ERZ652961': 'SRS1912926', 'ERZ652963': 'SRS1912804', 'ERZ652965': 'SRS1912982', 'ERZ652967': 'SRS1912997', 'ERZ652969': 'SRS1913019', 'ERZ652971': 'SRS1912941', 'ERZ652973': 'SRS1912733', 'ERZ652975': 'SRS1912962', 'ERZ652977': 'SRS1913030', 'ERZ653906': 'SRS1905677', 'ERZ653908': 'SRS1905563', 'ERZ653910': 'SRS1905741', 'ERZ653912': 'SRS1905517', 'ERZ653914': 'SRS1905545', 'ERZ653916': 'SRS1905593', 'ERZ653918': 'SRS1905524', 'ERZ652878': 'SRS1905817', 'ERZ652880': 'SRS1905816', 'ERZ652882': 'SRS1905815', 'ERZ652884': 'SRS1905919', 'ERZ652886': 'SRS1905959', 'ERZ652888': 'SRS1905836', 'ERZ652890': 'SRS1905891', 'ERZ652892': 'SRS1905965', 'ERZ652894': 'SRS1905798', 'ERZ652896': 'SRS1905857', 'ERZ652898': 'SRS1905850', 'ERZ652900': 'SRS1905814', 'ERZ652902': 'SRS1905856', 'ERZ654444': 'SRS1905649', 'ERZ654446': 'SRS1905976', 'ERZ654448': 'SRS1905704', 'ERZ654450': 'SRS1905935', 'ERZ654452': 'SRS1905760', 'ERZ654454': 'SRS1905838', 'ERZ654456': 'SRS1905946', 'ERZ654458': 'SRS1905848', 'ERZ654460': 'SRS1905810', 'ERZ654462': 'SRS1905686', 'ERZ654464': 'SRS1905517', 'ERZ654466': 'SRS1905830', 'ERZ654468': 'SRS1905813', 'ERZ654470': 'SRS1905699', 'ERZ654472': 'SRS1905825', 'ERZ654476': 'SRS1905811', 'ERZ654478': 'SRS1905555', 'ERZ654480': 'SRS1905846', 'ERZ654482': 'SRS1905545', 'ERZ654484': 'SRS1905955', 'ERZ654486': 'SRS1905780', 'ERZ652862': 'SRS1905896', 'ERZ652864': 'SRS1905783', 'ERZ652866': 'SRS1905806', 'ERZ652868': 'SRS1905934', 'ERZ652870': 'SRS1905876', 'ERZ652873': 'SRS1905797', 'ERZ652874': 'SRS1905947', 'ERZ652876': 'SRS1905961', 'ERZ652996': 'SRS1912807', 'ERZ652998': 'SRS1913099', 'ERZ653000': 'SRS1912818', 'ERZ653002': 'SRS1912866', 'ERZ653004': 'SRS1913046', 'ERZ653006': 'SRS1912766', 'ERZ653008': 'SRS1912829', 'ERZ653010': 'SRS1913104', 'ERZ653012': 'SRS1913022', 'ERZ653014': 'SRS1913017', 'ERZ653016': 'SRS1912767', 'ERZ653018': 'SRS1912816', 'ERZ653020': 'SRS1912780', 'ERZ653022': 'SRS1912787', 'ERZ654153': 'SRS1914020', 'ERZ654155': 'SRS1914012', 'ERZ654157': 'SRS1913905', 'ERZ654159': 'SRS1913877', 'ERZ654161': 'SRS1914033', 'ERZ654163': 'SRS1914042', 'ERZ654167': 'SRS1914066', 'ERZ654169': 'SRS1914247', 'ERZ654171': 'SRS1914197', 'ERZ654173': 'SRS1914065', 'ERZ654175': 'SRS1913971', 'ERZ654177': 'SRS1914213', 'ERZ654179': 'SRS1914204', 'ERZ654181': 'SRS1913901', 'ERZ654183': 'SRS1913990', 'ERZ654185': 'SRS1914099', 'ERZ654187': 'SRS1914248', 'ERZ654189': 'SRS1913893', 'ERZ654191': 'SRS1914079', 'ERZ654193': 'SRS1913926', 'ERZ654195': 'SRS1913952', 'ERZ654197': 'SRS1914201', 'ERZ652979': 'SRS1913051', 'ERZ652981': 'SRS1912869', 'ERZ652983': 'SRS1912894', 'ERZ652985': 'SRS1912830', 'ERZ652987': 'SRS1912738', 'ERZ652989': 'SRS1912848', 'ERZ652991': 'SRS1912976', 'ERZ652993': 'SRS1912731', 'ERZ652995': 'SRS1912856', 'ERZ652997': 'SRS1912845', 'ERZ652999': 'SRS1913061', 'ERZ653001': 'SRS1912935', 'ERZ653003': 'SRS1913003', 'ERZ653005': 'SRS1912820', 'ERZ653007': 'SRS1912781', 'ERZ653009': 'SRS1912975', 'ERZ653011': 'SRS1912763', 'ERZ653013': 'SRS1912834', 'ERZ653015': 'SRS1912732', 'ERZ653017': 'SRS1912992', 'ERZ653019': 'SRS1913021', 'ERZ653021': 'SRS1913011', 'ERZ653920': 'SRS1905600', 'ERZ653922': 'SRS1905658', 'ERZ653924': 'SRS1905594', 'ERZ653926': 'SRS1905657', 'ERZ653928': 'SRS1905564', 'ERZ653930': 'SRS1905709', 'ERZ653932': 'SRS1905629', 'ERZ653934': 'SRS1905554', 'ERZ653936': 'SRS1905743', 'ERZ653938': 'SRS1905644', 'ERZ653940': 'SRS1905701', 'ERZ653942': 'SRS1905661', 'ERZ653944': 'SRS1905763', 'ERZ653946': 'SRS1905648', 'ERZ653948': 'SRS1905591', 'ERZ653950': 'SRS1905734', 'ERZ652703': 'SRS1905946', 'ERZ652705': 'SRS1905999', 'ERZ652707': 'SRS1905846', 'ERZ652709': 'SRS1905971', 'ERZ652711': 'SRS1905977', 'ERZ652713': 'SRS1905849', 'ERZ652715': 'SRS1905925', 'ERZ652717': 'SRS1905877', 'ERZ652719': 'SRS1905915', 'ERZ652721': 'SRS1905821', 'ERZ652904': 'SRS1905871', 'ERZ652906': 'SRS1905980', 'ERZ652908': 'SRS1905822', 'ERZ652910': 'SRS1905954', 'ERZ652912': 'SRS1905906', 'ERZ652914': 'SRS1905775', 'ERZ652916': 'SRS1905883', 'ERZ652918': 'SRS1905988', 'ERZ652920': 'SRS1905964', 'ERZ652922': 'SRS1905913', 'ERZ652924': 'SRS1905950', 'ERZ652926': 'SRS1905931', 'ERZ652928': 'SRS1905882', 'ERZ652930': 'SRS1905962', 'ERZ652932': 'SRS1912955', 'ERZ652934': 'SRS1912916', 'ERZ652936': 'SRS1913095', 'ERZ652938': 'SRS1912865', 'ERZ652940': 'SRS1912771', 'ERZ652942': 'SRS1913007', 'ERZ652944': 'SRS1912728', 'ERZ652946': 'SRS1912785', 'ERZ654488': 'SRS1905797', 'ERZ654490': 'SRS1905985', 'ERZ654492': 'SRS1905919', 'ERZ654496': 'SRS1905661', 'ERZ654498': 'SRS1905554', 'ERZ654504': 'SRS1905718', 'ERZ654506': 'SRS1905638', 'ERZ654508': 'SRS1905692', 'ERZ654510': 'SRS1905617', 'ERZ654512': 'SRS1905623', 'ERZ654520': 'SRS1905624', 'ERZ654522': 'SRS1905677', 'ERZ654524': 'SRS1905746', 'ERZ654526': 'SRS1905910', 'ERZ654528': 'SRS1905609', 'ERZ654530': 'SRS1905615', 'ERZ654532': 'SRS1905973', 'ERZ653024': 'SRS1912886', 'ERZ653026': 'SRS1912717', 'ERZ653028': 'SRS1913040', 'ERZ653030': 'SRS1912710', 'ERZ653032': 'SRS1912838', 'ERZ653034': 'SRS1912939', 'ERZ653036': 'SRS1912949', 'ERZ653759': 'SRS1913939', 'ERZ653761': 'SRS1913953', 'ERZ653763': 'SRS1913942', 'ERZ653765': 'SRS1913906', 'ERZ653767': 'SRS1913882', 'ERZ653769': 'SRS1913904', 'ERZ653771': 'SRS1913930', 'ERZ653772': 'SRS1913924', 'ERZ653775': 'SRS1913019', 'ERZ653777': 'SRS1913952', 'ERZ653779': 'SRS1913955', 'ERZ653781': 'SRS1905618', 'ERZ653783': 'SRS1905634', 'ERZ653785': 'SRS1905691', 'ERZ653787': 'SRS1905714', 'ERZ653789': 'SRS1905722', 'ERZ653791': 'SRS1905617', 'ERZ653793': 'SRS1905610', 'ERZ653795': 'SRS1905559', 'ERZ654199': 'SRS1913969', 'ERZ654201': 'SRS1914008', 'ERZ654203': 'SRS1913935', 'ERZ654205': 'SRS1913958', 'ERZ654207': 'SRS1914215', 'ERZ654209': 'SRS1913978', 'ERZ654211': 'SRS1913975', 'ERZ654213': 'SRS1913947', 'ERZ654215': 'SRS1913932', 'ERZ654217': 'SRS1914147', 'ERZ654219': 'SRS1914179', 'ERZ654221': 'SRS1914006', 'ERZ654223': 'SRS1914125', 'ERZ654225': 'SRS1914199', 'ERZ654227': 'SRS1913993', 'ERZ654229': 'SRS1913887', 'ERZ654231': 'SRS1914007', 'ERZ654233': 'SRS1913917', 'ERZ654235': 'SRS1913945', 'ERZ654237': 'SRS1914150', 'ERZ654239': 'SRS1914243', 'ERZ653023': 'SRS1912832', 'ERZ653025': 'SRS1912741', 'ERZ653027': 'SRS1912826', 'ERZ653029': 'SRS1912764', 'ERZ653031': 'SRS1912963', 'ERZ653033': 'SRS1912784', 'ERZ653035': 'SRS1912750', 'ERZ653037': 'SRS1912841', 'ERZ653039': 'SRS1912749', 'ERZ653041': 'SRS1912778', 'ERZ653043': 'SRS1913092', 'ERZ653045': 'SRS1912864', 'ERZ653047': 'SRS1912871', 'ERZ653049': 'SRS1912794', 'ERZ653051': 'SRS1912795', 'ERZ653053': 'SRS1913084', 'ERZ653055': 'SRS1913049', 'ERZ653057': 'SRS1912768', 'ERZ653059': 'SRS1913096', 'ERZ653061': 'SRS1912882', 'ERZ653063': 'SRS1912755', 'ERZ653428': 'SRS1914136', 'ERZ653952': 'SRS1905548', 'ERZ653954': 'SRS1905642', 'ERZ653313': 'SRS1912920', 'ERZ653315': 'SRS1913064', 'ERZ653317': 'SRS1913090', 'ERZ653319': 'SRS1912844', 'ERZ653321': 'SRS1913022', 'ERZ653323': 'SRS1913016', 'ERZ653325': 'SRS1912783', 'ERZ653327': 'SRS1913041', 'ERZ653329': 'SRS1913086', 'ERZ653331': 'SRS1912789', 'ERZ653333': 'SRS1912952', 'ERZ653335': 'SRS1912884', 'ERZ653337': 'SRS1912915', 'ERZ653339': 'SRS1913001', 'ERZ653341': 'SRS1912981', 'ERZ653343': 'SRS1912836', 'ERZ653506': 'SRS1914185', 'ERZ653508': 'SRS1914143', 'ERZ653510': 'SRS1914220', 'ERZ653512': 'SRS1914044', 'ERZ653514': 'SRS1914018', 'ERZ653516': 'SRS1914063', 'ERZ654534': 'SRS1905775', 'ERZ654536': 'SRS1905667', 'ERZ654540': 'SRS1914272', 'ERZ654542': 'SRS1905716', 'ERZ654544': 'SRS1905884', 'ERZ654546': 'SRS1905901', 'ERZ654548': 'SRS1905597', 'ERZ654550': 'SRS1905751', 'ERZ654552': 'SRS1905796', 'ERZ654554': 'SRS1905831', 'ERZ654556': 'SRS1905853', 'ERZ654558': 'SRS1905931', 'ERZ654560': 'SRS1905612', 'ERZ654564': 'SRS1905948', 'ERZ654566': 'SRS1905529', 'ERZ654568': 'SRS1905520', 'ERZ654570': 'SRS1905833', 'ERZ654572': 'SRS1905914', 'ERZ654574': 'SRS1905584', 'ERZ654576': 'SRS1905593', 'ERZ654578': 'SRS1905553', 'ERZ653038': 'SRS1912769', 'ERZ653040': 'SRS1912747', 'ERZ653042': 'SRS1912979', 'ERZ653044': 'SRS1912739', 'ERZ653046': 'SRS1913044', 'ERZ653048': 'SRS1912815', 'ERZ653050': 'SRS1912923', 'ERZ653052': 'SRS1912895', 'ERZ653054': 'SRS1912912', 'ERZ653056': 'SRS1913024', 'ERZ653058': 'SRS1913016', 'ERZ653060': 'SRS1912757', 'ERZ653062': 'SRS1912748', 'ERZ653064': 'SRS1912896', 'ERZ653135': 'SRS1912828', 'ERZ653136': 'SRS1912854', 'ERZ653138': 'SRS1913001', 'ERZ653140': 'SRS1912739', 'ERZ653142': 'SRS1912856', 'ERZ653144': 'SRS1913104', 'ERZ653430': 'SRS1914168', 'ERZ653432': 'SRS1914211', 'ERZ653434': 'SRS1914052', 'ERZ653436': 'SRS1914164', 'ERZ653518': 'SRS1914242', 'ERZ653520': 'SRS19

,SRS1913960,SRS1905678,SRS1905630,SRS1905862,SRS1905627,SRS1914276,SRS1905682,SRS1905858,SRS1905706,SRS1906000,SRS1905902,SRS1905998,SRS1905581,SRS1905748,SRS1905608,SRS1905693,SRS1905684,SRS1905995,SRS1905754,SRS1905936,SRS1905675,SRS1905892,SRS1905750,SRS1905795,SRS1905636,SRS1905757,SRS1905703,SRS1905730,SRS1905744,SRS1905776,SRS1905939,SRS1905689,SRS1905574,SRS1905729,SRS1905832,SRS1912850,SRS1913963,SRS1914284,SRS1905533,SRS1905747,SRS1905944,SRS1905899,SRS1905672,SRS1905738,SRS1905724,SRS1905626,SRS1905824,SRS1905956,SRS1905585,SRS1905865,SRS1905673,SRS1905656,SRS1905711,SRS1905791,SRS1905855,SRS1905984,SRS1905697,SRS1905522,SRS1905963,SRS1905994,SRS1905671,SRS1905619,SRS1905690,SRS1905670,SRS1905727,SRS1914028,SRS1905926,SRS1905606,SRS1905805,SRS1905572,SRS1905577,SRS1905761,SRS1905544,SRS1905764,SRS1905687,SRS1905826,SRS1914277,SRS1914278,SRS1905643,SRS1905717,SRS1905712,SRS1905804,SRS1905837,SRS1905587,SRS1905872,SRS1905558,SRS1905940,SRS1905835,SRS1905705,SRS1905782,SRS1905894,SRS1905789,SRS1905840,SRS1905987,SRS1905715,SRS1905879,SRS1905535,SRS1905659,SRS1905683,SRS1905527,SRS1905681,SRS1905803,SRS1905573,SRS1905679,SRS1905633,SRS1905770,SRS1905614,SRS1905625,SRS1905943,SRS1905807,SRS1905860,SRS1905588,SRS1905575,SRS1905827,SRS1905949,SRS1905767,SRS1905622,SRS1905996,SRS1905992,SRS1905886,SRS1905966,SRS1905859,SRS1905828,SRS1905904,SRS1905808,SRS1905611,SRS1905516,SRS1905570,SRS1905540,SRS1905801,SRS1905603,SRS1905731,SRS1905725,SRS1905560,SRS1905556,SRS1905785,SRS1905542,SRS1905728,SRS1905800,SRS1905989,SRS1905652,SRS1905528,SRS1905942,SRS1912909,SRS1914223,SRS1914283,SRS1905653,SRS1905787,SRS1905680,SRS1905834,SRS1905654,SRS1905755,SRS1905778,SRS1905975,SRS1905870,SRS1905905,SRS1905812,SRS1905676,SRS1905981,SRS1905685,SRS1905951,SRS1905779,SRS1905968,SRS1905888,SRS1905873,SRS1905571,SRS1905928,SRS1905773,SRS1905745,SRS1906002,SRS1905889,SRS1905880,SRS1905898,SRS1905802,SRS1905895,SRS1905991,SRS1905978,SRS1913981,SRS1905531,SRS1905864,SRS1905713,SRS1905739,SRS1905982,SRS1905602,SRS1905721,SRS1905765,SRS1913089,SRS1913097,SRS1913103,SRS1913107,SRS1913111,SRS1913878,SRS1913879,SRS1913881,SRS1913883,SRS1913886,SRS1913888,SRS1913889,SRS1913894,SRS1913895,SRS1913896,SRS1913898,SRS1913899,SRS1913900,SRS1913903,SRS1913907,SRS1913910,SRS1913911,SRS1913912,SRS1913913,SRS1913914,SRS1913916,SRS1913920,SRS1913921,SRS1913922,SRS1913923,SRS1913925,SRS1913931,SRS1913934,SRS1913936,SRS1913938,SRS1913940,SRS1913941,SRS1913943,SRS1913944,SRS1913946,SRS1913948,SRS1913949,SRS1913954,SRS1913956,SRS1913957,SRS1913959,SRS1913964,SRS1913967,SRS1913968,SRS1913970,SRS1913972,SRS1913973,SRS1913977,SRS1913979,SRS1913982,SRS1913983,SRS1913988,SRS1913997,SRS1913998,SRS1913999,SRS1914001,SRS1914003,SRS1914013,SRS1914014,SRS1914016,SRS1914017,SRS1914019,SRS1914021,SRS1914022,SRS1914024,SRS1914026,SRS1914030,SRS1914034,SRS1914037,SRS1914039,SRS1914041,SRS1914051,SRS1914054,SRS1914056,SRS1914057,SRS1914058,SRS1914060,SRS1914061,SRS1914062,SRS1914064,SRS1914069,SRS1914071,SRS1914072,SRS1914073,SRS1914075,SRS1914076,SRS1914077,SRS1914078,SRS1914082,SRS1914084,SRS1914087,SRS1914089,SRS1914090,SRS1914093,SRS1914100,SRS1914105,SRS1914106,SRS1914107,SRS1914108,SRS1914109,SRS1914113,SRS1914115,SRS1914117,SRS1914118,SRS1914122,SRS1914123,SRS1914124,SRS1914127,SRS1914128,SRS1914129,SRS1914130,SRS1914131,SRS1914132,SRS1914133,SRS1914134,SRS1914138,SRS1914139,SRS1914140,SRS1914142,SRS1914145,SRS1914146,SRS1914148,SRS1914151,SRS1914157,SRS1914158,SRS1914159,SRS1914160,SRS1914161,SRS1914163,SRS1914166,SRS1914167,SRS1914169,SRS1914173,SRS1914174,SRS1914175,SRS1914178,SRS1914182,SRS1914183,SRS1914184,SRS1914186,SRS1914190,SRS1914191,SRS1914192,SRS1914193,SRS1914195,SRS1914196,SRS1914198,SRS1914200,SRS1914202,SRS1914205,SRS1914210,SRS1914216,SRS1914218,SRS1914221,SRS1914222,SRS1914229,SRS1914231,SRS1914232,SRS1914236,SRS1914245,SRS1914249,SRS1914251,SRS1914260,SRS1914262,SRS1914263,SRS1914266,SRS1914267,SRS1914268,SRS1914269,SRS1914271,SRS1914275,SRS1905515,SRS1905523,SRS1905543,SRS1905568,SRS1905576,SRS1905583,SRS1905586,SRS1905604,SRS1905613,SRS1905616,SRS1905637,SRS1905669,SRS1905688,SRS1905707,SRS1905708,SRS1905723,SRS1905733,SRS1905735,SRS1905736,SRS1905753,SRS1905768,SRS1905771,SRS1905792,SRS1905794,SRS1905844,SRS1905863,SRS1905869,SRS1905874,SRS1905887,SRS1905893,SRS1905909,SRS1905912,SRS1905916,SRS1905932,SRS1905945,SRS1905958,SRS1905967,SRS1912703,SRS1912704,SRS1912705,SRS1912706,SRS1912707,SRS1912709,SRS1912711,SRS1912713,SRS1912719,SRS1912721,SRS1912722,SRS1912725,SRS1912726,SRS1912729,SRS1912734,SRS1912736,SRS1912743,SRS1912746,SRS1912754,SRS1912756,SRS1912758,SRS1912759,SRS1912760,SRS1912762,SRS1912770,SRS1912772,SRS1912773,SRS1912782,SRS1912786,SRS1912788,SRS1912790,SRS1912791,SRS1912792,SRS1912796,SRS1912798,SRS1912799,SRS1912801,SRS1912802,SRS1912803,SRS1912808,SRS1912809,SRS1912810,SRS1912819,SRS1912827,SRS1912831,SRS1912849,SRS1912855,SRS1912858,SRS1912859,SRS1912860,SRS1912872,SRS1912873,SRS1912874,SRS1912875,SRS1912876,SRS1912877,SRS1912878,SRS1912887,SRS1912891,SRS1912893,SRS1912898,SRS1912899,SRS1912903,SRS1912904,SRS1912921,SRS1912924,SRS1912928,SRS1912931,SRS1912932,SRS1912938,SRS1912940,SRS1912942,SRS1912944,SRS1912945,SRS1912948,SRS1912954,SRS1912956,SRS1912957,SRS1912958,SRS1912959,SRS1912961,SRS1912967,SRS1912970,SRS1912971,SRS1912973,SRS1912978,SRS1912980,SRS1912985,SRS1912986,SRS1912988,SRS1912989,SRS1912990,SRS1912991,SRS1912994,SRS1912995,SRS1912998,SRS1912999,SRS1913000,SRS1913004,SRS1913009,SRS1913012,SRS1913013,SRS1913020,SRS1913026,SRS1913028,SRS1913029,SRS1913033,SRS1913034,SRS1913035,SRS1913045,SRS1913050,SRS1913053,SRS1913056,SRS1913058,SRS1913063,SRS1913071,SRS1913073,SRS1913074,SRS1913075,SRS1913076,SRS1913080,SRS1913082,SRS1913083,SRS1913088,ERZ653427,ERZ654418,ERZ653429,ERZ653431,ERZ653433,ERZ654053,ERZ653435,ERZ653437,ERZ653439,ERZ654071,ERZ653441,ERZ653443,ERZ653447,ERZ653449,ERZ654221,ERZ653451,ERZ653453,ERZ653455,ERZ653457,ERZ654085,ERZ653459,ERZ654177,ERZ653461,ERZ653463,ERZ653465,ERZ653467,ERZ653469,ERZ654141,ERZ654246,ERZ654248,ERZ653529,ERZ653931,ERZ653933,ERZ653935,ERZ653937,ERZ653939,ERZ653941,ERZ653943,ERZ653945,ERZ653947,ERZ654528,ERZ653949,ERZ654508,ERZ653951,ERZ653953,ERZ653955,ERZ653959,ERZ653961,ERZ654542,ERZ653963,ERZ654436,ERZ653965,ERZ653967,ERZ653969,ERZ653971,ERZ653973,ERZ654535,ERZ654497,ERZ654499,ERZ652874,ERZ654501,ERZ654505,ERZ652838,ERZ654507,ERZ653952,ERZ653471,ERZ654149,ERZ653473,ERZ653475,ERZ653477,ERZ653479,ERZ654133,ERZ653481,ERZ653483,ERZ653487,ERZ653489,ERZ653491,ERZ654151,ERZ653493,ERZ653495,ERZ654055,ERZ653497,ERZ653499,ERZ653501,ERZ653503,ERZ653505,ERZ653507,ERZ654117,ERZ653509,ERZ653511,ERZ654319,ERZ653975,ERZ653977,ERZ654530,ERZ653979,ERZ653981,ERZ653983,ERZ653985,ERZ653987,ERZ654574,ERZ653989,ERZ653991,ERZ653993,ERZ654440,ERZ653995,ERZ653997,ERZ653999,ERZ654001,ERZ654550,ERZ654003,ERZ654005,ERZ654007,ERZ654009,ERZ654011,ERZ654013,ERZ654506,ERZ654015,ERZ654017,ERZ654509,ERZ654511,ERZ652919,ERZ654513,ERZ654515,ERZ652719,ERZ654517,ERZ654519,ERZ654521,ERZ653872,ERZ654523,ERZ654525,ERZ654527,ERZ654529,ERZ652909,ERZ654531,ERZ654533,ERZ652812,ERZ654537,ERZ654539,ERZ654541,ERZ652892,ERZ654543,ERZ654545,ERZ654043,ERZ654547,ERZ654549,ERZ652888,ERZ654551,ERZ653513,ERZ654201,ERZ653515,ERZ654325,ERZ653517,ERZ653519,ERZ653521,ERZ653523,ERZ654237,ERZ653525,ERZ654376,ERZ653527,ERZ654372,ERZ653531,ERZ653533,ERZ654179,ERZ653535,ERZ654338,ERZ653537,ERZ653539,ERZ653541,ERZ653543,ERZ654051,ERZ653545,ERZ654348,ERZ653547,ERZ654207,ERZ653549,ERZ653551,ERZ653267,ERZ652940,ERZ653269,ERZ653030,ERZ653271,ERZ653273,ERZ652998,ERZ653275,ERZ652981,ERZ653277,ERZ653279,ERZ653281,ERZ652987,ERZ653283,ERZ653285,ERZ652963,ERZ653287,ERZ653289,ERZ653291,ERZ653033,ERZ653293,ERZ653295,ERZ653297,ERZ653056,ERZ653299,ERZ652965,ERZ653301,ERZ652967,ERZ653303,ERZ653000,ERZ653305,ERZ653013,ERZ653307,ERZ653309,ERZ654320,ERZ654321,ERZ654322,ERZ653538,ERZ654323,ERZ654324,ERZ654326,ERZ654327,ERZ653516,ERZ654328,ERZ654329,ERZ654332,ERZ654334,ERZ653434,ERZ654336,ERZ654340,ERZ654342,ERZ654344,ERZ654346,ERZ653514,ERZ654350,ERZ654352,ERZ654354,ERZ652798,ERZ652800,ERZ652802,ERZ652804,ERZ652806,ERZ652808,ERZ652810,ERZ654556,ERZ652814,ERZ652816,ERZ652818,ERZ652820,ERZ652822,ERZ652824,ERZ654458,ERZ652826,ERZ654019,ERZ654021,ERZ654448,ERZ654023,ERZ654025,ERZ654027,ERZ654029,ERZ654031,ERZ654033,ERZ654035,ERZ654553,ERZ654037,ERZ654540,ERZ654039,ERZ654432,ERZ654041,ERZ654045,ERZ654047,ERZ654049,ERZ654057,ERZ654059,ERZ654061,ERZ653555,ERZ652875,ERZ652877,ERZ652879,ERZ652881,ERZ654562,ERZ652883,ERZ652885,ERZ652887,ERZ652889,ERZ652891,ERZ652893,ERZ652895,ERZ652897,ERZ652899,ERZ654555,ERZ654557,ERZ652862,ERZ654559,ERZ654561,ERZ654563,ERZ654565,ERZ653902,ERZ654567,ERZ654569,ERZ654571,ERZ654573,ERZ654575,ERZ654577,ERZ654579,ERZ652898,ERZ654581,ERZ652850,ERZ653553,ERZ653557,ERZ654131,ERZ653559,ERZ653561,ERZ653563,ERZ654209,ERZ653564,ERZ654105,ERZ653847,ERZ654478,ERZ653848,ERZ653850,ERZ653852,ERZ654430,ERZ653854,ERZ653856,ERZ653858,ERZ653860,ERZ653862,ERZ654578,ERZ653864,ERZ653866,ERZ653868,ERZ653870,ERZ653874,ERZ654356,ERZ654358,ERZ654360,ERZ653526,ERZ654362,ERZ654364,ERZ654366,ERZ654368,ERZ654370,ERZ654374,ERZ654378,ERZ654380,ERZ654382,ERZ654384,ERZ654386,ERZ654388,ERZ654390,ERZ654394,ERZ654396,ERZ654398,ERZ653772,ERZ654063,ERZ653524,ERZ654065,ERZ654067,ERZ654069,ERZ654073,ERZ653536,ERZ654075,ERZ654077,ERZ654079,ERZ654081,ERZ654087,ERZ654089,ERZ654091,ERZ654093,ERZ654095,ERZ654097,ERZ654099,ERZ654101,ERZ654103,ERZ654107,ERZ652901,ERZ652903,ERZ652905,ERZ652907,ERZ652911,ERZ654466,ERZ652913,ERZ652915,ERZ652917,ERZ652921,ERZ652923,ERZ654484,ERZ652925,ERZ652927,ERZ654486,ERZ652929,ERZ652931,ERZ652933,ERZ653325,ERZ652935,ERZ653333,ERZ653876,ERZ653878,ERZ653880,ERZ653882,ERZ653884,ERZ653886,ERZ653888,ERZ653890,ERZ653892,ERZ653894,ERZ653896,ERZ653898,ERZ653900,ERZ653904,ERZ653311,ERZ652973,ERZ653344,ERZ653345,ERZ653019,ERZ653347,ERZ653349,ERZ653018,ERZ653351,ERZ654400,ERZ654402,ERZ654404,ERZ654406,ERZ654408,ERZ653767,ERZ654410,ERZ654412,ERZ654414,ERZ653761,ERZ654416,ERZ654420,ERZ654422,ERZ654424,ERZ654426,ERZ654428,ERZ654434,ERZ654438,ERZ654442,ERZ653950,ERZ652828,ERZ652830,ERZ652832,ERZ654454,ERZ652834,ERZ654552,ERZ652836,ERZ652840,ERZ654544,ERZ652842,ERZ652844,ERZ652846,ERZ652848,ERZ652852,ERZ652854,ERZ652856,ERZ652858,ERZ652860,ERZ654109,ERZ653759,ERZ654111,ERZ654113,ERZ654115,ERZ654119,ERZ654121,ERZ654123,ERZ654125,ERZ654127,ERZ654129,ERZ654135,ERZ654137,ERZ654139,ERZ654143,ERZ654145,ERZ654147,ERZ652937,ERZ652939,ERZ652941,ERZ652943,ERZ652945,ERZ652947,ERZ652951,ERZ652953,ERZ652955,ERZ652957,ERZ652959,ERZ652961,ERZ652969,ERZ653775,ERZ652971,ERZ652975,ERZ652977,ERZ653906,ERZ654522,ERZ653908,ERZ653910,ERZ653912,ERZ654464,ERZ653914,ERZ654482,ERZ653916,ERZ654576,ERZ653918,ERZ652878,ERZ652880,ERZ652882,ERZ652884,ERZ654492,ERZ652886,ERZ652890,ERZ652894,ERZ652896,ERZ652900,ERZ652902,ERZ654444,ERZ654446,ERZ654450,ERZ654452,ERZ654456,ERZ652703,ERZ654460,ERZ654462,ERZ654468,ERZ654470,ERZ654472,ERZ654476,ERZ654480,ERZ652707,ERZ652864,ERZ652866,ERZ652868,ERZ652870,ERZ652873,ERZ654488,ERZ652876,ERZ652996,ERZ653002,ERZ653004,ERZ653006,ERZ653008,ERZ653010,ERZ653144,ERZ653012,ERZ653321,ERZ653014,ERZ653016,ERZ653020,ERZ653022,ERZ654153,ERZ654155,ERZ654157,ERZ654159,ERZ654161,ERZ654163,ERZ654167,ERZ654169,ERZ654171,ERZ654173,ERZ654175,ERZ654181,ERZ654183,ERZ654185,ERZ654187,ERZ654189,ERZ654191,ERZ654193,ERZ654195,ERZ653777,ERZ654197,ERZ652979,ERZ652983,ERZ652985,ERZ652989,ERZ652991,ERZ652993,ERZ652995,ERZ653142,ERZ652997,ERZ652999,ERZ653001,ERZ653003,ERZ653005,ERZ653007,ERZ653009,ERZ653011,ERZ653015,ERZ653017,ERZ653021,ERZ653920,ERZ653922,ERZ653924,ERZ653926,ERZ653928,ERZ653930,ERZ653932,ERZ653934,ERZ654498,ERZ653936,ERZ653938,ERZ653940,ERZ653942,ERZ654496,ERZ653944,ERZ653946,ERZ653948,ERZ652705,ERZ652709,ERZ652711,ERZ652713,ERZ652715,ERZ652717,ERZ652721,ERZ652904,ERZ652906,ERZ652908,ERZ652910,ERZ652912,ERZ652914,ERZ654534,ERZ652916,ERZ652918,ERZ652920,ERZ652922,ERZ652924,ERZ652926,ERZ654558,ERZ652928,ERZ652930,ERZ652932,ERZ652934,ERZ652936,ERZ652938,ERZ652942,ERZ652944,ERZ652946,ERZ654490,ERZ654504,ERZ654510,ERZ653791,ERZ654512,ERZ654520,ERZ654524,ERZ654526,ERZ654532,ERZ653024,ERZ653026,ERZ653028,ERZ653032,ERZ653034,ERZ653036,ERZ653763,ERZ653765,ERZ653769,ERZ653771,ERZ653779,ERZ653781,ERZ653783,ERZ653785,ERZ653787,ERZ653789,ERZ653793,ERZ653795,ERZ654199,ERZ654203,ERZ654205,ERZ654211,ERZ654213,ERZ654215,ERZ654217,ERZ654219,ERZ654223,ERZ654225,ERZ654227,ERZ654229,ERZ654231,ERZ654233,ERZ654235,ERZ654239,ERZ653023,ERZ653025,ERZ653027,ERZ653029,ERZ653031,ERZ653035,ERZ653037,ERZ653039,ERZ653041,ERZ653043,ERZ653045,ERZ653047,ERZ653049,ERZ653051,ERZ653053,ERZ653055,ERZ653057,ERZ653059,ERZ653061,ERZ653063,ERZ653428,ERZ653954,ERZ653313,ERZ653315,ERZ653317,ERZ653319,ERZ653323,ERZ653058,ERZ653327,ERZ653329,ERZ653331,ERZ653335,ERZ653337,ERZ653339,ERZ653138,ERZ653341,ERZ653343,ERZ653506,ERZ653508,ERZ653510,ERZ653512,ERZ654536,ERZ654546,ERZ654548,ERZ654554,ERZ654560,ERZ654564,ERZ654566,ERZ654568,ERZ654570,ERZ654572,ERZ653038,ERZ653040,ERZ653042,ERZ653044,ERZ653140,ERZ653046,ERZ653048,ERZ653050,ERZ653052,ERZ653054,ERZ653060,ERZ653062,ERZ653064,ERZ653135,ERZ653136,ERZ653430,ERZ653432,ERZ653436,ERZ653518,ERZ653520,ERZ653522,ERZ653528,ERZ653530,ERZ653532,ERZ653540
"geographic location (country and/or sea,region)",USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA

           single strand break repair  phosphopyruvate hydratase complex  \
ERZ652703                           0                                 10
ERZ652705                           0                                 27
ERZ652707                           0                                  1
ERZ652709                           0                                 20
ERZ652711                           0                                 21

           mannosyltransferase activity  adenine deaminase activity  \
ERZ652703                             1                           0
ERZ652705                             3                           3
ERZ652707                             0                           0
ERZ652709                             1                           2
ERZ652711                             2                           4

           transition metal ion transport  protein targeting to Golgi  \
ERZ652703                               1                           0
ERZ652705                               5                           0
ERZ652707                               0                           0
ERZ652709                               5                           0
ERZ652711                               3                           0

           tRNA binding  fatty-acyl-CoA binding  \
ERZ652703            30                       0
ERZ652705           105                       0
ERZ652707            15                       0
ERZ652709            79                       1
ERZ652711            67                       1

           mitotic sister chromatid segregation  DNA damage checkpoint  \
ERZ652703                                     0                      0
ERZ652705                                     0                      0
ERZ652707                                     0                      0
ERZ652709                                     0                      0
ERZ652711                                     0                      0

           regulation of cyclin-dependent protein serine/threonine kinase activity  \
ERZ652703                                                                        0
ERZ652705                                                                        0
ERZ652707                                                                        0
ERZ652709                                                                        0
ERZ652711                                                                        0

           sulfate assimilation  succinate dehydrogenase activity  \
ERZ652703                     4                                 0
ERZ652705                     5                                 1
ERZ652707                     0                                 0
ERZ652709                     4                                 5
ERZ652711                     4                                 2

           histidine biosynthetic process  \
ERZ652703                              55
ERZ652705                             155
ERZ652707                              24
ERZ652709                              93
ERZ652711                             117

           imidazoleglycerol-phosphate synthase activity  \
ERZ652703                                              4
ERZ652705                                             14
ERZ652707                                              2
ERZ652709                                              6
ERZ652711                                              6

           histone acetyltransferase complex  flocculation  Golgi membrane  \
ERZ652703                                  0             0               0
ERZ652705                                  0             0               0
ERZ652707                                  0             0               0
ERZ652709                                  0             0               0
ERZ652711                                  0             0               0

           exocyst  1@3-beta-D-glucan synthase complex  recombinase activity  \
ERZ652703        0                                   0                    92
ERZ652705        0                                   0                   307
ERZ652707        0                                   0                    73
ERZ652709        0                                   0                   110
ERZ652711        0                                   0                   161

           ubiquitin ligase complex  rRNA modification  \
ERZ652703                         0                  4
ERZ652705                         0                 22
ERZ652707                         0                  2
ERZ652709                         0                 15
ERZ652711                         0                 17

           phosphorelay sensor kinase activity  \
ERZ652703                                  286
ERZ652705                                  416
ERZ652707                                   58
ERZ652709                                  258
ERZ652711                                  443

           phosphorelay response regulator activity  \
ERZ652703                                         1
ERZ652705                                        10
ERZ652707                                         2
ERZ652709                                         6
ERZ652711                                        11

           protein phosphatase type 2A complex  \
ERZ652703                                    0
ERZ652705                                    0
ERZ652707                                    0
ERZ652709                                    0
ERZ652711                                    0

           phosphorelay signal transduction system  \
ERZ652703                                      363
ERZ652705                                      811
ERZ652707                                      129
ERZ652709                                      486
ERZ652711                                      715

           tryptophan biosynthetic process  nucleotide binding  \
ERZ652703                                7                 291
ERZ652705                               20                 829
ERZ652707                                4                 122
ERZ652709                               11                 636
ERZ652711                               13                 645

           ribonuclease MRP complex  3'-5'-exoribonuclease activity  \
ERZ652703                         0                               8
ERZ652705                         0                              17
ERZ652707                         0                               6
ERZ652709                         0                              14
ERZ652711                         0                              16

           nuclear exosome (RNase complex)  exosome (RNase complex)  \
ERZ652703                                0                        0
ERZ652705                                0                        0
ERZ652707                                0                        0
ERZ652709                                0                        0
ERZ652711                                0                        0

           rRNA (adenine-N6@N6-)-dimethyltransferase activity  \
ERZ652703                                                   6
ERZ652705                                                  24
ERZ652707                                                   2
ERZ652709                                                  17
ERZ652711                                                  19

           nuclear-transcribed mRNA catabolic process@ nonsense-mediated decay  \
ERZ652703                                                                    0
ERZ652705                                                                    0
ERZ652707                                                                    0
ERZ652709                                                                    0
ERZ652711                                                                    0

           tRNA-intron endonuclease activity  \
ERZ652703                                  0
ERZ652705                                  0
ERZ652707                                  0
ERZ652709                                  0
ERZ652711                                  0

           vacuolar proton-transporting V-type ATPase@ V1 domain  \
ERZ652703                                                      0
ERZ652705                                                      0
ERZ652707                                                      0
ERZ652709                                                      0
ERZ652711                                                      0

           microtubule cytoskeleton organization  nuclear chromosome  \
ERZ652703                                      0                   0
ERZ652705                                      0                   0
ERZ652707                                      0                   0
ERZ652709                                      0                   0
ERZ652711                                      0                   0

           allantoin catabolic process  mitochondrial fission  \
ERZ652703                            0                      0
ERZ652705                            1                      0
ERZ652707                            0                      0
ERZ652709                            4                      0
ERZ652711                            3                      0

           peptidoglycan metabolic process  \
ERZ652703                                6
ERZ652705                                9
ERZ652707                                2
ERZ652709                               12
ERZ652711                               12

           polysaccharide biosynthetic process  \
ERZ652703                                   11
ERZ652705                                   28
ERZ652707                                    4
ERZ652709                                   18
ERZ652711                                   24

           polysaccharide catabolic process  \
ERZ652703                                12
ERZ652705                                26
ERZ652707                                 1
ERZ652709                                 3
ERZ652711                                14

           mitochondrial proton-transporting ATP synthase complex@ catalytic core F(1)  \
ERZ652703                                                                            0
ERZ652705                                                                            0
ERZ652707                                                                            0
ERZ652709                                                                            0
ERZ652711                                                                            0

           mitochondrial proton-transporting ATP synthase complex@ coupling factor F(o)  \
ERZ652703                                                                             0
ERZ652705                                                                             0
ERZ652707                                                                             0
ERZ652709                                                                             0
ERZ652711                                                                             0

           mitotic cell cycle  alanine dehydrogenase activity  \
ERZ652703                   0                               3
ERZ652705                   0                               4
ERZ652707                   0                               1
ERZ652709                   0                               2
ERZ652711                   0                               2

           magnesium ion binding  \
ERZ652703                    105
ERZ652705                    301
ERZ652707                     33
ERZ652709                    237
ERZ652711                    234

           deadenylation-dependent decapping of nuclear-transcribed mRNA  \
ERZ652703                                                              0
ERZ652705                                                              0
ERZ652707                                                              0
ERZ652709                                                              0
ERZ652711                                                              0

           response to reactive oxygen species  \
ERZ652703                                    3
ERZ652705                                    0
ERZ652707                                    0
ERZ652709                                    2
ERZ652711                                    3

           nicotinamide-nucleotide adenylyltransferase activity  \
ERZ652703                                                     0
ERZ652705                                                     0
ERZ652707                                                     0
ERZ652709                                                     0
ERZ652711                                                     0

           3-hydroxyanthranilate 3@4-dioxygenase activity  \
ERZ652703                                               0
ERZ652705                                               0
ERZ652707                                               0
ERZ652709                                               0
ERZ652711                                               0

           RNA 7-methylguanosine cap binding  \
ERZ652703                                  0
ERZ652705                                  0
ERZ652707                                  0
ERZ652709                                  0
ERZ652711                                  0

           generation of catalytic spliceosome for second transesterification step  \
ERZ652703                                                                        0
ERZ652705                                                                        0
ERZ652707                                                                        0
ERZ652709                                                                        0
ERZ652711                                                                        0

           Group I intron splicing  mRNA splicing@ via spliceosome  \
ERZ652703                        0                               0
ERZ652705                        0                               0
ERZ652707                        0                               0
ERZ652709                        0                               0
ERZ652711                        0                               0

           EKC/KEOPS complex  protein peptidyl-prolyl isomerization  \
ERZ652703                  0                                     14
ERZ652705                  0                                     39
ERZ652707                  0                                      6
ERZ652709                  0                                     26
ERZ652711                  0                                     26

           core TFIIH complex  \
ERZ652703                   0
ERZ652705                   0
ERZ652707                   0
ERZ652709                   0
ERZ652711                   0

           THO complex part of transcription export complex  \
ERZ652703                                                 0
ERZ652705                                                 0
ERZ652707                                                 0
ERZ652709                                                 0
ERZ652711                                                 0

           maturation of SSU-rRNA from tricistronic rRNA transcript (SSU-rRNA@ 5.8S rRNA@ LSU-rRNA)  \
ERZ652703                                                                                         0
ERZ652705                                                                                         0
ERZ652707                                                                                         0
ERZ652709                                                                                         0
ERZ652711                                                                                         0

           cleavage involved in rRNA processing  proteasome complex  \
ERZ652703                                     0                   0
ERZ652705                                     0                   0
ERZ652707                                     0                   0
ERZ652709                                     0                   0
ERZ652711                                     0                   0

           telomere maintenance  \
ERZ652703                     7
ERZ652705                    15
ERZ652707                     2
ERZ652709                     5
ERZ652711                     6

           double-strand break repair via homologous recombination  \
ERZ652703                                                        0
ERZ652705                                                        0
ERZ652707                                                        0
ERZ652709                                                        0
ERZ652711                                                        0

           DNA catabolic process@ endonucleolytic  conjugation  \
ERZ652703                                       0            0
ERZ652705                                       0            0
ERZ652707                                       0            0
ERZ652709                                       0            1
ERZ652711                                       0            1

           pheromone-dependent signal transduction involved in conjugation with cellular fusion  \
ERZ652703                                                                                     0
ERZ652705                                                                                     0
ERZ652707                                                                                     0
ERZ652709                                                                                     0
ERZ652711                                                                                     0

           mating pheromone activity  \
ERZ652703                          0
ERZ652705                          0
ERZ652707                          0
ERZ652709                          0
ERZ652711                          0

           adenyl-nucleotide exchange factor activity  \
ERZ652703                                          11
ERZ652705                                          23
ERZ652707                                           5
ERZ652709                                          21
ERZ652711                                          15

           chromosome@ centromeric region  kinetochore  chromatin  nucleosome  \
ERZ652703                               0            0          0           0
ERZ652705                               0            0          0           1
ERZ652707                               0            0          0           0
ERZ652709                               0            0          0           0
ERZ652711                               0            0          0           0

           synaptonemal complex  condensin complex  \
ERZ652703                     0                  0
ERZ652705                     0                  0
ERZ652707                     0                  0
ERZ652709                     0                  0
ERZ652711                     0                  0

           origin recognition complex  ESCRT I complex  cell morphogenesis  \
ERZ652703                           0                0                  13
ERZ652705                           0                0                  47
ERZ652707                           0                0                  10
ERZ652709                           0                0                  32
ERZ652711                           0                0                  37

           6@7-dimethyl-8-ribityllumazine synthase activity  \

750

In [57]:

print(len(combined_data))

combined_data = summary.join(metadata, how="outer")
display(combined_data.head())
print(len(combined_data))

print(len(summary))
print(len(metadata))

print(len(set(summary.index)))
print(len(set(metadata.index)))
print(len(set(summary.index) - set(metadata.index)))

print((set(summary.index) - set(metadata.index)))
print((set(metadata.index) - set(summary.index)))

750

            single strand break repair  phosphopyruvate hydratase complex  \
ERZ1026774                         0.0                               36.0
ERZ1026777                         0.0                               44.0
ERZ1026906                         0.0                               16.0
ERZ1026907                         0.0                               16.0
ERZ1026908                         0.0                                4.0

            mannosyltransferase activity  adenine deaminase activity  \
ERZ1026774                           2.0                         3.0
ERZ1026777                           2.0                         3.0
ERZ1026906                           0.0                         2.0
ERZ1026907                           1.0                         1.0
ERZ1026908                           0.0                         0.0

            transition metal ion transport  protein targeting to Golgi  \
ERZ1026774                             7.0                         0.0
ERZ1026777                             7.0                         0.0
ERZ1026906                             1.0                         0.0
ERZ1026907                             2.0                         0.0
ERZ1026908                             1.0                         0.0

            tRNA binding  fatty-acyl-CoA binding  \
ERZ1026774         143.0                     1.0
ERZ1026777         139.0                     0.0
ERZ1026906          52.0                     0.0
ERZ1026907          52.0                     0.0
ERZ1026908           2.0                     0.0

            mitotic sister chromatid segregation  DNA damage checkpoint  \
ERZ1026774                                   0.0                    0.0
ERZ1026777                                   0.0                    0.0
ERZ1026906                                   0.0                    0.0
ERZ1026907                                   0.0                    0.0
ERZ1026908                                   0.0                    0.0

            regulation of cyclin-dependent protein serine/threonine kinase activity  \
ERZ1026774                                                                      0.0
ERZ1026777                                                                      0.0
ERZ1026906                                                                      0.0
ERZ1026907                                                                      0.0
ERZ1026908                                                                      0.0

            sulfate assimilation  succinate dehydrogenase activity  \
ERZ1026774                   3.0                               5.0
ERZ1026777                   3.0                               3.0
ERZ1026906                   3.0                               1.0
ERZ1026907                   0.0                               0.0
ERZ1026908                   0.0                               0.0

            histidine biosynthetic process  \
ERZ1026774                           180.0
ERZ1026777                           195.0
ERZ1026906                            89.0
ERZ1026907                            68.0
ERZ1026908                             0.0

            imidazoleglycerol-phosphate synthase activity  \
ERZ1026774                                            8.0
ERZ1026777                                           11.0
ERZ1026906                                            5.0
ERZ1026907                                            3.0
ERZ1026908                                            0.0

            histone acetyltransferase complex  flocculation  Golgi membrane  \
ERZ1026774                                0.0           0.0             0.0
ERZ1026777                                0.0           0.0             0.0
ERZ1026906                                0.0           0.0             0.0
ERZ1026907                                0.0           0.0             0.0
ERZ1026908                                0.0           0.0             0.0

            exocyst  1@3-beta-D-glucan synthase complex  recombinase activity  \
ERZ1026774      0.0                                 0.0                 355.0
ERZ1026777      0.0                                 0.0                 380.0
ERZ1026906      0.0                                 0.0                 137.0
ERZ1026907      0.0                                 0.0                 192.0
ERZ1026908      0.0                                 0.0                   4.0

            ubiquitin ligase complex  rRNA modification  \
ERZ1026774                       0.0               22.0
ERZ1026777                       0.0               27.0
ERZ1026906                       0.0               10.0
ERZ1026907                       0.0                9.0
ERZ1026908                       0.0                0.0

            phosphorelay sensor kinase activity  \
ERZ1026774                                482.0
ERZ1026777                                509.0
ERZ1026906                                312.0
ERZ1026907                                191.0
ERZ1026908                                  1.0

            phosphorelay response regulator activity  \
ERZ1026774                                      12.0
ERZ1026777                                       8.0
ERZ1026906                                       1.0
ERZ1026907                                       2.0
ERZ1026908                                       0.0

            protein phosphatase type 2A complex  \
ERZ1026774                                  1.0
ERZ1026777                                  0.0
ERZ1026906                                  0.0
ERZ1026907                                  0.0
ERZ1026908                                  0.0

            phosphorelay signal transduction system  \
ERZ1026774                                    925.0
ERZ1026777                                    961.0
ERZ1026906                                    511.0
ERZ1026907                                    366.0
ERZ1026908                                     10.0

            tryptophan biosynthetic process  nucleotide binding  \
ERZ1026774                             15.0              1165.0
ERZ1026777                             25.0              1254.0
ERZ1026906                              9.0               385.0
ERZ1026907                              6.0               510.0
ERZ1026908                              0.0                 1.0

            ribonuclease MRP complex  3'-5'-exoribonuclease activity  \
ERZ1026774                       0.0                            28.0
ERZ1026777                       0.0                            28.0
ERZ1026906                       0.0                            10.0
ERZ1026907                       0.0                            10.0
ERZ1026908                       0.0                             0.0

            nuclear exosome (RNase complex)  exosome (RNase complex)  \
ERZ1026774                              0.0                      0.0
ERZ1026777                              0.0                      0.0
ERZ1026906                              0.0                      0.0
ERZ1026907                              0.0                      0.0
ERZ1026908                              0.0                      0.0

            rRNA (adenine-N6@N6-)-dimethyltransferase activity  \
ERZ1026774                                                28.0
ERZ1026777                                                29.0
ERZ1026906                                                10.0
ERZ1026907                                                11.0
ERZ1026908                                                 0.0

            nuclear-transcribed mRNA catabolic process@ nonsense-mediated decay  \
ERZ1026774                                                                  0.0
ERZ1026777                                                                  0.0
ERZ1026906                                                                  0.0
ERZ1026907                                                                  0.0
ERZ1026908                                                                  0.0

            tRNA-intron endonuclease activity  \
ERZ1026774                                0.0
ERZ1026777                                1.0
ERZ1026906                                0.0
ERZ1026907                                0.0
ERZ1026908                                0.0

            vacuolar proton-transporting V-type ATPase@ V1 domain  \
ERZ1026774                                                    0.0
ERZ1026777                                                    0.0
ERZ1026906                                                    0.0
ERZ1026907                                                    0.0
ERZ1026908                                                    0.0

            microtubule cytoskeleton organization  nuclear chromosome  \
ERZ1026774                                    0.0                 0.0
ERZ1026777                                    0.0                 0.0
ERZ1026906                                    0.0                 0.0
ERZ1026907                                    0.0                 0.0
ERZ1026908                                    0.0                 0.0

            allantoin catabolic process  mitochondrial fission  \
ERZ1026774                          1.0                    0.0
ERZ1026777                          0.0                    0.0
ERZ1026906                          0.0                    0.0
ERZ1026907                          1.0                    0.0
ERZ1026908                          0.0                    0.0

            peptidoglycan metabolic process  \
ERZ1026774                             14.0
ERZ1026777                             12.0
ERZ1026906                              5.0
ERZ1026907                              3.0
ERZ1026908                              0.0

            polysaccharide biosynthetic process  \
ERZ1026774                                 40.0
ERZ1026777                                 47.0
ERZ1026906                                 14.0
ERZ1026907                                  8.0
ERZ1026908                                  0.0

            polysaccharide catabolic process  \
ERZ1026774                              12.0
ERZ1026777                              19.0
ERZ1026906                               2.0
ERZ1026907                               7.0
ERZ1026908                               3.0

            mitochondrial proton-transporting ATP synthase complex@ catalytic core F(1)  \
ERZ1026774                                                                          0.0
ERZ1026777                                                                          0.0
ERZ1026906                                                                          0.0
ERZ1026907                                                                          0.0
ERZ1026908                                                                          0.0

            mitochondrial proton-transporting ATP synthase complex@ coupling factor F(o)  \
ERZ1026774                                                                           0.0
ERZ1026777                                                                           0.0
ERZ1026906                                                                           0.0
ERZ1026907                                                                           0.0
ERZ1026908                                                                           0.0

            mitotic cell cycle  alanine dehydrogenase activity  \
ERZ1026774                 0.0                             3.0
ERZ1026777                 0.0                             3.0
ERZ1026906                 0.0                             2.0
ERZ1026907                 0.0                             1.0
ERZ1026908                 0.0                             0.0

            magnesium ion binding  \
ERZ1026774                  345.0
ERZ1026777                  380.0
ERZ1026906                  152.0
ERZ1026907                  145.0
ERZ1026908                    5.0

            deadenylation-dependent decapping of nuclear-transcribed mRNA  \
ERZ1026774                                                            0.0
ERZ1026777                                                            0.0
ERZ1026906                                                            0.0
ERZ1026907                                                            0.0
ERZ1026908                                                            0.0

            response to reactive oxygen species  \
ERZ1026774                                  3.0
ERZ1026777                                  2.0
ERZ1026906                                  3.0
ERZ1026907                                  0.0
ERZ1026908                                  0.0

            nicotinamide-nucleotide adenylyltransferase activity  \
ERZ1026774                                                   1.0
ERZ1026777                                                   0.0
ERZ1026906                                                   0.0
ERZ1026907                                                   0.0
ERZ1026908                                                   0.0

            3-hydroxyanthranilate 3@4-dioxygenase activity  \
ERZ1026774                                             1.0
ERZ1026777                                             0.0
ERZ1026906                                             0.0
ERZ1026907                                             0.0
ERZ1026908                                             0.0

            RNA 7-methylguanosine cap binding  \
ERZ1026774                                0.0
ERZ1026777                                0.0
ERZ1026906                                0.0
ERZ1026907                                0.0
ERZ1026908                                0.0

            generation of catalytic spliceosome for second transesterification step  \
ERZ1026774                                                                      0.0
ERZ1026777                                                                      0.0
ERZ1026906                                                                      0.0
ERZ1026907                                                                      0.0
ERZ1026908                                                                      0.0

            Group I intron splicing  mRNA splicing@ via spliceosome  \
ERZ1026774                      0.0                             0.0
ERZ1026777                      0.0                             0.0
ERZ1026906                      0.0                             0.0
ERZ1026907                      0.0                             0.0
ERZ1026908                      0.0                             0.0

            EKC/KEOPS complex  protein peptidyl-prolyl isomerization  \
ERZ1026774                0.0                                   45.0
ERZ1026777                0.0                                   48.0
ERZ1026906                0.0                                   16.0
ERZ1026907                0.0                                   20.0
ERZ1026908                0.0                                    0.0

            core TFIIH complex  \
ERZ1026774                 0.0
ERZ1026777                 0.0
ERZ1026906                 0.0
ERZ1026907                 0.0
ERZ1026908                 0.0

            THO complex part of transcription export complex  \
ERZ1026774                                               0.0
ERZ1026777                                               0.0
ERZ1026906                                               0.0
ERZ1026907                                               0.0
ERZ1026908                                               0.0

            maturation of SSU-rRNA from tricistronic rRNA transcript (SSU-rRNA@ 5.8S rRNA@ LSU-rRNA)  \
ERZ1026774                                                                                       0.0
ERZ1026777                                                                                       0.0
ERZ1026906                                                                                       0.0
ERZ1026907                                                                                       0.0
ERZ1026908                                                                                       0.0

            cleavage involved in rRNA processing  proteasome complex  \
ERZ1026774                                   0.0                 0.0
ERZ1026777                                   0.0                 0.0
ERZ1026906                                   0.0                 0.0
ERZ1026907                                   0.0                 0.0
ERZ1026908                                   0.0                 0.0

            telomere maintenance  \
ERZ1026774                   6.0
ERZ1026777                  13.0
ERZ1026906                   9.0
ERZ1026907                   3.0
ERZ1026908                   0.0

            double-strand break repair via homologous recombination  \
ERZ1026774                                                      0.0
ERZ1026777                                                      1.0
ERZ1026906                                                      0.0
ERZ1026907                                                      0.0
ERZ1026908                                                      0.0

            DNA catabolic process@ endonucleolytic  conjugation  \
ERZ1026774                                     1.0          7.0
ERZ1026777                                     0.0          0.0
ERZ1026906                                     0.0          0.0
ERZ1026907                                     0.0          0.0
ERZ1026908                                     0.0          0.0

            pheromone-dependent signal transduction involved in conjugation with cellular fusion  \
ERZ1026774                                                                                   0.0
ERZ1026777                                                                                   0.0
ERZ1026906                                                                                   0.0
ERZ1026907                                                                                   0.0
ERZ1026908                                                                                   0.0

            mating pheromone activity  \
ERZ1026774                        0.0
ERZ1026777                        0.0
ERZ1026906                        0.0
ERZ1026907                        0.0
ERZ1026908                        0.0

            adenyl-nucleotide exchange factor activity  \
ERZ1026774                                        30.0
ERZ1026777                                        29.0
ERZ1026906                                         8.0
ERZ1026907                                        13.0
ERZ1026908                                         7.0

            chromosome@ centromeric region  kinetochore  chromatin  \
ERZ1026774                             0.0          1.0        0.0
ERZ1026777                             0.0          1.0        0.0
ERZ1026906                             0.0          0.0        0.0
ERZ1026907                             0.0          0.0        0.0
ERZ1026908                             0.0          0.0        0.0

            nucleosome  synaptonemal complex  condensin complex  \
ERZ1026774         0.0                   0.0                0.0
ERZ1026777         1.0                   0.0                0.0
ERZ1026906         0.0                   0.0                0.0
ERZ1026907         0.0                   0.0                0.0
ERZ1026908         0.0                   0.0                0.0

            origin recognition complex  ESCRT I complex  cell morphogenesis  \
ERZ1026774                         0.0              0.0                56.0
ERZ1026777                         0.0              0.0                61.0

2740
2217
1273
2217
1273
1467
{'ERZ653470', 'ERZ652847', 'ERZ1027264', 'ERZ1027100', 'ERZ654254', 'ERZ653308', 'ERZ653680', 'ERZ1027235', 'ERZ654443', 'ERZ653361', 'ERZ653825', 'ERZ653194', 'ERZ653250', 'ERZ1026963', 'ERZ1026990', 'ERZ652722', 'ERZ654270', 'ERZ654381', 'ERZ653640', 'ERZ653322', 'ERZ652794', 'ERZ654919', 'ERZ652859', 'ERZ653714', 'ERZ654252', 'ERZ653599', 'ERZ654290', 'ERZ1026952', 'ERZ1027041', 'ERZ652823', 'ERZ654367', 'ERZ652956', 'ERZ653784', 'ERZ1027255', 'ERZ654174', 'ERZ1026970', 'ERZ653326', 'ERZ654287', 'ERZ653125', 'ERZ654226', 'ERZ654120', 'ERZ653617', 'ERZ653720', 'ERZ653817', 'ERZ654238', 'ERZ653425', 'ERZ654355', 'ERZ1027204', 'ERZ653835', 'ERZ1027242', 'ERZ1027145', 'ERZ654298', 'ERZ654202', 'ERZ1026948', 'ERZ653611', 'ERZ653663', 'ERZ654058', 'ERZ653986', 'ERZ653822', 'ERZ1027197', 'ERZ653709', 'ERZ1027192', 'ERZ653213', 'ERZ653780', 'ERZ652792', 'ERZ1027243', 'ERZ653600', 'ERZ652736', 'ERZ1027129', 'ERZ653607', 'ERZ652748', 'ERZ1027224', 'ERZ653637', 'ERZ1026938', 'ERZ653251', 'ERZ654451', 'ERZ653684', 'ERZ654306', 'ERZ654154', 'ERZ1027247', 'ERZ653849', 'ERZ653151', 'ERZ653592', 'ERZ653741', 'ERZ652835', 'ERZ653838', 'ERZ653456', 'ERZ653585', 'ERZ654269', 'ERZ1027194', 'ERZ1026925', 'ERZ652741', 'ERZ653092', 'ERZ652728', 'ERZ654302', 'ERZ654170', 'ERZ653498', 'ERZ654180', 'ERZ653099', 'ERZ653578', 'ERZ652872', 'ERZ653074', 'ERZ1027253', 'ERZ653379', 'ERZ654493', 'ERZ654349', 'ERZ1027223', 'ERZ1027103', 'ERZ1027283', 'ERZ653119', 'ERZ654030', 'ERZ652726', 'ERZ652851', 'ERZ653114', 'ERZ654417', 'ERZ653577', 'ERZ653988', 'ERZ654220', 'ERZ1026939', 'ERZ653165', 'ERZ654084', 'ERZ1026959', 'ERZ1027238', 'ERZ653328', 'ERZ654212', 'ERZ1027049', 'ERZ1027142', 'ERZ1026993', 'ERZ653354', 'ERZ1027066', 'ERZ654347', 'ERZ653302', 'ERZ654243', 'ERZ653404', 'ERZ652972', 'ERZ652712', 'ERZ652783', 'ERZ653883', 'ERZ653704', 'ERZ652949', 'ERZ653184', 'ERZ653069', 'ERZ653572', 'ERZ653641', 'ERZ653120', 'ERZ653237', 'ERZ653214', 'ERZ653642', 'ERZ653841', 'ERZ1027258', 'ERZ653574', 'ERZ1027052', 'ERZ652788', 'ERZ653703', 'ERZ653731', 'ERZ1027275', 'ERZ653204', 'ERZ653927', 'ERZ654469', 'ERZ652839', 'ERZ653678', 'ERZ653885', 'ERZ653834', 'ERZ653807', 'ERZ654062', 'ERZ653972', 'ERZ653392', 'ERZ653382', 'ERZ653550', 'ERZ653667', 'ERZ653208', 'ERZ653581', 'ERZ653472', 'ERZ653371', 'ERZ653639', 'ERZ654331', 'ERZ653685', 'ERZ653996', 'ERZ653464', 'ERZ653209', 'ERZ653808', 'ERZ1026982', 'ERZ653112', 'ERZ654114', 'ERZ1027086', 'ERZ652782', 'ERZ653633', 'ERZ1027230', 'ERZ653421', 'ERZ653823', 'ERZ652829', 'ERZ653410', 'ERZ1026923', 'ERZ653593', 'ERZ654890', 'ERZ653113', 'ERZ653661', 'ERZ654441', 'ERZ652706', 'ERZ653306', 'ERZ653320', 'ERZ1026981', 'ERZ653496', 'ERZ653422', 'ERZ653974', 'ERZ652758', 'ERZ653580', 'ERZ654214', 'ERZ654068', 'ERZ652771', 'ERZ653829', 'ERZ1027042', 'ERZ1027171', 'ERZ1026935', 'ERZ654308', 'ERZ653245', 'ERZ653542', 'ERZ1027070', 'ERZ1027257', 'ERZ1026929', 'ERZ652716', 'ERZ654046', 'ERZ1027163', 'ERZ653624', 'ERZ652791', 'ERZ652982', 'ERZ653397', 'ERZ652948', 'ERZ654280', 'ERZ653643', 'ERZ653238', 'ERZ653084', 'ERZ653652', 'ERZ653984', 'ERZ654483', 'ERZ1027043', 'ERZ653167', 'ERZ653800', 'ERZ653129', 'ERZ653804', 'ERZ1026997', 'ERZ653442', 'ERZ653718', 'ERZ653355', 'ERZ653739', 'ERZ654064', 'ERZ654261', 'ERZ653921', 'ERZ653619', 'ERZ653163', 'ERZ653373', 'ERZ1027065', 'ERZ653675', 'ERZ653095', 'ERZ653846', 'ERZ1027124', 'ERZ1027051', 'ERZ653448', 'ERZ1027183', 'ERZ654232', 'ERZ1027060', 'ERZ1027219', 'ERZ653575', 'ERZ653284', 'ERZ1026961', 'ERZ652765', 'ERZ1027261', 'ERZ654036', 'ERZ1027218', 'ERZ653160', 'ERZ653638', 'ERZ653082', 'ERZ653085', 'ERZ653760', 'ERZ654018', 'ERZ1027201', 'ERZ653610', 'ERZ652803', 'ERZ653243', 'ERZ1027040', 'ERZ653565', 'ERZ1026906', 'ERZ653560', 'ERZ654048', 'ERZ653812', 'ERZ1027095', 'ERZ654050', 'ERZ653225', 'ERZ652738', 'ERZ654140', 'ERZ653395', 'ERZ653919', 'ERZ654489', 'ERZ654078', 'ERZ654112', 'ERZ654108', 'ERZ653446', 'ERZ1026918', 'ERZ653754', 'ERZ654166', 'ERZ654242', 'ERZ653768', 'ERZ1026977', 'ERZ1027237', 'ERZ653131', 'ERZ653594', 'ERZ652992', 'ERZ1027241', 'ERZ652966', 'ERZ1027099', 'ERZ653336', 'ERZ653630', 'ERZ653982', 'ERZ653721', 'ERZ1027069', 'ERZ653736', 'ERZ652753', 'ERZ1027198', 'ERZ1027047', 'ERZ1027205', 'ERZ653356', 'ERZ654216', 'ERZ654879', 'ERZ654330', 'ERZ653790', 'ERZ653191', 'ERZ653274', 'ERZ654160', 'ERZ653770', 'ERZ652768', 'ERZ1026976', 'ERZ653669', 'ERZ654296', 'ERZ1027263', 'ERZ1026962', 'ERZ653723', 'ERZ654188', 'ERZ653647', 'ERZ653646', 'ERZ654413', 'ERZ653175', 'ERZ654907', 'ERZ1027206', 'ERZ1027213', 'ERZ653831', 'ERZ653626', 'ERZ653155', 'ERZ654361', 'ERZ1027175', 'ERZ654126', 'ERZ1026967', 'ERZ1027209', 'ERZ653375', 'ERZ654479', 'ERZ653232', 'ERZ653197', 'ERZ653266', 'ERZ653842', 'ERZ1027076', 'ERZ1026989', 'ERZ654074', 'ERZ654152', 'ERZ652821', 'ERZ653881', 'ERZ653236', 'ERZ653844', 'ERZ1027034', 'ERZ1027236', 'ERZ654461', 'ERZ653424', 'ERZ653221', 'ERZ1027005', 'ERZ1027125', 'ERZ653782', 'ERZ654245', 'ERZ653358', 'ERZ653075', 'ERZ1027087', 'ERZ654892', 'ERZ654894', 'ERZ653415', 'ERZ1027144', 'ERZ653682', 'ERZ654491', 'ERZ1027137', 'ERZ653132', 'ERZ1027215', 'ERZ653372', 'ERZ654895', 'ERZ1027148', 'ERZ653814', 'ERZ653992', 'ERZ1027269', 'ERZ653486', 'ERZ652978', 'ERZ652974', 'ERZ653380', 'ERZ654132', 'ERZ653228', 'ERZ653401', 'ERZ653154', 'ERZ653627', 'ERZ1027108', 'ERZ653821', 'ERZ1026936', 'ERZ654128', 'ERZ1026964', 'ERZ653466', 'ERZ653805', 'ERZ653623', 'ERZ653146', 'ERZ1026994', 'ERZ654447', 'ERZ653366', 'ERZ1027279', 'ERZ652990', 'ERZ653727', 'ERZ653179', 'ERZ653747', 'ERZ653871', 'ERZ1027000', 'ERZ653500', 'ERZ653710', 'ERZ653189', 'ERZ1026943', 'ERZ653757', 'ERZ653670', 'ERZ653674', 'ERZ653388', 'ERZ1027259', 'ERZ653128', 'ERZ652731', 'ERZ654086', 'ERZ653917', 'ERZ653915', 'ERZ653115', 'ERZ652704', 'ERZ654156', 'ERZ654387', 'ERZ653591', 'ERZ654582', 'ERZ653773', 'ERZ654312', 'ERZ652780', 'ERZ653474', 'ERZ1027057', 'ERZ653405', 'ERZ1027055', 'ERZ654289', 'ERZ654315', 'ERZ653724', 'ERZ652865', 'ERZ653462', 'ERZ1026944', 'ERZ653259', 'ERZ1027064', 'ERZ1027245', 'ERZ654208', 'ERZ1027147', 'ERZ653879', 'ERZ654885', 'ERZ653083', 'ERZ653705', 'ERZ1026958', 'ERZ653324', 'ERZ1027167', 'ERZ653185', 'ERZ1027112', 'ERZ653217', 'ERZ653556', 'ERZ654337', 'ERZ653362', 'ERZ653691', 'ERZ653141', 'ERZ653411', 'ERZ653660', 'ERZ653625', 'ERZ652743', 'ERZ654088', 'ERZ652809', 'ERZ653252', 'ERZ653103', 'ERZ1027009', 'ERZ654006', 'ERZ654409', 'ERZ653233', 'ERZ653687', 'ERZ653093', 'ERZ652950', 'ERZ653396', 'ERZ1027202', 'ERZ654206', 'ERZ1027077', 'ERZ1027216', 'ERZ654284', 'ERZ1026978', 'ERZ653253', 'ERZ654449', 'ERZ653187', 'ERZ1027068', 'ERZ652735', 'ERZ652772', 'ERZ1026953', 'ERZ653897', 'ERZ1027039', 'ERZ1026928', 'ERZ653722', 'ERZ653676', 'ERZ653278', 'ERZ653282', 'ERZ653091', 'ERZ652737', 'ERZ654427', 'ERZ1027134', 'ERZ653226', 'ERZ653690', 'ERZ654275', 'ERZ653231', 'ERZ653108', 'ERZ653683', 'ERZ652962', 'ERZ1027128', 'ERZ653595', 'ERZ654459', 'ERZ652988', 'ERZ653368', 'ERZ654178', 'ERZ654435', 'ERZ653130', 'ERZ654425', 'ERZ653925', 'ERZ654343', 'ERZ1027139', 'ERZ653650', 'ERZ653681', 'ERZ652762', 'ERZ1026913', 'ERZ654251', 'ERZ1026966', 'ERZ1027109', 'ERZ654397', 'ERZ653648', 'ERZ653239', 'ERZ654910', 'ERZ652813', 'ERZ654244', 'ERZ1027133', 'ERZ1027132', 'ERZ654256', 'ERZ652784', 'ERZ652720', 'ERZ1027036', 'ERZ654379', 'ERZ652958', 'ERZ1027154', 'ERZ653837', 'ERZ653711', 'ERZ653998', 'ERZ653391', 'ERZ1027189', 'ERZ653383', 'ERZ1027117', 'ERZ653094', 'ERZ653820', 'ERZ652779', 'ERZ653270', 'ERZ652811', 'ERZ1027228', 'ERZ652869', 'ERZ653744', 'ERZ653699', 'ERZ653753', 'ERZ653402', 'ERZ653614', 'ERZ654385', 'ERZ653394', 'ERZ653137', 'ERZ1027282', 'ERZ652819', 'ERZ653719', 'ERZ654904', 'ERZ654124', 'ERZ654106', 'ERZ653730', 'ERZ653671', 'ERZ652954', 'ERZ653686', 'ERZ654250', 'ERZ653426', 'ERZ653385', 'ERZ653828', 'ERZ1027190', 'ERZ652787', 'ERZ653867', 'ERZ1027221', 'ERZ654146', 'ERZ653264', 'ERZ653334', 'ERZ1027111', 'ERZ1027168', 'ERZ652776', 'ERZ653211', 'ERZ653899', 'ERZ653292', 'ERZ1027003', 'ERZ1027229', 'ERZ1027195', 'ERZ653584', 'ERZ654439', 'ERZ653873', 'ERZ1027177', 'ERZ1027093', 'ERZ652817', 'ERZ654467', 'ERZ653571', 'ERZ1026957', 'ERZ653158', 'ERZ653207', 'ERZ652790', 'ERZ653086', 'ERZ654377', 'ERZ1027251', 'ERZ653700', 'ERZ653149', 'ERZ653665', 'ERZ653588', 'ERZ652952', 'ERZ653589', 'ERZ653161', 'ERZ1027214', 'ERZ653597', 'ERZ653598', 'ERZ653558', 'ERZ653857', 'ERZ653359', 'ERZ1026979', 'ERZ653242', 'ERZ653390', 'ERZ653608', 'ERZ653827', 'ERZ1027004', 'ERZ653960', 'ERZ653826', 'ERZ653078', 'ERZ652764', 'ERZ654905', 'ERZ1026917', 'ERZ654176', 'ERZ653280', 'ERZ654253', 'ERZ653393', 'ERZ1027123', 'ERZ1027016', 'ERZ1026960', 'ERZ653389', 'ERZ652740', 'ERZ653484', 'ERZ653568', 'ERZ653695', 'ERZ654357', 'ERZ653962', 'ERZ654887', 'ERZ653164', 'ERZ653256', 'ERZ653605', 'ERZ653412', 'ERZ653240', 'ERZ653263', 'ERZ654304', 'ERZ652796', 'ERZ653288', 'ERZ654083', 'ERZ654144', 'ERZ654044', 'ERZ653143', 'ERZ1027071', 'ERZ1027013', 'ERZ653576', 'ERZ654026', 'ERZ1027227', 'ERZ653792', 'ERZ654301', 'ERZ653180', 'ERZ653889', 'ERZ1027217', 'ERZ653654', 'ERZ653088', 'ERZ654230', 'ERZ653729', 'ERZ653745', 'ERZ653776', 'ERZ653159', 'ERZ654411', 'ERZ652761', 'ERZ654004', 'ERZ654204', 'ERZ1027199', 'ERZ1026777', 'ERZ653087', 'ERZ653153', 'ERZ653418', 'ERZ1027015', 'ERZ653378', 'ERZ652710', 'ERZ653174', 'ERZ1026946', 'ERZ1027046', 'ERZ1027249', 'ERZ653803', 'ERZ1027106', 'ERZ653662', 'ERZ1026919', 'ERZ1027010', 'ERZ653726', 'ERZ653178', 'ERZ653634', 'ERZ653254', 'ERZ653569', 'ERZ653369', 'ERZ653656', 'ERZ1027122', 'ERZ652785', 'ERZ654198', 'ERZ653407', 'ERZ653247', 'ERZ653562', 'ERZ654022', 'ERZ654052', 'ERZ653258', 'ERZ653668', 'ERZ653476', 'ERZ653716', 'ERZ653715', 'ERZ654190', 'ERZ653582', 'ERZ653836', 'ERZ654134', 'ERZ652767', 'ERZ654268', 'ERZ654299', 'ERZ1026945', 'ERZ1027270', 'ERZ653750', 'ERZ653601', 'ERZ653490', 'ERZ653733', 'ERZ652769', 'ERZ652786', 'ERZ654196', 'ERZ653077', 'ERZ1027116', 'ERZ654339', 'ERZ652845', 'ERZ1027184', 'ERZ1026915', 'ERZ1027044', 'ERZ654407', 'ERZ654283', 'ERZ652755', 'ERZ653468', 'ERZ653220', 'ERZ653612', 'ERZ1027146', 'ERZ653566', 'ERZ1027136', 'ERZ654210', 'ERZ652841', 'ERZ652730', 'ERZ652747', 'ERZ1027072', 'ERZ653748', 'ERZ653215', 'ERZ1027140', 'ERZ652871', 'ERZ653106', 'ERZ1027203', 'ERZ652733', 'ERZ654295', 'ERZ653570', 'ERZ654038', 'ERZ653272', 'ERZ653628', 'ERZ1027274', 'ERZ653201', 'ERZ653377', 'ERZ653330', 'ERZ654247', 'ERZ654359', 'ERZ653186', 'ERZ653755', 'ERZ653629', 'ERZ1026992', 'ERZ652795', 'ERZ654092', 'ERZ1027280', 'ERZ1027090', 'ERZ654457', 'ERZ1026975', 'ERZ653689', 'ERZ1026932', 'ERZ652729', 'ERZ652724', 'ERZ653367', 'ERZ1027011', 'ERZ654401', 'ERZ653819', 'ERZ653089', 'ERZ1027250', 'ERZ653903', 'ERZ652797', 'ERZ654164', 'ERZ653798', 'ERZ653905', 'ERZ653994', 'ERZ1026940', 'ERZ652775', 'ERZ653286', 'ERZ654909', 'ERZ653865', 'ERZ653198', 'ERZ653786', 'ERZ653818', 'ERZ653688', 'ERZ1027098', 'ERZ653734', 'ERZ653788', 'ERZ1026942', 'ERZ653318', 'ERZ653492', 'ERZ1026950', 'ERZ654082', 'ERZ1027252', 'ERZ654876', 'ERZ1026931', 'ERZ653618', 'ERZ654453', 'ERZ654264', 'ERZ1026968', 'ERZ654259', 'ERZ654200', 'ERZ654032', 'ERZ1026908', 'ERZ653181', 'ERZ653732', 'ERZ1027097', 'ERZ1027260', 'ERZ653692', 'ERZ1027268', 'ERZ652766', 'ERZ654335', 'ERZ1027222', 'ERZ654473', 'ERZ654265', 'ERZ1027006', 'ERZ652725', 'ERZ653824', 'ERZ653386', 'ERZ652777', 'ERZ653346', 'ERZ653100', 'ERZ653182', 'ERZ653419', 'ERZ654341', 'ERZ1027120', 'ERZ1027285', 'ERZ654294', 'ERZ654148', 'ERZ653172', 'ERZ652752', 'ERZ1026912', 'ERZ653234', 'ERZ654094', 'ERZ653478', 'ERZ1027045', 'ERZ652770', 'ERZ652855', 'ERZ1026774', 'ERZ653202', 'ERZ1027033', 'ERZ654066', 'ERZ1026973', 'ERZ1026941', 'ERZ1027181', 'ERZ1027118', 'ERZ653980', 'ERZ1027266', 'ERZ1026983', 'ERZ653546', 'ERZ653502', 'ERZ1026916', 'ERZ1027131', 'ERZ654271', 'ERZ1026927', 'ERZ652760', 'ERZ653488', 'ERZ654020', 'ERZ1027130', 'ERZ653246', 'ERZ653797', 'ERZ654282', 'ERZ653708', 'ERZ654369', 'ERZ653799', 'ERZ654300', 'ERZ654279', 'ERZ653968', 'ERZ653855', 'ERZ654276', 'ERZ653766', 'ERZ1027225', 'ERZ653698', 'ERZ1027053', 'ERZ653166', 'ERZ1027054', 'ERZ653693', 'ERZ1026911', 'ERZ653976', 'ERZ652815', 'ERZ653749', 'ERZ653657', 'ERZ653363', 'ERZ652825', 'ERZ1027063', 'ERZ653635', 'ERZ653152', 'ERZ1026947', 'ERZ654257', 'ERZ653212', 'ERZ1027096', 'ERZ1027265', 'ERZ654162', 'ERZ653877', 'ERZ653696', 'ERZ654158', 'ERZ653076', 'ERZ1027220', 'ERZ653124', 'ERZ653200', 'ERZ653360', 'ERZ653438', 'ERZ653887', 'ERZ653399', 'ERZ653195', 'ERZ652984', 'ERZ653417', 'ERZ653370', 'ERZ653398', 'ERZ1026937', 'ERZ653423', 'ERZ1027107', 'ERZ653196', 'ERZ653073', 'ERZ652793', 'ERZ654389', 'ERZ653832', 'ERZ654258', 'ERZ1027074', 'ERZ1027248', 'ERZ1027232', 'ERZ653171', 'ERZ653762', 'ERZ653205', 'ERZ653145', 'ERZ654893', 'ERZ653651', 'ERZ1027278', 'ERZ654234', 'ERZ653260', 'ERZ654054', 'ERZ653122', 'ERZ653702', 'ERZ654353', 'ERZ653978', 'ERZ653276', 'ERZ1027062', 'ERZ654285', 'ERZ653403', 'ERZ654100', 'ERZ653183', 'ERZ1027196', 'ERZ1027174', 'ERZ653162', 'ERZ653586', 'ERZ653636', 'ERZ1027246', 'ERZ653615', 'ERZ653909', 'ERZ653869', 'ERZ1027178', 'ERZ1027038', 'ERZ653907', 'ERZ1026984', 'ERZ1027256', 'ERZ653206', 'ERZ654080', 'ERZ652789', 'ERZ654901', 'ERZ653241', 'ERZ653406', 'ERZ652831', 'ERZ654309', 'ERZ1027114', 'ERZ1027254', 'ERZ653147', 'ERZ653409', 'ERZ653845', 'ERZ653170', 'ERZ1027001', 'ERZ654165', 'ERZ654224', 'ERZ653743', 'ERZ654138', 'ERZ653265', 'ERZ1026985', 'ERZ653454', 'ERZ653116', 'ERZ1027180', 'ERZ654240', 'ERZ653101', 'ERZ653740', 'ERZ652801', 'ERZ654313', 'ERZ653222', 'ERZ653632', 'ERZ653332', 'ERZ653067', 'ERZ1026907', 'ERZ653168', 'ERZ653072', 'ERZ654375', 'ERZ1026922', 'ERZ1027141', 'ERZ1027119', 'ERZ653756', 'ERZ653764', 'ERZ653833', 'ERZ1026954', 'ERZ653843', 'ERZ653620', 'ERZ653066', 'ERZ653127', 'ERZ653694', 'ERZ654122', 'ERZ653352', 'ERZ654365', 'ERZ652751', 'ERZ1027058', 'ERZ653616', 'ERZ653758', 'ERZ652970', 'ERZ653644', 'ERZ1026909', 'ERZ652718', 'ERZ654012', 'ERZ654136', 'ERZ653853', 'ERZ1027207', 'ERZ654056', 'ERZ1026995', 'ERZ1027138', 'ERZ1027179', 'ERZ653296', 'ERZ653602', 'ERZ1027101', 'ERZ653738', 'ERZ1027115', 'ERZ653604', 'ERZ653338', 'ERZ654241', 'ERZ653111', 'ERZ653596', 'ERZ654278', 'ERZ653148', 'ERZ653150', 'ERZ653859', 'ERZ653199', 'ERZ1027104', 'ERZ653713', 'ERZ654363', 'ERZ653548', 'ERZ653316', 'ERZ654316', 'ERZ654060', 'ERZ652749', 'ERZ653314', 'ERZ1027210', 'ERZ653579', 'ERZ1027182', 'ERZ653840', 'ERZ1026986', 'ERZ1027067', 'ERZ1027153', 'ERZ653701', 'ERZ653268', 'ERZ654485', 'ERZ654292', 'ERZ1027262', 'ERZ653830', 'ERZ653649', 'ERZ653413', 'ERZ654273', 'ERZ653223', 'ERZ654186', 'ERZ654291', 'ERZ653414', 'ERZ654896', 'ERZ654399', 'ERZ1026971', 'ERZ653735', 'ERZ654423', 'ERZ654218', 'ERZ654317', 'ERZ1027056', 'ERZ654305', 'ERZ1026930', 'ERZ653123', 'ERZ653298', 'ERZ653658', 'ERZ653342', 'ERZ653645', 'ERZ1026924', 'ERZ1027035', 'ERZ653188', 'ERZ652754', 'ERZ654774', 'ERZ653742', 'ERZ654116', 'ERZ653249', 'ERZ1027113', 'ERZ654437', 'ERZ653450', 'ERZ1027267', 'ERZ654262', 'ERZ653802', 'ERZ1027007', 'ERZ654010', 'ERZ654277', 'ERZ654333', 'ERZ653384', 'ERZ653861', 'ERZ654433', 'ERZ653219', 'ERZ653210', 'ERZ652739', 'ERZ653964', 'ERZ1027240', 'ERZ653923', 'ERZ1027191', 'ERZ1026949', 'ERZ654716', 'ERZ653679', 'ERZ654228', 'ERZ652778', 'ERZ654371', 'ERZ652960', 'ERZ654024', 'ERZ654303', 'ERZ654090', 'ERZ653590', 'ERZ1027078', 'ERZ653090', 'ERZ654881', 'ERZ653573', 'ERZ1027089', 'ERZ652986', 'ERZ653079', 'ERZ652857', 'ERZ653664', 'ERZ1027226', 'ERZ652773', 'ERZ653310', 'ERZ653966', 'ERZ653893', 'ERZ653133', 'ERZ653774', 'ERZ653169', 'ERZ654000', 'ERZ653121', 'ERZ1027157', 'ERZ1027092', 'ERZ654130', 'ERZ653655', 'ERZ653117', 'ERZ653126', 'ERZ654072', 'ERZ654070', 'ERZ653863', 'ERZ654494', 'ERZ653631', 'ERZ654102', 'ERZ653653', 'ERZ654495', 'ERZ653387', 'ERZ652756', 'ERZ653603', 'ERZ1026955', 'ERZ1027212', 'ERZ653839', 'ERZ1027037', 'ERZ1026969', 'ERZ653227', 'ERZ653230', 'ERZ1027176', 'ERZ1026956', 'ERZ652833', 'ERZ653794', 'ERZ653107', 'ERZ653139', 'ERZ653970', 'ERZ1027271', 'ERZ654351', 'ERZ1027032', 'ERZ653666', 'ERZ1027012', 'ERZ654281', 'ERZ653717', 'ERZ654040', 'ERZ653712', 'ERZ653815', 'ERZ654293', 'ERZ653706', 'ERZ654263', 'ERZ1027188', 'ERZ654658', 'ERZ653400', 'ERZ653929', 'ERZ652849', 'ERZ653452', 'ERZ654463', 'ERZ1027002', 'ERZ1026998', 'ERZ652807', 'ERZ653098', 'ERZ653990', 'ERZ654383', 'ERZ653357', 'ERZ653192', 'ERZ652863', 'ERZ653365', 'ERZ653364', 'ERZ654286', 'ERZ654882', 'ERZ1027008', 'ERZ653104', 'ERZ654016', 'ERZ653348', 'ERZ653851', 'ERZ654255', 'ERZ654314', 'ERZ652757', 'ERZ1026933', 'ERZ653376', 'ERZ653176', 'ERZ654310', 'ERZ653504', 'ERZ652708', 'ERZ654274', 'ERZ653203', 'ERZ653806', 'ERZ652980', 'ERZ653255', 'ERZ653248', 'ERZ654373', 'ERZ654455', 'ERZ654194', 'ERZ1027094', 'ERZ1027084', 'ERZ653751', 'ERZ654487', 'ERZ653218', 'ERZ654236', 'ERZ1027048', 'ERZ653420', 'ERZ653065', 'ERZ653609', 'ERZ654184', 'ERZ652750', 'ERZ654249', 'ERZ653480', 'ERZ653097', 'ERZ654267', 'ERZ652781', 'ERZ1026972', 'ERZ654098', 'ERZ653261', 'ERZ1027193', 'ERZ652861', 'ERZ1027050', 'ERZ653312', 'ERZ653304', 'ERZ652843', 'ERZ653673', 'ERZ654903', 'ERZ1026921', 'ERZ654182', 'ERZ1027149', 'ERZ653081', 'ERZ1027135', 'ERZ653244', 'ERZ653290', 'ERZ654481', 'ERZ1026951', 'ERZ652759', 'ERZ653262', 'ERZ652853', 'ERZ653801', 'ERZ653707', 'ERZ653157', 'ERZ653068', 'ERZ654900', 'ERZ654600', 'ERZ653737', 'ERZ1026920', 'ERZ653752', 'ERZ653728', 'ERZ653482', 'ERZ653350', 'ERZ1027233', 'ERZ654471', 'ERZ654345', 'ERZ654118', 'ERZ653895', 'ERZ653891', 'ERZ653659', 'ERZ652994', 'ERZ652774', 'ERZ1026914', 'ERZ653381', 'ERZ654477', 'ERZ653677', 'ERZ653583', 'ERZ654142', 'ERZ653294', 'ERZ652714', 'ERZ1027127', 'ERZ652867', 'ERZ653416', 'ERZ654391', 'ERZ1027272', 'ERZ652723', 'ERZ652837', 'ERZ653177', 'ERZ654393', 'ERZ653810', 'ERZ654192', 'ERZ1026965', 'ERZ654150', 'ERZ654260', 'ERZ653374', 'ERZ653809', 'ERZ652964', 'ERZ653096', 'ERZ1027059', 'ERZ1027102', 'ERZ1026934', 'ERZ653725', 'ERZ1027014', 'ERZ654104', 'ERZ653235', 'ERZ654008', 'ERZ1026999', 'ERZ1026988', 'ERZ653216', 'ERZ1026974', 'ERZ652734', 'ERZ653109', 'ERZ654429', 'ERZ653460', 'ERZ653875', 'ERZ653156', 'ERZ652745', 'ERZ1027085', 'ERZ654415', 'ERZ1027273', 'ERZ652805', 'ERZ653229', 'ERZ653257', 'ERZ653901', 'ERZ654028', 'ERZ653778', 'ERZ653444', 'ERZ653173', 'ERZ654886', 'ERZ653118', 'ERZ654042', 'ERZ654002', 'ERZ1027244', 'ERZ653911', 'ERZ1027239', 'ERZ1027160', 'ERZ653621', 'ERZ654168', 'ERZ654906', 'ERZ652742', 'ERZ652763', 'ERZ1027276', 'ERZ653587', 'ERZ653672', 'ERZ653102', 'ERZ653494', 'ERZ653913', 'ERZ653606', 'ERZ654222', 'ERZ654891', 'ERZ653408', 'ERZ1027110', 'ERZ1027150', 'ERZ653746', 'ERZ653813', 'ERZ654110', 'ERZ653958', 'ERZ653110', 'ERZ1027061', 'ERZ654445', 'ERZ1027105', 'ERZ654902', 'ERZ653567', 'ERZ653105', 'ERZ1026980', 'ERZ652799', 'ERZ653193', 'ERZ1026996', 'ERZ1027284', 'ERZ652976', 'ERZ653440', 'ERZ653224', 'ERZ653622', 'ERZ654421', 'ERZ654403', 'ERZ652968', 'ERZ654266', 'ERZ652827', 'ERZ653956', 'ERZ654034', 'ERZ652746', 'ERZ653300', 'ERZ653697', 'ERZ654920', 'ERZ653544', 'ERZ654076', 'ERZ653554', 'ERZ654288', 'ERZ654272', 'ERZ1027186', 'ERZ652744', 'ERZ1027277', 'ERZ653796', 'ERZ653340', 'ERZ653613', 'ERZ653190', 'ERZ1026926', 'ERZ653071', 'ERZ654297', 'ERZ652732', 'ERZ652727', 'ERZ654899', 'ERZ1027126', 'ERZ1027121', 'ERZ654172', 'ERZ654311', 'ERZ1027200', 'ERZ653816', 'ERZ654318', 'ERZ653811', 'ERZ653070', 'ERZ654405', 'ERZ654096'}

In [19]:
print("SRS1914207" in assembly_id_to_sample_id.values())
print("ERZ654086" in assembly_id_to_sample_id.keys())
print("ERZ653429" in assembly_id_to_sample_id.keys())

True
False
True

#### analyze table of metadata from the following paper: 
https://www.cell.com/cell-host-microbe/fulltext/S1931-3128(18)30493-1?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1931312818304931%3Fshowall%3Dtrue

In [110]:
%pip install openpyxl
import pandas as pd

metadata = pd.read_excel("mmc7.xlsx", skiprows=2)

Requirement already satisfied: openpyxl in c:\users\shaya\documents\tu_projects\master_thesis\.thesis_venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\shaya\documents\tu_projects\master_thesis\.thesis_venv\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.
Index(['GID', 'SubjectID', 'sampleType', 'collectionWeek', 'age', 'gender',
       'race', 'INITIAL_TRT_C4', 'antibiotics', 'antibiotics_time_to',
       'antibiotics_type', 'COLECTOMY_WK52', 'TWEEK_COLECTOMY_WK52',
       'REMISSION_WK4', 'CSFREE_REMISSION_WK12', 'CSFREE_REMISSION_WK52',
       'PUCAI_C4_WKall', 'CALPROTECTIN_WKall', 'IGA', 'IGG', 'SER_ANCA',
       'SER_CBIR1', 'SER_OMPC', 'MONTREAL_ORD',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Ruminococcaceae..g__Oscillospira..s__..OTU_310886',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Peptostreptococcaceae..g__..s__..OTU_531374',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__..g__..s__..OTU_366584',
       'k__Bacteria..p__Proteobacteria..c__Betaproteobacteria..o__Burkholderiales..f__Alcaligenaceae..g__Sutterella..s__..OTU_173726',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Ruminococcaceae..g__..s__..OTU_366794',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Lachnospiraceae..g__..s__..OTU_975306'],
      dtype='object')

In [113]:
print(metadata.columns[:30])
print(metadata["SubjectID"].nunique())
print(len(metadata))

Index(['GID', 'SubjectID', 'sampleType', 'collectionWeek', 'age', 'gender',
       'race', 'INITIAL_TRT_C4', 'antibiotics', 'antibiotics_time_to',
       'antibiotics_type', 'COLECTOMY_WK52', 'TWEEK_COLECTOMY_WK52',
       'REMISSION_WK4', 'CSFREE_REMISSION_WK12', 'CSFREE_REMISSION_WK52',
       'PUCAI_C4_WKall', 'CALPROTECTIN_WKall', 'IGA', 'IGG', 'SER_ANCA',
       'SER_CBIR1', 'SER_OMPC', 'MONTREAL_ORD',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Ruminococcaceae..g__Oscillospira..s__..OTU_310886',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Peptostreptococcaceae..g__..s__..OTU_531374',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__..g__..s__..OTU_366584',
       'k__Bacteria..p__Proteobacteria..c__Betaproteobacteria..o__Burkholderiales..f__Alcaligenaceae..g__Sutterella..s__..OTU_173726',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Ruminococcaceae..g__..s__..OTU_366794',
       'k__Bacteria..p__Firmicutes..c__Clostridia..o__Clostridiales..f__Lachnospiraceae..g__..s__..OTU_975306'],
      dtype='object')
405
1212

#### Checking out whether longitudinal studies have same sampleID for same sample throughout time or not

In [ ]:
# get metadata of studies with longitudinal in title
from requests import Session as requests_session
import json

from src.global_vars import HTTP_ADAPTER_FOR_REQUESTS

# study_accessions = set()

# with requests_session() as session:
#     url = f"https://www.ebi.ac.uk/metagenomics/api/latest/studies?fields[studies]=study_name,samples_count,biomes,id&page_size=250&page=1"
#     session.mount("http://", HTTP_ADAPTER_FOR_REQUESTS)
#     session.mount("https://", HTTP_ADAPTER_FOR_REQUESTS)

#     while url:
#         response = session.get(url, timeout=30).json()
#         studies = response.get("data", [])
#         for study in studies:
#             if "longitudinal" in study["attributes"]["study-name"].lower() and study["attributes"]["samples-count"] > 100:
#                 biome = study["relationships"]["biomes"]["data"][0]["id"]
#                 study_accessions.add(study["id"])
#         print(f"Processed page {url.split("&page=")[1]}")
#         url = response.get("links", {}).get("next")

with open("study_accessions_with_longitudinal_in_title.json", "w") as f:
    json.dump(list(study_accessions), f)

In [ ]:
import json
import pandas as pd
import sys


sys.path.append("../")

%load_ext autoreload
%autoreload 2
import src.mgnify_helper_functions as mhf

mgnify = mhf.MGnifyData(cache_folder="./")

with open("study_accessions_with_longitudinal_in_title.json") as f:
    study_accessions = json.load(f)

mgnify.download_metadata_for_studies(study_accessions)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2024-11-27 13:34:42.401 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 278 samples in study MGYS00002357.
2024-11-27 13:37:13.506 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 764 samples in study MGYS00003619.
2024-11-27 13:37:34.645 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 176 samples in study MGYS00006120.
2024-11-27 13:37:55.022 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 158 samples in study MGYS00001212.
2024-11-27 13:40:12.355 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 744 samples in study MGYS00005340.
2024-11-27 13:41:40.238 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 751 samples in study MGYS00006273.
2024-11-27 13:42:15.836 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 287 samples in study MGYS00001068.
2024-11-27 13:42:40.160 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 124 samples in study MGYS00005378.
2024-11-27 13:43:04.789 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 124 samples in study MGYS00005377.
2024-11-27 13:46:56.596 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 1625 samples in study MGYS00003659.
2024-11-27 13:48:54.031 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 850 samples in study MGYS00005505.
2024-11-27 13:50:01.656 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 510 samples in study MGYS00005525.
2024-11-27 13:50:49.283 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 258 samples in study MGYS00002072.
2024-11-27 13:51:04.627 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 118 samples in study MGYS00006469.
2024-11-27 13:51:33.854 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 204 samples in study MGYS00006258.
2024-11-27 13:52:01.524 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 200 samples in study MGYS00005791.
2024-11-27 13:52:39.382 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 297 samples in study MGYS00006285.
2024-11-27 13:53:05.523 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 199 samples in study MGYS00005792.
2024-11-27 13:53:39.705 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 251 samples in study MGYS00005610.
2024-11-27 13:53:54.377 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:452 - Found metadata for 120 samples in study MGYS00005090.

In [ ]:
with open(f"../data/mgnify_data/{study}__metadata.json") as f:
    metadata = json.load(f)

metadata = metadata["metadata"]
metadata = pd.DataFrame(metadata)
display(metadata.head())
print(metadata.index)

mgnify = mhf.MGnifyData(cache_folder="../data/mgnify_data")
run_id_to_sample_id = mgnify.get_run_id_to_sample_id_dict(study)

column_mapper = {}
for key, value in run_id_to_sample_id.items():
    if value not in column_mapper:
        column_mapper[value] = []
    column_mapper[value].append(key)

new_columns = {new_name: metadata[old_name] for old_name, new_names in column_mapper.items() for new_name in new_names}
metadata = metadata.drop(columns=list(column_mapper.keys()))
metadata = metadata.join(pd.DataFrame(new_columns))
metadata = metadata.dropna(axis=1, how="all")
metadata = metadata.T
display(metadata.head())

In [ ]:
print(len(metadata))
metadata_ids = metadata[["sample_id"]]
metadata_ids.value_counts()[metadata_ids.value_counts() > 1]

metadata_id_with_date = metadata[["sample_id", "biosample_id", "collection date", "collection date__biosamples", "month__biosamples", "subject__biosamples", "host taxid"]]
print("Number of missing values")
display((metadata_id_with_date.isna()).sum())

print("Unique values and value counts")
for col in metadata_id_with_date.columns:
    print(f"**{col}**:\n{metadata_id_with_date[col].nunique()}")
    print(metadata_id_with_date[col].value_counts(dropna=False))

200
Number of missing values

sample_id                      0
biosample_id                   0
collection date                0
collection date__biosamples    0
month__biosamples              0
subject__biosamples            0
host taxid                     0
dtype: int64

Unique values and value counts
**sample_id**:
200
sample_id
SRS2255246    1
SRS2255134    1
SRS2255208    1
SRS2255091    1
SRS2255258    1
             ..
SRS2255106    1
SRS2255197    1
SRS2256116    1
SRS2256085    1
SRS2256101    1
Name: count, Length: 200, dtype: int64
**biosample_id**:
200
biosample_id
SAMN07199872    1
SAMN07199907    1
SAMN07199953    1
SAMN07199834    1
SAMN07199956    1
               ..
SAMN07199979    1
SAMN07199855    1
SAMN07200393    1
SAMN07200376    1
SAMN07200349    1
Name: count, Length: 200, dtype: int64
**collection date**:
1
collection date
2013-01-01    200
Name: count, dtype: int64
**collection date__biosamples**:
1
collection date__biosamples
2013    200
Name: count, dtype: int64
**month__biosamples**:
12
month__biosamples
3     23
1     23
2     22
7     20
5     20
6     19
4     19
8     16
10    11
9     10
11     9
12     8
Name: count, dtype: int64
**subject__biosamples**:
32
subject__biosamples
p8646      12
p8600      11
p8775      10
p8582       9
p8649       9
p8748       9
SKST024     8
p8712       8
p8816       8
p8883       8
SKST023     7
p8808       7
p9223       7
p9220       6
SKST007     6
p8585       6
p9216       6
SKST010     6
SKST011     6
SKST012     6
SKST027     5
p8855       5
SKST025     5
p9061       5
SKST006     5
p9281       4
SKST032     4
p9193       3
SKST036     3
SKST014     3
SKST041     2
SKST037     1
Name: count, dtype: int64
**host taxid**:
1
host taxid
9606    200
Name: count, dtype: int64

# Scanning 250 largest studies to decide what to use for baseline models

In [ ]:
import sys
sys.path.append("../")

%load_ext autoreload
%autoreload 2

import src.mgnify_helper_functions as mhf

mgnify = mhf.MGnifyData(cache_folder="../data/250_largest_studies/")

study_sizes = mgnify.get_study_sample_sizes()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

Get only studies larger than 100 samples

In [2]:
studies_larger_than_100 = {study: size for study, size in study_sizes.items() if size > 100}
sorted_studies = sorted(studies_larger_than_100.items(), key=lambda x: x[1], reverse=True)
sorted_accessions = [study[0] for study in sorted_studies]

Get around 25 studies (largest ones) with desired download links

In [70]:

desired_studies = mgnify.get_download_links_for_studies(sorted_accessions[:250], "Taxonomic assignments SSU")

# while len(desired_studies) < 25:
#     for i in range(0, len(sorted_studies), 25):
#         study_download_links = mgnify.get_download_links_for_studies(sorted_accessions[i:i+25], "Complete GO")
#         desired_studies.update(study_download_links)

2024-11-29 11:10:17.420 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00004712.
2024-11-29 11:10:17.455 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00003194.
2024-11-29 11:10:17.807 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005138.
2024-11-29 11:10:17.816 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00005146.
2024-11-29 11:10:18.831 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001679.
2024-11-29 11:10:18.843 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005513.
2024-11-29 11:10:19.808 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005142.
2024-11-29 11:10:19.813 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006551.
2024-11-29 11:10:20.877 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005143.
2024-11-29 11:10:20.881 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00000604.
2024-11-29 11:10:20.886 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 10/250 unprocessed studies.
2024-11-29 11:10:21.900 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003708.
2024-11-29 11:10:21.901 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003937.
2024-11-29 11:10:22.824 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00002184.
2024-11-29 11:10:22.827 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005152.
2024-11-29 11:10:23.849 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005222.
2024-11-29 11:10:23.851 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005192.
2024-11-29 11:10:24.871 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00005240.
2024-11-29 11:10:24.872 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00000596.
2024-11-29 11:10:25.895 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00005147.
2024-11-29 11:10:25.897 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005200.
2024-11-29 11:10:25.901 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 20/250 unprocessed studies.
2024-11-29 11:10:26.804 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001107.
2024-11-29 11:10:26.810 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005500.
2024-11-29 11:10:27.840 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005199.
2024-11-29 11:10:27.841 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005612.
2024-11-29 11:10:28.803 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005228.
2024-11-29 11:10:28.853 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00000633.
2024-11-29 11:10:29.890 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005196.
2024-11-29 11:10:29.891 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003659.
2024-11-29 11:10:30.914 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00002355.
2024-11-29 11:10:30.915 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005191.
2024-11-29 11:10:30.916 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 30/250 unprocessed studies.
2024-11-29 11:10:31.833 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005190.
2024-11-29 11:10:31.834 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00001075.
2024-11-29 11:10:32.754 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005224.
2024-11-29 11:10:32.815 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00001070.
2024-11-29 11:10:33.881 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005172.
2024-11-29 11:10:33.882 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001306.
2024-11-29 11:10:34.818 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005162.
2024-11-29 11:10:34.824 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003677.
2024-11-29 11:10:35.931 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006638.
2024-11-29 11:10:35.932 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005184.
2024-11-29 11:10:35.936 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 40/250 unprocessed studies.
2024-11-29 11:10:36.851 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003733.
2024-11-29 11:10:36.852 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005170.
2024-11-29 11:10:37.879 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00000494.
2024-11-29 11:10:37.881 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00000505.
2024-11-29 11:10:38.904 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003962.
2024-11-29 11:10:38.904 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003505.
2024-11-29 11:10:39.926 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005181.
2024-11-29 11:10:39.924 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001357.
2024-11-29 11:10:40.946 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003481.
2024-11-29 11:10:40.947 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006069.
2024-11-29 11:10:40.949 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 50/250 unprocessed studies.
2024-11-29 11:10:41.871 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00002392.
2024-11-29 11:10:41.878 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005133.
2024-11-29 11:10:42.892 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001341.
2024-11-29 11:10:42.893 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00002363.
2024-11-29 11:10:43.840 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005173.
2024-11-29 11:10:43.882 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005195.
2024-11-29 11:10:44.839 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005197.
2024-11-29 11:10:44.910 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003811.
2024-11-29 11:10:45.863 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005225.
2024-11-29 11:10:45.911 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005202.
2024-11-29 11:10:45.914 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 60/250 unprocessed studies.
2024-11-29 11:10:46.888 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005507.
2024-11-29 11:10:46.891 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005128.
2024-11-29 11:10:47.912 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005227.
2024-11-29 11:10:47.915 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00003961.
2024-11-29 11:10:48.886 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00001368.
2024-11-29 11:10:48.886 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005156.
2024-11-29 11:10:49.959 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005230.
2024-11-29 11:10:49.960 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005523.
2024-11-29 11:10:50.879 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006446.
2024-11-29 11:10:50.950 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005242.
2024-11-29 11:10:50.951 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 70/250 unprocessed studies.
2024-11-29 11:10:51.846 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005188.
2024-11-29 11:10:51.847 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006034.
2024-11-29 11:10:52.928 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005514.
2024-11-29 11:10:52.929 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005259.
2024-11-29 11:10:53.938 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005314.
2024-11-29 11:10:53.942 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006389.
2024-11-29 11:10:54.875 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005237.
2024-11-29 11:10:54.879 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005503.
2024-11-29 11:10:55.898 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005158.
2024-11-29 11:10:55.927 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00001864.
2024-11-29 11:10:55.930 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 80/250 unprocessed studies.
2024-11-29 11:10:56.921 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005203.
2024-11-29 11:10:56.921 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005501.
2024-11-29 11:10:57.946 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005505.
2024-11-29 11:10:57.949 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005239.
2024-11-29 11:10:58.866 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00003715.
2024-11-29 11:10:58.901 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005498.
2024-11-29 11:10:59.891 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006491.
2024-11-29 11:10:59.904 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005504.
2024-11-29 11:11:00.916 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005232.
2024-11-29 11:11:00.919 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006345.
2024-11-29 11:11:00.931 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 90/250 unprocessed studies.
2024-11-29 11:11:01.941 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005205.
2024-11-29 11:11:01.943 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006028.
2024-11-29 11:11:02.963 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005150.
2024-11-29 11:11:02.964 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005217.
2024-11-29 11:11:03.926 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00005153.
2024-11-29 11:11:03.957 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00002360.
2024-11-29 11:11:04.902 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005512.
2024-11-29 11:11:04.908 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005850.
2024-11-29 11:11:05.934 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005198.
2024-11-29 11:11:05.936 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001748.
2024-11-29 11:11:05.948 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 100/250 unprocessed studies.
2024-11-29 11:11:06.956 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005231.
2024-11-29 11:11:06.976 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00003619.
2024-11-29 11:11:07.981 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00001278.
2024-11-29 11:11:07.982 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005223.
2024-11-29 11:11:08.932 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00005340.
2024-11-29 11:11:08.958 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005176.
2024-11-29 11:11:09.927 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006273.
2024-11-29 11:11:09.996 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005506.
2024-11-29 11:11:11.052 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005213.
2024-11-29 11:11:11.054 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005207.
2024-11-29 11:11:11.059 | INFO     | mgnify_helper_functions:get_download_links_for_studies:222 - Processed 110/250 unprocessed studies.
2024-11-29 11:11:11.976 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005316.
2024-11-29 11:11:12.012 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005241.
2024-11-29 11:11:12.918 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00004729.
2024-11-29 11:11:12.941 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001072.
2024-11-29 11:11:14.024 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00006477.
2024-11-29 11:11:14.025 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005208.
2024-11-29 11:11:15.010 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 1 download links for study MGYS00005206.
2024-11-29 11:11:15.039 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001809.
2024-11-29 11:11:15.968 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 0 download links for study MGYS00001645.
2024-11-29 11:11:15.997 | INFO     | mgnify_helper_functions:_get_download_urls_for_label_with_start:115 - Found 2 download links for study MGYS00005318.

In [15]:
# sorting desired studies by size
# desired_studies = {study: link for study, link in desired_studies.items() if link}
# desired_studies = list(sorted(desired_studies.keys(), key=lambda x: study_sizes[x], reverse=True))
print(desired_studies[25: 50])

['MGYS00005384', 'MGYS00003670', 'MGYS00006472', 'MGYS00003666', 'MGYS00002017', 'MGYS00006562', 'MGYS00006442', 'MGYS00005321', 'MGYS00000427', 'MGYS00005383', 'MGYS00006079', 'MGYS00005294', 'MGYS00005780', 'MGYS00002368', 'MGYS00006554', 'MGYS00005628', 'MGYS00005379', 'MGYS00006006']

In [ ]:
studies = ["MGYS00000604", "MGYS00003677", "MGYS00003733", "MGYS00003481", "MGYS00003619", "MGYS00001980"]

mgnify.download_metadata_for_studies(desired_studies[:25], n_samples=50)

2024-11-29 10:42:28.647 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00004712.
2024-11-29 10:42:35.135 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 500 samples in study MGYS00004712.
2024-11-29 10:42:35.205 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003194.
2024-11-29 10:42:42.529 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00003194.
2024-11-29 10:42:42.539 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003937.
2024-11-29 10:42:54.015 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00003937.
2024-11-29 10:42:54.022 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00000604.
2024-11-29 10:42:54.062 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 2758 samples in study MGYS00000604.
2024-11-29 10:42:54.147 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00006551.
2024-11-29 10:43:01.581 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00006551.
2024-11-29 10:43:01.593 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00000494.
2024-11-29 10:43:12.552 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00000494.
2024-11-29 10:43:12.564 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00000633.
2024-11-29 10:43:20.569 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00000633.
2024-11-29 10:43:20.574 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003962.
2024-11-29 10:43:28.243 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00003962.
2024-11-29 10:43:28.248 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003677.
2024-11-29 10:43:28.283 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 1388 samples in study MGYS00003677.
2024-11-29 10:43:28.328 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003733.
2024-11-29 10:43:28.342 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 1307 samples in study MGYS00003733.
2024-11-29 10:43:28.386 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00005128.
2024-11-29 10:43:35.292 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00005128.
2024-11-29 10:43:35.299 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003481.
2024-11-29 10:43:35.325 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 1155 samples in study MGYS00003481.
2024-11-29 10:43:35.383 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003961.
2024-11-29 10:43:46.266 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00003961.
2024-11-29 10:43:46.273 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00006069.
2024-11-29 10:44:18.877 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00006069.
2024-11-29 10:44:18.889 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003811.
2024-11-29 10:44:29.398 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00003811.
2024-11-29 10:44:29.408 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00006028.
2024-11-29 10:44:37.435 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00006028.
2024-11-29 10:44:37.444 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00006034.
2024-11-29 10:44:43.024 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00006034.
2024-11-29 10:44:43.035 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00001864.
2024-11-29 10:44:49.779 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00001864.
2024-11-29 10:44:49.784 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00006491.
2024-11-29 10:45:09.834 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00006491.
2024-11-29 10:45:09.841 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00001645.
2024-11-29 10:45:18.099 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00001645.
2024-11-29 10:45:18.109 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00001748.
2024-11-29 10:45:25.462 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00001748.
2024-11-29 10:45:25.473 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003619.
2024-11-29 10:45:25.501 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 764 samples in study MGYS00003619.
2024-11-29 10:45:25.530 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00005176.
2024-11-29 10:45:40.491 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00005176.
2024-11-29 10:45:40.500 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00001980.
2024-11-29 10:45:40.540 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 717 samples in study MGYS00001980.
2024-11-29 10:45:40.661 | INFO     | mgnify_helper_functions:download_metadata_for_studies:431 - Downloading metadata for study MGYS00003858.
2024-11-29 10:45:49.695 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00003858.

In [69]:
metadata = mgnify.get_metadata_for_study(desired_studies[10], n_samples=50)
metadata.index
# print(metadata.loc["treatment__biosamples"].value_counts(dropna=False))
# print(metadata.loc["Antibiotics__elixir"].value_counts(dropna=False))

2024-11-29 11:07:09.811 | SUCCESS  | mgnify_helper_functions:get_metadata_for_study:505 - Found metadata for 50 samples in study MGYS00003811.

Index(['temperature', 'geographic location (longitude)',
       'geographic location (country and/or sea,region)',
       'environment (biome)', 'environment (feature)',
       'environment (material)', 'environmental package', 'depth', 'elevation',
       'pH', 'geographic location (latitude)', 'instrument model',
       'ENA checklist', 'last update date', 'biosample_id', 'sample_id',
       'latitude', 'longitude', 'species', 'ENA-CHECKLIST__biosamples',
       'ENA-FIRST-PUBLIC__biosamples', 'ENA-LAST-UPDATE__biosamples',
       'ammonium__biosamples', 'anonymized name__biosamples',
       'cod__biosamples', 'collection_timestamp__biosamples',
       'days_from_last_scrape__biosamples', 'depth__biosamples',
       'diss_org_carb__biosamples', 'diss_oxygen__biosamples',
       'dna_extracted__biosamples', 'elevation__biosamples',
       'env biome__biosamples', 'env feature__biosamples',
       'env package__biosamples', 'env_material__biosamples',
       'extracted DNA avail now__biosamples', 'filter_identity__biosamples',
       'geo loc name__biosamples', 'has_physical_specimen__biosamples',
       'host subject id__biosamples', 'latitude__biosamples',
       'longitude__biosamples', 'nitrate__biosamples', 'nitrite__biosamples',
       'ph__biosamples', 'phosphate__biosamples',
       'physical_specimen_location__biosamples',
       'physical_specimen_remaining__biosamples', 'public__biosamples',
       'required_sample_info_status__biosamples', 'sample type__biosamples',
       'sample_progress__biosamples', 'temp__biosamples',
       'temp_enviromnment__biosamples', 'title__biosamples',
       'uv_absorbance__biosamples', 'uva254__biosamples',
       'ph_meth__biosamples', 'light intensity__biosamples',
       'light_intensity_5cm__biosamples'],
      dtype='object')

In [ ]:
from numpy import array
import pandas as pd
from IPython.display import display

x = {'test_accuracy': array([0.79194631, 0.7852349 , 0.76510067, 0.77852349, 0.81879195]), 'train_accuracy': array([1., 1., 1., 1., 1.]), 'test_balanced_accuracy': array([0.5       , 0.52941176, 0.49565217, 0.50707799, 0.51785714]), 'train_balanced_accuracy': array([1., 1., 1., 1., 1.]), 'test_f1(_binary)': array([0.        , 0.11111111, 0.        , 0.05714286, 0.06896552]), 'train_f1(_binary)': array([1., 1., 1., 1., 1.]), 'test_f1_macro': array([0.44194757, 0.49448685, 0.43346008, 0.46583379, 0.48429689]), 'train_f1_macro': array([1., 1., 1., 1., 1.]), 'test_f1_micro': array([0.79194631, 0.7852349 , 0.76510067, 0.77852349, 0.81879195]), 'train_f1_micro': array([1., 1., 1., 1., 1.]), 'test_f1_weighted': array([0.69999749, 0.70289917, 0.66909945, 0.69897962, 0.74353056]), 'train_f1_weighted': array([1., 1., 1., 1., 1.]), 'test_roc_auc(_macro)': array([0.5       , 0.52941176, 0.49565217, 0.50707799, 0.51785714]), 'train_roc_auc(_macro)': array([1., 1., 1., 1., 1.]), 'test_roc_auc_micro': array([0.5       , 0.52941176, 0.49565217, 0.50707799, 0.51785714]), 'train_roc_auc_micro': array([1., 1., 1., 1., 1.]), 'test_roc_auc_weighted': array([0.5       , 0.52941176, 0.49565217, 0.50707799, 0.51785714]), 'train_roc_auc_weighted': array([1., 1., 1., 1., 1.]), 'test_average_precision(_macro)': array([0.20805369, 0.27358863, 0.22818792, 0.21847036, 0.21692234]), 'train_average_precision(_macro)': array([1., 1., 1., 1., 1.]), 'test_average_precision_micro': array([0.20805369, 0.27358863, 0.22818792, 0.21847036, 0.21692234]), 'train_average_precision_micro': array([1., 1., 1., 1., 1.]), 'test_average_precision_weighted': array([0.20805369, 0.27358863, 0.22818792, 0.21847036, 0.21692234]), 'train_average_precision_weighted': array([1., 1., 1., 1., 1.]), 'test_precision(_binary)': array([0.        , 1.        , 0.        , 0.33333333, 1.        ]), 'train_precision(_binary)': array([1., 1., 1., 1., 1.]), 'test_precision_macro': array([0.39597315, 0.89115646, 0.38513514, 0.56050228, 0.90878378]), 'train_precision_macro': array([1., 1., 1., 1., 1.]), 'test_precision_micro': array([0.79194631, 0.7852349 , 0.76510067, 0.77852349, 0.81879195]), 'train_precision_micro': array([1., 1., 1., 1., 1.]), 'test_precision_weighted': array([0.62717896, 0.83198649, 0.5945039 , 0.69009531, 0.85185017]), 'train_precision_weighted': array([1., 1., 1., 1., 1.]), 'test_recall(_binary)': array([0.        , 0.05882353, 0.        , 0.03125   , 0.03571429]), 'train_recall(_binary)': array([1., 1., 1., 1., 1.]), 'test_recall_micro': array([0.79194631, 0.7852349 , 0.76510067, 0.77852349, 0.81879195]), 'train_recall_micro': array([1., 1., 1., 1., 1.]), 'test_recall_macro': array([0.5       , 0.52941176, 0.49565217, 0.50707799, 0.51785714]), 'train_recall_macro': array([1., 1., 1., 1., 1.]), 'test_recall_weighted': array([0.79194631, 0.7852349 , 0.76510067, 0.77852349, 0.81879195]), 'train_recall_weighted': array([1., 1., 1., 1., 1.])}

# replace first underscore with slash in column names
x = {k.replace("_", "/", 1): v for k, v in x.items()}

df = pd.DataFrame(x, index=["run1", "run2", "run3", "run4", "run5"])
df_mean = df.mean().rename("mean")
df = pd.concat([df, df_mean.to_frame().T])
df

,test_accuracy,train_accuracy,test_balanced_accuracy,train_balanced_accuracy,test_f1(_binary),train_f1(_binary),test_f1_macro,train_f1_macro,test_f1_micro,train_f1_micro,...,test_precision_weighted,train_precision_weighted,test_recall(_binary),train_recall(_binary),test_recall_micro,train_recall_micro,test_recall_macro,train_recall_macro,test_recall_weighted,train_recall_weighted
run1,0.791946,1.0,0.500000,1.0,0.000000,1.0,0.441948,1.0,0.791946,1.0,...,0.627179,1.0,0.000000,1.0,0.791946,1.0,0.500000,1.0,0.791946,1.0
run2,0.785235,1.0,0.529412,1.0,0.111111,1.0,0.494487,1.0,0.785235,1.0,...,0.831986,1.0,0.058824,1.0,0.785235,1.0,0.529412,1.0,0.785235,1.0
run3,0.765101,1.0,0.495652,1.0,0.000000,1.0,0.433460,1.0,0.765101,1.0,...,0.594504,1.0,0.000000,1.0,0.765101,1.0,0.495652,1.0,0.765101,1.0
run4,0.778523,1.0,0.507078,1.0,0.057143,1.0,0.465834,1.0,0.778523,1.0,...,0.690095,1.0,0.031250,1.0,0.778523,1.0,0.507078,1.0,0.778523,1.0
run5,0.818792,1.0,0.517857,1.0,0.068966,1.0,0.484297,1.0,0.818792,1.0,...,0.851850,1.0,0.035714,1.0,0.818792,1.0,0.517857,1.0,0.818792,1.0
mean,0.787919,1.0,0.510000,1.0,0.047444,1.0,0.464005,1.0,0.787919,1.0,...,0.719123,1.0,0.025158,1.0,0.787919,1.0,0.510000,1.0,0.787919,1.0

In [19]:
%reload_ext autoreload
%autoreload 2


import os
from importlib import import_module

import sys
sys.path.append("../")

import fire
import numpy as np
import pandas as pd
import wandb
import yaml
from joblib import Memory
from loguru import logger
from numpy.random import RandomState
from sklearn.model_selection import GridSearchCV, ShuffleSplit, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Normalizer

from src.data.dataloader import load_data
from src.global_vars import BASE_DATA_DIR, BASE_DIR
from src.helper_function import get_data_dir_for_eperiment, get_scores


def get_data(base_data_dir: str, **kwargs) -> tuple[pd.DataFrame, pd.DataFrame]:
    study_accessions = kwargs.get("study_accessions", None)
    summary_type = kwargs.get("summary_type", None)
    pipeline = kwargs.get("pipeline_version", None)
    metdata_cols_to_use_as_features = kwargs.get("metdata_cols_to_use_as_features", [])
    label_col = kwargs.get("label_col", None)

    assert summary_type is not None, logger.error("Summary type must be provided")
    assert pipeline is not None, logger.error("Pipeline version must be provided")

    if not isinstance(study_accessions, list):
        study_accessions = [study_accessions]

    data, labels = load_data(
        base_data_dir,
        study_accessions,
        summary_type,
        pipeline,
        metdata_cols_to_use_as_features,
        label_col,
    )

    return data, labels


# def build_preprocessor_pipeline(
#     cacher: Memory, *, verbose: bool = False, **kwargs
# ) -> Pipeline:
#     batch_correction_methods = kwargs.get("batch_correction_methods", [])
#     imputations = kwargs.get("imputations", [])
#     normalizations_and_transformations = kwargs.get(
#         "normalizations_and_transformations", []
#     )
#     feature_space_changes = kwargs.get("feature_space_changes", [])

#     # Create a pipeline for batch correction methods
#     p = []
#     for batch_corrector in batch_correction_methods:
#         pass
#     batch_correction_methods = Pipeline(p)

#     # Create a pipeline for imputation methods
#     p = []
#     for imputation in imputations:
#         pass
#     imputations = Pipeline(p)

#     # Create a pipeline for normalization and transformation methods
#     p = []
#     for n_or_t in normalizations_and_transformations:
#         if n_or_t["type"] == "total_sum_scaling":
#             p.append((n_or_t, Normalizer(**n_or_t["params"])))
#         elif n_or_t["type"] == "...":
#             pass
#     normalizations_and_transformations = Pipeline(p)

#     # Create a pipeline for feature space changes
#     p = []
#     for feature_space_change in feature_space_changes:
#         pass
#     feature_space_changes = Pipeline(p)

#     return Pipeline(
#         [
#             ("batch_correction_methods", batch_correction_methods),
#             ("imputations", imputations),
#             ("normalizations_and_transformations", normalizations_and_transformations),
#             ("feature_space_changes", feature_space_changes),
#         ]
#     )


# def build_model_pipeline(
#     cacher: Memory, *, verbose: bool = False, **kwargs
# ) -> Pipeline:


def main(config_script: str):
    # can we change SLURM stdout and stderr file?
    config_module = import_module(config_script)
    setup = config_module.get_setup()
    (
        misc_config,
        data_load_config,
        outer_cv_config,
        inner_cv_config,
        standard_pipeline,
        label_preprocessor,
        tuning_grid,
        scoring,
        best_fit_scorer,
    ) = setup.values()

    # get misc config parameters
    use_wandb = misc_config["wandb"]
    wandb_params = misc_config["wandb_params"]
    verbose_pipeline = misc_config.get("verbose_pipeline", True)

    # Set up file logging
    logger_path = get_data_dir_for_eperiment(misc_config) / "log.log"
    logger.add(logger_path, colorize=True, level="DEBUG")

    # Initialize wandb if enabled
    if use_wandb:
        wandb.init(
            project="thesis",
            notes=str(setup) ** wandb_params,
        )
    else:
        wandb.init(mode="disabled", project="thesis")

    # Load data
    data, labels = get_data(BASE_DATA_DIR, **data_load_config)

    # Encode labels. Make sure the positive class is labeled as 1
    positive_class_label = data_load_config["positive_class_label"]
    label_preprocessor.fit(labels)
    classes = list(label_preprocessor.classes_)
    if positive_class_label in classes:
        positive_class_index = classes.index(positive_class_label)
        if positive_class_index != 1:
            # Swap labels to ensure the desired class is labeled as 1
            classes[1], classes[positive_class_index] = (
                classes[positive_class_index],
                classes[1],
            )
            label_preprocessor.classes_ = np.array(classes)
    encoded_labels = label_preprocessor.transform(labels)

    # nested_score = cross_validate(
    #     tuner,
    #     data,
    #     encoded_labels,
    #     cv=outer_cv,
    #     scoring=score_functions,
    #     return_train_score=True,
    #     return_indices=True,
    # )

    tuner_results = []
    train_outer_cv_scores = []
    test_outer_cv_scores = []

    outer_cv = outer_cv_config["type"](**outer_cv_config["params"])

    for i, (train_index, test_index) in enumerate(outer_cv.split(data, encoded_labels)):
        # outer cv data split
        X_train, X_test = data.iloc[train_index], data.iloc[test_index]
        y_train, y_test = encoded_labels[train_index], encoded_labels[test_index]

        # With random state defined like this, each experiment is reproducible but the inner cv splits are different per outer cv split
        random_state = RandomState(i)

        inner_cv = inner_cv_config["type"](
            **inner_cv_config["params"], random_state=random_state
        )
        tuner = GridSearchCV(
            estimator=standard_pipeline,
            param_grid=tuning_grid,
            cv=inner_cv,
            scoring=scoring,
            refit=best_fit_scorer,
            verbose=verbose_pipeline,
            n_jobs=-1,
            return_train_score=True,
        )

        tuner = tuner.fit(X_train, y_train)
        
        tuner_cv_result = tuner.cv_results_

        best_model = tuner.best_estimator_
        best_model.fit(X_train, y_train)

        train_outer_cv_score = get_scores(best_model, X_train, y_train, scoring)
        test_outer_cv_score = get_scores(best_model, X_test, y_test, scoring)

        tuner_results.append(tuner_cv_result)
        train_outer_cv_scores.append(train_outer_cv_score)
        test_outer_cv_scores.append(test_outer_cv_score)

    return tuner_results, train_outer_cv_score, test_outer_cv_score


    # test_scores = nested_score["test_score"]
    # train_scores = nested_score["train_score"]
    # indices = nested_score["indices"]
    # score_time_test_set = nested_score["score_time"]

    # logger.info(nested_score)


# if __name__ == "__main__":
#     fire.Fire(main)

In [27]:
# tuner_results, train_outer_cv_score, test_outer_cv_score = main("run_configs.baseline1")

import pandas as pd
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.width = None
pd.options.display.max_colwidth = None

print(len(tuner_results))
print(tuner_results[0].keys())
print(tuner_results)
display(pd.DataFrame(tuner_results[0]))
print(pd.DataFrame(tuner_results[0]).dtypes)

5
dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_model', 'param_model__max_depth', 'param_model__n_estimators', 'param_preprocessor__batch_effect_corrections', 'param_preprocessor__feature_space_change', 'param_preprocessor__imputations', 'param_preprocessor__normalizations_and_transformations', 'param_preprocessor__normalizations_and_transformations__l1_normalizer__norm', 'params', 'split0_test_accuracy', 'split1_test_accuracy', 'split2_test_accuracy', 'split3_test_accuracy', 'split4_test_accuracy', 'mean_test_accuracy', 'std_test_accuracy', 'rank_test_accuracy', 'split0_train_accuracy', 'split1_train_accuracy', 'split2_train_accuracy', 'split3_train_accuracy', 'split4_train_accuracy', 'mean_train_accuracy', 'std_train_accuracy', 'split0_test_balanced_accuracy', 'split1_test_balanced_accuracy', 'split2_test_balanced_accuracy', 'split3_test_balanced_accuracy', 'split4_test_balanced_accuracy', 'mean_test_balanced_accuracy', 'std_test_balanced_accuracy', 'rank_test_balanced_accuracy', 'split0_train_balanced_accuracy', 'split1_train_balanced_accuracy', 'split2_train_balanced_accuracy', 'split3_train_balanced_accuracy', 'split4_train_balanced_accuracy', 'mean_train_balanced_accuracy', 'std_train_balanced_accuracy', 'split0_test_f1(_binary)', 'split1_test_f1(_binary)', 'split2_test_f1(_binary)', 'split3_test_f1(_binary)', 'split4_test_f1(_binary)', 'mean_test_f1(_binary)', 'std_test_f1(_binary)', 'rank_test_f1(_binary)', 'split0_train_f1(_binary)', 'split1_train_f1(_binary)', 'split2_train_f1(_binary)', 'split3_train_f1(_binary)', 'split4_train_f1(_binary)', 'mean_train_f1(_binary)', 'std_train_f1(_binary)', 'split0_test_f1_macro', 'split1_test_f1_macro', 'split2_test_f1_macro', 'split3_test_f1_macro', 'split4_test_f1_macro', 'mean_test_f1_macro', 'std_test_f1_macro', 'rank_test_f1_macro', 'split0_train_f1_macro', 'split1_train_f1_macro', 'split2_train_f1_macro', 'split3_train_f1_macro', 'split4_train_f1_macro', 'mean_train_f1_macro', 'std_train_f1_macro', 'split0_test_f1_micro', 'split1_test_f1_micro', 'split2_test_f1_micro', 'split3_test_f1_micro', 'split4_test_f1_micro', 'mean_test_f1_micro', 'std_test_f1_micro', 'rank_test_f1_micro', 'split0_train_f1_micro', 'split1_train_f1_micro', 'split2_train_f1_micro', 'split3_train_f1_micro', 'split4_train_f1_micro', 'mean_train_f1_micro', 'std_train_f1_micro', 'split0_test_f1_weighted', 'split1_test_f1_weighted', 'split2_test_f1_weighted', 'split3_test_f1_weighted', 'split4_test_f1_weighted', 'mean_test_f1_weighted', 'std_test_f1_weighted', 'rank_test_f1_weighted', 'split0_train_f1_weighted', 'split1_train_f1_weighted', 'split2_train_f1_weighted', 'split3_train_f1_weighted', 'split4_train_f1_weighted', 'mean_train_f1_weighted', 'std_train_f1_weighted', 'split0_test_roc_auc(_macro)', 'split1_test_roc_auc(_macro)', 'split2_test_roc_auc(_macro)', 'split3_test_roc_auc(_macro)', 'split4_test_roc_auc(_macro)', 'mean_test_roc_auc(_macro)', 'std_test_roc_auc(_macro)', 'rank_test_roc_auc(_macro)', 'split0_train_roc_auc(_macro)', 'split1_train_roc_auc(_macro)', 'split2_train_roc_auc(_macro)', 'split3_train_roc_auc(_macro)', 'split4_train_roc_auc(_macro)', 'mean_train_roc_auc(_macro)', 'std_train_roc_auc(_macro)', 'split0_test_roc_auc_micro', 'split1_test_roc_auc_micro', 'split2_test_roc_auc_micro', 'split3_test_roc_auc_micro', 'split4_test_roc_auc_micro', 'mean_test_roc_auc_micro', 'std_test_roc_auc_micro', 'rank_test_roc_auc_micro', 'split0_train_roc_auc_micro', 'split1_train_roc_auc_micro', 'split2_train_roc_auc_micro', 'split3_train_roc_auc_micro', 'split4_train_roc_auc_micro', 'mean_train_roc_auc_micro', 'std_train_roc_auc_micro', 'split0_test_roc_auc_weighted', 'split1_test_roc_auc_weighted', 'split2_test_roc_auc_weighted', 'split3_test_roc_auc_weighted', 'split4_test_roc_auc_weighted', 'mean_test_roc_auc_weighted', 'std_test_roc_auc_weighted', 'rank_test_roc_auc_weighted', 'split0_train_roc_auc_weighted', 'split1_train_roc_auc_weighted', 'split2_train_roc_auc_weighted', 'split3_train_roc_auc_weighted', 'split4_train_roc_auc_weighted', 'mean_train_roc_auc_weighted', 'std_train_roc_auc_weighted', 'split0_test_average_precision(_macro)', 'split1_test_average_precision(_macro)', 'split2_test_average_precision(_macro)', 'split3_test_average_precision(_macro)', 'split4_test_average_precision(_macro)', 'mean_test_average_precision(_macro)', 'std_test_average_precision(_macro)', 'rank_test_average_precision(_macro)', 'split0_train_average_precision(_macro)', 'split1_train_average_precision(_macro)', 'split2_train_average_precision(_macro)', 'split3_train_average_precision(_macro)', 'split4_train_average_precision(_macro)', 'mean_train_average_precision(_macro)', 'std_train_average_precision(_macro)', 'split0_test_average_precision_micro', 'split1_test_average_precision_micro', 'split2_test_average_precision_micro', 'split3_test_average_precision_micro', 'split4_test_average_precision_micro', 'mean_test_average_precision_micro', 'std_test_average_precision_micro', 'rank_test_average_precision_micro', 'split0_train_average_precision_micro', 'split1_train_average_precision_micro', 'split2_train_average_precision_micro', 'split3_train_average_precision_micro', 'split4_train_average_precision_micro', 'mean_train_average_precision_micro', 'std_train_average_precision_micro', 'split0_test_average_precision_weighted', 'split1_test_average_precision_weighted', 'split2_test_average_precision_weighted', 'split3_test_average_precision_weighted', 'split4_test_average_precision_weighted', 'mean_test_average_precision_weighted', 'std_test_average_precision_weighted', 'rank_test_average_precision_weighted', 'split0_train_average_precision_weighted', 'split1_train_average_precision_weighted', 'split2_train_average_precision_weighted', 'split3_train_average_precision_weighted', 'split4_train_average_precision_weighted', 'mean_train_average_precision_weighted', 'std_train_average_precision_weighted', 'split0_test_precision(_binary)', 'split1_test_precision(_binary)', 'split2_test_precision(_binary)', 'split3_test_precision(_binary)', 'split4_test_precision(_binary)', 'mean_test_precision(_binary)', 'std_test_precision(_binary)', 'rank_test_precision(_binary)', 'split0_train_precision(_binary)', 'split1_train_precision(_binary)', 'split2_train_precision(_binary)', 'split3_train_precision(_binary)', 'split4_train_precision(_binary)', 'mean_train_precision(_binary)', 'std_train_precision(_binary)', 'split0_test_precision_macro', 'split1_test_precision_macro', 'split2_test_precision_macro', 'split3_test_precision_macro', 'split4_test_precision_macro', 'mean_test_precision_macro', 'std_test_precision_macro', 'rank_test_precision_macro', 'split0_train_precision_macro', 'split1_train_precision_macro', 'split2_train_precision_macro', 'split3_train_precision_macro', 'split4_train_precision_macro', 'mean_train_precision_macro', 'std_train_precision_macro', 'split0_test_precision_micro', 'split1_test_precision_micro', 'split2_test_precision_micro', 'split3_test_precision_micro', 'split4_test_precision_micro', 'mean_test_precision_micro', 'std_test_precision_micro', 'rank_test_precision_micro', 'split0_train_precision_micro', 'split1_train_precision_micro', 'split2_train_precision_micro', 'split3_train_precision_micro', 'split4_train_precision_micro', 'mean_train_precision_micro', 'std_train_precision_micro', 'split0_test_precision_weighted', 'split1_test_precision_weighted', 'split2_test_precision_weighted', 'split3_test_precision_weighted', 'split4_test_precision_weighted', 'mean_test_precision_weighted', 'std_test_precision_weighted', 'rank_test_precision_weighted', 'split0_train_precision_weighted', 'split1_train_precision_weighted', 'split2_train_precision_weighted', 'split3_train_precision_weighted', 'split4_train_precision_weighted', 'mean_train_precision_weighted', 'std_train_precision_weighted', 'split0_test_recall(_binary)', 'split1_test_recall(_binary)', 'split2_test_recall(_binary)', 'split3_test_recall(_binary)', 'split4_test_recall(_binary)', 'mean_test_recall(_binary)', 'std_test_recall(_binary)', 'rank_test_recall(_binary)', 'split0_train_recall(_binary)', 'split1_train_recall(_binary)', 'split2_train_recall(_binary)', 'split3_train_recall(_binary)', 'split4_train_recall(_binary)', 'mean_train_recall(_binary)', 'std_train_recall(_binary)', 'split0_test_recall_micro', 'split1_test_recall_micro', 'split2_test_recall_micro', 'split3_test_recall_micro', 'split4_test_recall_micro', 'mean_test_recall_micro', 'std_test_recall_micro', 'rank_test_recall_micro', 'split0_train_recall_micro', 'split1_train_recall_micro', 'split2_train_recall_micro', 'split3_train_recall_micro', 'split4_train_recall_micro', 'mean_train_recall_micro', 'std_train_recall_micro', 'split0_test_recall_macro', 'split1_test_recall_macro', 'split2_test_recall_macro', 'split3_test_recall_macro', 'split4_test_recall_macro', 'mean_test_recall_macro', 'std_test_recall_macro', 'rank_test_recall_macro', 'split0_train_recall_macro', 'split1_train_recall_macro', 'split2_train_recall_macro', 'split3_train_recall_macro', 'split4_train_recall_macro', 'mean_train_recall_macro', 'std_train_recall_macro', 'split0_test_recall_weighted', 'split1_test_recall_weighted', 'split2_test_recall_weighted', 'split3_test_recall_weighted', 'split4_test_recall_weighted', 'mean_test_recall_weighted', 'std_test_recall_weighted', 'rank_test_recall_weighted', 'split0_train_recall_weighted', 'split1_train_recall_weighted', 'split2_train_recall_weighted', 'split3_train_recall_weighted', 'split4_train_recall_weighted', 'mean_train_recall_weighted', 'std_train_recall_weighted'])
[{'mean_fit_time': array([0.38777318, 2.81435485, 0.38391438, 2.32724938]), 'std_fit_time': array([0.01694128, 0.07991857, 0.03086551, 0.29032424]), 'mean_score_time': array([0.16519918, 0.17846303, 0.1617466 , 0.09705462]), 'std_score_time': array([0.0048131 , 0.01153783, 0.00912401, 0.01673646]), 'param_model': masked_array(data=[RandomForestClassifier(), RandomForestClassifier(),
                   RandomForestClassifier(), RandomForestClassifier()],
             mask=[False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_model__max_depth': masked_array(data=[None, None, 100, 100],
             mask=[False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_model__n_estimators': masked_array(data=[10, 100, 10, 100],
             mask=[False, False, False, False],
       fill_value=999999), 'param_preprocessor__batch_effect_corrections': masked_array(data=['passthrough', 'passthrough', 'passthrough',
                   'passthrough'],
             mask=[False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_preprocessor__feature_space_change': masked_array(data=['passthrough', 'passthrough', 'passthrough',
                   'passthrough'],
             mask=[False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_preprocessor__imputations': masked_array(data=['passthrough', 'passthrough', 'passthrough',
                   'passthrough'],
             mask=[False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_preprocessor__normalizations_and_transformations': masked_array(data=[Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),
                            steps=[('l1_normalizer', Normalizer())], verbose=True)                                              ,
                   Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),
                            steps=[('l1_normalizer', Normalizer())], verbose=True)                                              ,
                   Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),
                            steps=[('l1_normalizer', Normalizer())], verbose=True)                                              ,
                   Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),
                            steps=[('l1_normalizer', Normalizer())], verbose=True)                                              ],
             mask=[False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_preprocessor__normalizations_and_transformations__l1_normalizer__norm': masked_array(data=['l1', 'l1', 'l1', 'l1'],
             mask=[False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'model': RandomForestClassifier(), 'model__max_depth': None, 'model__n_estimators': 10, 'preprocessor__batch_effect_corrections': 'passthrough', 'preprocessor__feature_space_change': 'passthrough', 'preprocessor__imputations': 'passthrough', 'preprocessor__normalizations_and_transformations': Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),
         steps=[('l1_normalizer', Normalizer())], verbose=True), 'preprocessor__normalizations_and_transformations__l1_normalizer__norm': 'l1'}, {'model': RandomForestClassifier(), 'model__max_depth': None, 'model__n_estimators': 100, 'preprocessor__batch_effect_corrections': 'passthrough', 'preprocessor__feature_space_change': 'passthrough', 'preprocessor__imputations': 'passthrough', 'preprocessor__normalizations_and_transformations': Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),
         steps=[('l1_normalizer', Normalizer())], verbose=True), 'preprocessor__normalizations_and_transformations__l1_normalizer__norm': 'l1'}, {'model': RandomForestClassifier(), 'model__max_depth': 100, 'model__n_estimators': 10, 'preprocessor__batch_effect_corrections': 'passthrough', 'preprocessor__feature_space_change': 'passthrough', 'preprocessor__imputations': 'passthrough', 'preprocessor__normalizations_and_transformations': Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),
         steps=[('l1_normalizer', Normalizer())], verbose=True), 'preprocessor__normalizations_and_transformations__l1_normalizer__norm': 'l1'}, {'model': RandomForestClassifier(), 'model__max_depth': 100, 'model__n_estimators': 100, 'preprocessor__batch_effect_corrections': 'passthrough', 'preprocessor__feature_space_change': 'passthrough', 'preprocessor__imputations': 'passthrough', 'preprocessor__normalizations_and_transformations': Pipeline(memory=Memory(location=C:\Users\shaya\Documents\TU_projects\master_thesis\runs\test\pipeline_cache),

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model,param_model__max_depth,param_model__n_estimators,param_preprocessor__batch_effect_corrections,param_preprocessor__feature_space_change,param_preprocessor__imputations,param_preprocessor__normalizations_and_transformations,param_preprocessor__normalizations_and_transformations__l1_normalizer__norm,params,split0_test_accuracy,split1_test_accuracy,split2_test_accuracy,split3_test_accuracy,split4_test_accuracy,mean_test_accuracy,std_test_accuracy,rank_test_accuracy,split0_train_accuracy,split1_train_accuracy,split2_train_accuracy,split3_train_accuracy,split4_train_accuracy,mean_train_accuracy,std_train_accuracy,split0_test_balanced_accuracy,split1_test_balanced_accuracy,split2_test_balanced_accuracy,split3_test_balanced_accuracy,split4_test_balanced_accuracy,mean_test_balanced_accuracy,std_test_balanced_accuracy,rank_test_balanced_accuracy,split0_train_balanced_accuracy,split1_train_balanced_accuracy,split2_train_balanced_accuracy,split3_train_balanced_accuracy,split4_train_balanced_accuracy,mean_train_balanced_accuracy,std_train_balanced_accuracy,split0_test_f1(_binary),split1_test_f1(_binary),split2_test_f1(_binary),split3_test_f1(_binary),split4_test_f1(_binary),mean_test_f1(_binary),std_test_f1(_binary),rank_test_f1(_binary),split0_train_f1(_binary),split1_train_f1(_binary),split2_train_f1(_binary),split3_train_f1(_binary),split4_train_f1(_binary),mean_train_f1(_binary),std_train_f1(_binary),split0_test_f1_macro,split1_test_f1_macro,split2_test_f1_macro,split3_test_f1_macro,split4_test_f1_macro,mean_test_f1_macro,std_test_f1_macro,rank_test_f1_macro,split0_train_f1_macro,split1_train_f1_macro,split2_train_f1_macro,split3_train_f1_macro,split4_train_f1_macro,mean_train_f1_macro,std_train_f1_macro,split0_test_f1_micro,split1_test_f1_micro,split2_test_f1_micro,split3_test_f1_micro,split4_test_f1_micro,mean_test_f1_micro,std_test_f1_micro,rank_test_f1_micro,split0_train_f1_micro,split1_train_f1_micro,split2_train_f1_micro,split3_train_f1_micro,split4_train_f1_micro,mean_train_f1_micro,std_train_f1_micro,split0_test_f1_weighted,split1_test_f1_weighted,split2_test_f1_weighted,split3_test_f1_weighted,split4_test_f1_weighted,mean_test_f1_weighted,std_test_f1_weighted,rank_test_f1_weighted,split0_train_f1_weighted,split1_train_f1_weighted,split2_train_f1_weighted,split3_train_f1_weighted,split4_train_f1_weighted,mean_train_f1_weighted,std_train_f1_weighted,split0_test_roc_auc(_macro),split1_test_roc_auc(_macro),split2_test_roc_auc(_macro),split3_test_roc_auc(_macro),split4_test_roc_auc(_macro),mean_test_roc_auc(_macro),std_test_roc_auc(_macro),rank_test_roc_auc(_macro),split0_train_roc_auc(_macro),split1_train_roc_auc(_macro),split2_train_roc_auc(_macro),split3_train_roc_auc(_macro),split4_train_roc_auc(_macro),mean_train_roc_auc(_macro),std_train_roc_auc(_macro),split0_test_roc_auc_micro,split1_test_roc_auc_micro,split2_test_roc_auc_micro,split3_test_roc_auc_micro,split4_test_roc_auc_micro,mean_test_roc_auc_micro,std_test_roc_auc_micro,rank_test_roc_auc_micro,split0_train_roc_auc_micro,split1_train_roc_auc_micro,split2_train_roc_auc_micro,split3_train_roc_auc_micro,split4_train_roc_auc_micro,mean_train_roc_auc_micro,std_train_roc_auc_micro,split0_test_roc_auc_weighted,split1_test_roc_auc_weighted,split2_test_roc_auc_weighted,split3_test_roc_auc_weighted,split4_test_roc_auc_weighted,mean_test_roc_auc_weighted,std_test_roc_auc_weighted,rank_test_roc_auc_weighted,split0_train_roc_auc_weighted,split1_train_roc_auc_weighted,split2_train_roc_auc_weighted,split3_train_roc_auc_weighted,split4_train_roc_auc_weighted,mean_train_roc_auc_weighted,std_train_roc_auc_weighted,split0_test_average_precision(_macro),split1_test_average_precision(_macro),split2_test_average_precision(_macro),split3_test_average_precision(_macro),split4_test_average_precision(_macro),mean_test_average_precision(_macro),std_test_average_precision(_macro),rank_test_average_precision(_macro),split0_train_average_precision(_macro),split1_train_average_precision(_macro),split2_train_average_precision(_macro),split3_train_average_precision(_macro),split4_train_average_precision(_macro),mean_train_average_precision(_macro),std_train_average_precision(_macro),split0_test_average_precision_micro,split1_test_average_precision_micro,split2_test_average_precision_micro,split3_test_average_precision_micro,split4_test_average_precision_micro,mean_test_average_precision_micro,std_test_average_precision_micro,rank_test_average_precision_micro,split0_train_average_precision_micro,split1_train_average_precision_micro,split2_train_average_precision_micro,split3_train_average_precision_micro,split4_train_average_precision_micro,mean_train_average_precision_micro,std_train_average_precision_micro,split0_test_average_precision_weighted,split1_test_average_precision_weighted,split2_test_average_precision_weighted,split3_test_average_precision_weighted,split4_test_average_precision_weighted,mean_test_average_precision_weighted,std_test_average_precision_weighted,rank_test_average_precision_weighted,split0_train_average_precision_weighted,split1_train_average_precision_weighted,split2_train_average_precision_weighted,split3_train_average_precision_weighted,split4_train_average_precision_weighted,mean_train_average_precision_weighted,std_train_average_precision_weighted,split0_test_precision(_binary),split1_test_precision(_binary),split2_test_precision(_binary),split3_test_precision(_binary),split4_test_precision(_binary),mean_test_precision(_binary),std_test_precision(_binary),rank_test_precision(_binary),split0_train_precision(_binary),split1_train_precision(_binary),split2_train_precision(_binary),split3_train_precision(_binary),split4_train_precision(_binary),mean_train_precision(_binary),std_train_precision(_binary),split0_test_precision_macro,split1_test_precision_macro,split2_test_precision_macro,split3_test_precision_macro,split4_test_precision_macro,mean_test_precision_macro,std_test_precision_macro,rank_test_precision_macro,split0_train_precision_macro,split1_train_precision_macro,split2_train_precision_macro,split3_train_precision_macro,split4_train_precision_macro,mean_train_precision_macro,std_train_precision_macro,split0_test_precision_micro,split1_test_precision_micro,split2_test_precision_micro,split3_test_precision_micro,split4_test_precision_micro,mean_test_precision_micro,std_test_precision_micro,rank_test_precision_micro,split0_train_precision_micro,split1_train_precision_micro,split2_train_precision_micro,split3_train_precision_micro,split4_train_precision_micro,mean_train_precision_micro,std_train_precision_micro,split0_test_precision_weighted,split1_test_precision_weighted,split2_test_precision_weighted,split3_test_precision_weighted,split4_test_precision_weighted,mean_test_precision_weighted,std_test_precision_weighted,rank_test_precision_weighted,split0_train_precision_weighted,split1_train_precision_weighted,split2_train_precision_weighted,split3_train_precision_weighted,split4_train_precision_weighted,mean_train_precision_weighted,std_train_precision_weighted,split0_test_recall(_binary),split1_test_recall(_binary),split2_test_recall(_binary),split3_test_recall(_binary),split4_test_recall(_binary),mean_test_recall(_binary),std_test_recall(_binary),rank_test_recall(_binary),split0_train_recall(_binary),split1_train_recall(_binary),split2_train_recall(_binary),split3_train_recall(_binary),split4_train_recall(_binary),mean_train_recall(_binary),std_train_recall(_binary),split0_test_recall_micro,split1_test_recall_micro,split2_test_recall_micro,split3_test_recall_micro,split4_test_recall_micro,mean_test_recall_micro,std_test_recall_micro,rank_test_recall_micro,split0_train_recall_micro,split1_train_recall_micro,split2_train_recall_micro,split3_train_recall_micro,split4_train_recall_micro,mean_train_recall_micro,std_train_recall_micro,split0_test_recall_macro,split1_test_recall_macro,split2_test_recall_macro,split3_test_recall_macro,split4_test_recall_macro,mean_test_recall_macro,std_test_recall_macro,rank_test_recall_macro,split0_train_recall_macro,split1_train_recall_macro,split2_train_recall_macro,split3_train_recall_macro,split4_train_recall_macro,mean_train_recall_macro,std_train_recall_macro,split0_test_recall_weighted,split1_test_recall_weighted,split2_test_recall_weighted,split3_test_recall_weighted,split4_test_recall_weighted,mean_test_recall_weighted,std_test_recall_weighted,rank_test_recall_weighted,split0_train_recall_weighted,split1_train_recall_weighted,split2_train_recall_weighted,split3_train_recall_weighted,split4_train_recall_weighted,mean_train_recall_weighted,std_train_recall_weighted
0,0.387773,0.016941,0.165199,0.004813,RandomForestClassifier(),None,10,passthrough,passthrough,passthrough,(Normalizer()),l1,"{'model': RandomForestClassifier(), 'model__max_depth': None, 'model__n_estimators': 10, 'preprocessor__batch_effect_corrections': 'passthrough', 'preprocessor__feature_space_change': 'passthrough', 'preprocessor__imputations': 'passthrough', 'preprocessor__normalizations_and_transformations': (Normalizer()), 'preprocessor__normalizations_and_transformations__l1_normalizer__norm': 'l1'}",0.764706,0.739496,0.756303,0.764706,0.764706,0.757983,0.009800,4,0.978992,0.964286,0.968487,0.978992,0.970588,0.972269,0.005852,0.520733,0.514682,0.473684,0.555431,0.473958,0.507697,0.030959,3,0.950980,0.917476,0.931986,0.949495,0.933962,0.936780,0.012385,0.125000,0.162162,0.000000,0.222222,0.000000,0.101877,0.088780,2,0.948454,0.910053,0.923858,0.946809,0.929293,0.931693,0.014456,0.494539,0.503967,0.430622,0.541804,0.433333,0.480853,0.042937,2,0.967630,0.943886,0.951995,0.966860,0.955363,0.957147,0.009053,0.764706,0.739496,0.756303,0.764706,0.764706,0.757983,0.009800,4,0.978992,0.964286,0.968487,0.978992,0.970588,0.972269,0.005852,0.696388,0.696411,0.687548,0.700252,0.699160,0.695952,0.004468,3,0.978589,0.963077,0.967719,0.978570,0.969821,0.971555,0.006136,0.621981,0.491315,0.501535,0.588577,0.619339,0.564549,0.056941,4,0.999790,0.999688,0.998781,0.999424,0.999656,0.999468,0.000364,0.520733,0.514682,0.473684,0.555431,0.473958,0.507697,0.030959,3,0.950980,0.917476,0.931986,0.949495,0.933962,0.936780,0.012385,0.520733,0.514682,0.473684,0.555431,0.473958,0.507697,0.030959,3,0.950980,0.917476,0.931986,0.949495,0.933962,0.936780,0.012385,0.239714,0.224746,0.201681,0.307376,0.193277,0.233359,0.040505,2,0.922969,0.870666,0.886658,0.919998,0.897336,0.899526,0.019859,0.239714,0.224746,0.201681,0.307376,0.193277,0.233359,0.040505,2,0.922969,0.870666,0.886658,0.919998,0.897336,0.899526,0.019859,0.239714,0.224746,0.201681,0.307376,0.193277,0.233359,0.040505,2,0.922969,0.870666,0.886658,0.919998,0.897336,0.899526,0.019859,0.400000,0.272727,0.0,0.666667,0.000000,0.267879,0.252994,3,1.000000,1.0,0.98913,1.0,1.000000,0.997826,0.004348,0.590351,0.529882,0.394737,0.718289,0.399123,0.526476,0.122031,3,0.986979,0.978205,0.976336,0.987080,0.981771,0.982074,0.004407,0.764706,0.739496,0.756303,0.764706,0.764706,0.757983,0.009800,4,0.978992,0.964286,0.968487,0.978992,0.970588,0.972269,0.005852,0.694324,0.674667,0.630252,0.743883,0.643963,0.677418,0.040137,3,0.979539,0.965842,0.969186,0.979534,0.971661,0.973152,0.005530,0.074074,0.115385,0.000000,0.133333,0.000000,0.064558,0.056106,2,0.901961,0.834951,0.866667,0.898990,0.867925,0.874099,0.024583,0.764706,0.739496,0.756303,0.764706,0.764706,0.757983,0.009800,4,0.978992,0.964286,0.968487,0.978992,0.970588,0.972269,0.005852,0.520733,0.514682,0.473684,0.555431,0.473958,0.507697,0.030959,3,0.950980,0.917476,0.931986,0.949495,0.933962,0.936780,0.012385,0.764706,0.739496,0.756303,0.764706,0.764706,0.757983,0.009800,4,0.978992,0.964286,0.968487,0.978992,0.970588,0.972269,0.005852
1,2.814355,0.079919,0.178463,0.011538,RandomForestClassifier(),None,100,passthrough,passthrough,passthrough,(Normalizer()),l1,"{'model': RandomForestClassifier(), 'model__max_depth': None, 'model__n_estimators': 100, 'preprocessor__batch_effect_corrections': 'passthrough', 'preprocessor__feature_space_change': 'passthrough', 'preprocessor__imputations': 'passthrough', 'preprocessor__normalizations_and_transformations': (Normalizer()), 'preprocessor__normalizations_and_transformations__l1_normalizer__norm': 'l1'}",0.773109,0.747899,0.789916,0.756303,0.806723,0.774790,0.021523,2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.513084,0.492349,0.494737,0.527715,0.500000,0.505577,0.013191,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.068966,0.062500,0.000000,0.121212,0.000000,0.050536,0.046012,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.469889,0.458434,0.441315,0.489874,0.446512,0.461205,0.017416,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.773109,0.747899,0.789916,0.756303,0.806723,0.774790,0.021523,2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.688882,0.681356,0.704620,0.672656,0.720422,0.693587,0.017039,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.632448,0.509926,0.524781,0.729213,0.620697,0.603413,0.079863,2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.513084,0.492349,0.494737,0.527715,0.500000,0.505577,0.013191,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.513084,0.492349,0.494737,0.527715,0.500000,0.505577,0.013191,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.237006,0.216494,0.201681,0.279739,0.193277,0.225639,0.030857,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.237006,0.216494,0.201681,0.279739,0.193277,0.225639,0.030857,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.237006,0.216494,0.201681,0.279739,0.193277,0.225639,0.030857,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.500000,0.166667,0.0,0.666667,0.000000,0.266667,0.270801,4,1.000000,1.0,1.00000,1.0,1.000000,1.000000,0.000000,0.638889,0.472714,0.398305,0.712644,0.403361,0.525183,0.127877,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.773109,0.747899,0.789916,0.756303,0.806723,0.774790,0.021523,2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.714753,0.645026,0.635949,0.735439,0.650801,0.676394,0.040577,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.037037,0.038462,0.000000,0.066667,0.000000,0.028433,0.025508,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.773109,0.747899,0.789916,0.756303,0.806723,0.774790,0.021523,2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.513084,0.492349,0.494737,0.527715,0.500000,0.505577,0.013191,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.773109,0.747899,0.789916,0.756303,0.806723,0.774790,0.021523,2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
2,0.383914,0.030866,0.161747,0.009124,RandomForestClassifier(),100,10,passthrough,passthrough,passthrough,(Normalizer()),l1,"{'model': RandomForestClassifier(), 'model__max_depth': 100, 'model__n_estimators': 10, 'preprocessor__batch_effect_corrections': 'passthrough', 'preprocessor__feature_space_change': 'passthrough', 'preprocessor__imputations': 'passthrough', 'preprocessor__normalizations_and_transformations': (Normalizer()), 'preprocessor__normalizations_and_transformations__l1_normalizer__norm': 'l1'}",0.756303,0.764706,0.806723,0.731092,0.789916,0.769748,0.026360,3,0.964286,0.978992,0.985294,0.976891,0.962185,0.973529,0.008873,0.502214,0.530811,0.551974,0.510861,0.522645,0.523701,0.017190,1,0.920232,0.951456,0.966667,0.944444,0.918460,0.940252,0.018529,0.064516,0.176471,0.206897,0.111111,0.137931,0.139385,0.049679,1,0.910053,0.948980,0.965517,0.941176,0.908163,0.934778,0.022393,0.462210,0.519608,0.548424,0.476348,0.509157,0.503149,0.030826,1,0.943886,0.967876,0.978086,0.963399,0.942177,0.959085,0.013956,0.756303,0.764706,0.806723,0.731092,0.789916,0.769748,0.026360,3,0.964286,0.978992,0.985294,0.976891,0.962185,0.973529,0.008873,0.679437,0.712803,0.752193,0.657431,0.736884,0.707750,0.035166,1,0.963220,0.978595,0.985109,0.976377,0.961042,0.972868,0.009251,0.537842,0.594086,0.511404,0.630712,0.620245,0.578858,0.046617,3,0.998584,0.999675,0.999974,0.998446,0.998904,0.999117,0.000604,0.502214,0.530811,0.551974,0.510861,0.522645,0.523701,0.017190,1,0.920232,0.951456,0.966667,0.944444,0.918460,0.940252,0.018529,0.502214,0.530811,0.551974,0.510861,0.522645,0.523701,0.017190,1,0.920232,0.951456,0.966667,0.944444,0.918460,0.940252,0.018529,0.227747,0.236547,0.251471,0.257516,0.205456,0.235747,0.018457,1,0.867059,0.923921,0.948039,0.911998,0.866008,0.903405,0.032269,0.227747,0.236547,0.251471,0.257516,0.205456,0.235747,0.018457,1,0.867059,0.923921,0.948039,0.911998,0.866008,0.903405,0.032269,0.227747,0.236547,0.251471,0.257516,0.205456,0.235747,0.018457,1,0.867059,0.923921,0.948039,0.911998,0.866008,0.903405,0.032269,0.250000,0.375000,0.6,0.333333,0.333333,0.378333,0.118040,2,0.988506,1.0,1.00000,1.0,0.988889,0.995479,0.005538,0.511957,0.583896,0.707895,0.542773,0.573746,0.584053,0.066851,2,0.973687,0.986945,0.990741,0.985825,0.972424,0.981924,0.007433,0.756303,0.764706,0.806723,0.731092,0.789916,0.769748,0.026360,3,0.964286,0.978992,0.985294,0.976891,0.962185,0.973529,0.008873,0.655042,0.701510,0.772269,0.646613,0.721227,0.699332,0.045924,2,0.965220,0.979540,0.985566,0.977546,0.963292,0.974233,0.008585,0.037037,0.115385,0.125000,0.066667,0.086957,0.086209,0.032113,1,0.843137,0.902913,0.933333,0.888889,0.839623,0.881579,0.035847,0.756303,0.764706,0.806723,0.731092,0.789916,0.769748,0.026360,3,0.964286,0.978992,0.985294,0.976891,0.962185,0.973529,0.008873,0.502214,0.530811,0.551974,0.510861,0.522645,0.523701,0.017190,1,0.920232,0.951456,0.966667,0.944444,0.918460,0.940252,0.018529,0.756303,0.764706,0.806723,0.731092,0.789916,0.769748,0.026360,3,0.964286,0.978992,0.985294,0.976891,0.962185,0.973529,0.008873

mean_fit_time                                                                  float64
std_fit_time                                                                   float64
mean_score_time                                                                float64
std_score_time                                                                 float64
param_model                                                                     object
param_model__max_depth                                                          object
param_model__n_estimators                                                        int64
param_preprocessor__batch_effect_corrections                                    object
param_preprocessor__feature_space_change                                        object
param_preprocessor__imputations                                                 object
param_preprocessor__normalizations_and_transformations                          object
param_preprocessor__normalizations_and_transformations__l1_normalizer__norm     object
params                                                                          object
split0_test_accuracy                                                           float64
split1_test_accuracy                                                           float64
split2_test_accuracy                                                           float64
split3_test_accuracy                                                           float64
split4_test_accuracy                                                           float64
mean_test_accuracy                                                             float64
std_test_accuracy                                                              float64
rank_test_accuracy                                                               int32
split0_train_accuracy                                                          float64
split1_train_accuracy                                                          float64
split2_train_accuracy                                                          float64
split3_train_accuracy                                                          float64
split4_train_accuracy                                                          float64
mean_train_accuracy                                                            float64
std_train_accuracy                                                             float64
split0_test_balanced_accuracy                                                  float64
split1_test_balanced_accuracy                                                  float64
split2_test_balanced_accuracy                                                  float64
split3_test_balanced_accuracy                                                  float64
split4_test_balanced_accuracy                                                  float64
mean_test_balanced_accuracy                                                    float64
std_test_balanced_accuracy                                                     float64
rank_test_balanced_accuracy                                                      int32
split0_train_balanced_accuracy                                                 float64
split1_train_balanced_accuracy                                                 float64
split2_train_balanced_accuracy                                                 float64
split3_train_balanced_accuracy                                                 float64
split4_train_balanced_accuracy                                                 float64
mean_train_balanced_accuracy                                                   float64
std_train_balanced_accuracy                                                    float64
split0_test_f1(_binary)                                                        float64
split1_test_f1(_binary)                                                        float64
split2_test_f1(_binary)                                                        float64
split3_test_f1(_binary)                                                        float64
split4_test_f1(_binary)                                                        float64
mean_test_f1(_binary)                                                          float64
std_test_f1(_binary)                                                           float64
rank_test_f1(_binary)                                                            int32
split0_train_f1(_binary)                                                       float64
split1_train_f1(_binary)                                                       float64
split2_train_f1(_binary)                                                       float64
split3_train_f1(_binary)                                                       float64
split4_train_f1(_binary)                                                       float64
mean_train_f1(_binary)                                                         float64
std_train_f1(_binary)                                                          float64
split0_test_f1_macro                                                           float64
split1_test_f1_macro                                                           float64
split2_test_f1_macro                                                           float64
split3_test_f1_macro                                                           float64
split4_test_f1_macro                                                           float64
mean_test_f1_macro                                                             float64
std_test_f1_macro                                                              float64
rank_test_f1_macro                                                               int32
split0_train_f1_macro                                                          float64
split1_train_f1_macro                                                          float64
split2_train_f1_macro                                                          float64
split3_train_f1_macro                                                          float64
split4_train_f1_macro                                                          float64
mean_train_f1_macro                                                            float64
std_train_f1_macro                                                             float64
split0_test_f1_micro                                                           float64
split1_test_f1_micro                                                           float64
split2_test_f1_micro                                                           float64
split3_test_f1_micro                                                           float64
split4_test_f1_micro                                                           float64
mean_test_f1_micro                                                             float64
std_test_f1_micro                                                              float64
rank_test_f1_micro                                                               int32
split0_train_f1_micro                                                          float64
split1_train_f1_micro                                                          float64
split2_train_f1_micro                                                          float64
split3_train_f1_micro                                                          float64
split4_train_f1_micro                                                          float64
mean_train_f1_micro                                                            float64
std_train_f1_micro                                                             float64
split0_test_f1_weighted                                                        float64
split1_test_f1_weighted                                                        float64
split2_test_f1_weighted                                                        float64
split3_test_f1_weighted                                                        float64
split4_test_f1_weighted                                                        float64
mean_test_f1_weighted                                                          float64
std_test_f1_weighted                                                           float64
rank_test_f1_weighted                                                            int32
split0_train_f1_weighted                                                       float64
split1_train_f1_weighted                                                       float64
split2_train_f1_weighted                                                       float64
split3_train_f1_weighted                                                       float64
split4_train_f1_weighted                                                       float64
mean_train_f1_weighted                                                         float64
std_train_f1_weighted                                                          float64
split0_test_roc_auc(_macro)                                                    float64
split1_test_roc_auc(_macro)                                                    float64
split2_test_roc_auc(_macro)                                                    float64
split3_test_roc_auc(_macro)                                                    float64
split4_test_roc_auc(_macro)                                                    float64
mean_test_roc_auc(_macro)                                                      float64
std_test_roc_auc(_macro)                                                       float64
rank_test_roc_auc(_macro)                                                        int32
split0_train_roc_auc(_macro)                                                   float64
split1_train_roc_auc(_macro)                                                   float64
split2_train_roc_auc(_macro)                                                   float64
split3_train_roc_auc(_macro)                                                   float64
split4_train_roc_auc(_macro)                                                   float64
mean_train_roc_auc(_macro)                                                     float64
std_train_roc_auc(_macro)                                                      float64
split0_test_roc_auc_micro                                                      float64
split1_test_roc_auc_micro                                                      float64
split2_test_roc_auc_micro                                                      float64
split3_test_roc_auc_micro                                                      float64
split4_test_roc_auc_micro                                                      float64
mean_test_roc_auc_micro                                                        float64
std_test_roc_auc_micro                                                         float64
rank_test_roc_auc_micro                                                          int32
split0_train_roc_auc_micro                                                     float64
split1_train_roc_auc_micro                                                     float64
split2_train_roc_auc_micro                                                     float64
split3_train_roc_auc_micro                                                     float64
split4_train_roc_auc_micro                                                     float64
mean_train_roc_auc_micro                                                       float64
std_train_roc_auc_micro                                                        float64
split0_test_roc_auc_weighted                                                   float64
split1_test_roc_auc_weighted                                                   float64
split2_test_roc_auc_weighted                                                   float64
split3_test_roc_auc_weighted                                                   float64
split4_test_roc_auc_weighted                                                   float64
mean_test_roc_auc_weighted                                                     float64
std_test_roc_auc_weighted                                                      float64
rank_test_roc_auc_weighted                                                       int32
split0_train_roc_auc_weighted                                                  float64
split1_train_roc_auc_weighted                                                  float64
split2_train_roc_auc_weighted                                                  float64
split3_train_roc_auc_weighted                                                  float64
split4_train_roc_auc_weighted                                                  float64
mean_train_roc_auc_weighted                                                    float64
std_train_roc_auc_weighted                                                     float64
split0_test_average_precision(_macro)                                          float64
split1_test_average_precision(_macro)                                          float64
split2_test_average_precision(_macro)                                          float64
split3_test_average_precision(_macro)                                          float64
split4_test_average_precision(_macro)                                          float64
mean_test_average_precision(_macro)                                            float64
std_test_average_precision(_macro)                                             float64
rank_test_average_precision(_macro)                                              int32
split0_train_average_precision(_macro)                                         float64
split1_train_average_precision(_macro)                                         float64
split2_train_average_precision(_macro)                                         float64
split3_train_average_precision(_macro)                                         float64
split4_train_average_precision(_macro)                                         float64
mean_train_average_precision(_macro)                                           float64
std_train_average_precision(_macro)                                            float64
split0_test_average_precision_micro                                            float64
split1_test_average_precision_micro                                            float64
split2_test_average_precision_micro                                            float64
split3_test_average_precision_micro                                            float64
split4_test_average_precision_micro                                            float64
mean_test_average_precision_micro                                              float64
std_test_average_precision_micro                                               float64
rank_test_average_precision_micro                                                int32
split0_train_average_precision_micro                                           float64
split1_train_average_precision_micro                                           float64
split2_train_average_precision_micro                                           float64
split3_train_average_precision_micro                                           float64
split4_train_average_precision_micro                                           float64
mean_train_average_precision_micro                                             float64
std_train_average_precision_micro                                              float64
split0_test_average_precision_weighted                                         float64
split1_test_average_precision_weighted                                         float64
split2_test_average_precision_weighted                                         float64
split3_test_average_precision_weighted                                         float64
split4_test_average_precision_weighted                                         float64
mean_test_average_precision_weighted                                           float64
std_test_average_precision_weighted                                            float64
rank_test_average_precision_weighted                                             int32
split0_train_average_precision_weighted                                        float64
split1_train_average_precision_weighted                                        float64
split2_train_average_precision_weighted                                        float64
split3_train_average_precision_weighted                                        float64
split4_train_average_precision_weighted                                        float64
mean_train_average_precision_weighted                                          float64
std_train_average_precision_weighted                                           float64
split0_test_precision(_binary)                                                 float64
split1_test_precision(_binary)                                                 float64
split2_test_precision(_binary)                                                 float64
split3_test_precision(_binary)                                                 float64
split4_test_precision(_binary)                                                 float64
mean_test_precision(_binary)                                                   float64
std_test_precision(_binary)                                                    float64
rank_test_precision(_binary)                                                     int32
split0_train_precision(_binary)                                                float64
split1_train_precision(_binary)                                                float64
split2_train_precision(_binary)                                                float64
split3_train_precision(_binary)                                                float64
split4_train_precision(_binary)                                                float64
mean_train_precision(_binary)                                                  float64
std_train_precision(_binary)                                                   float64
split0_test_precision_macro                                                    float64
split1_test_precision_macro                                                    float64
split2_test_precision_macro                                                    float64
split3_test_precision_macro                                                    float64
split4_test_precision_macro                                                    float64
mean_test_precision_macro                                                      float64
std_test_precision_macro                                                       float64
rank_test_precision_macro                                                        int32
split0_train_precision_macro                                                   float64
split1_train_precision_macro                                                   float64
split2_train_precision_macro                                                   float64
split3_train_precision_macro                                                   float64
split4_train_precision_macro                                                   float64
mean_train_precision_macro                                                     float64
std_train_precision_macro                                                      float64
split0_test_precision_micro                                                    float64
split1_test_precision_micro                                                    float64
split2_test_precision_micro                                                    float64
split3_test_precision_micro                                                    float64
split4_test_precision_micro                                                    float64
mean_test_precision_micro                                                      float64

In [1]:
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

# Create presentation
prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
bullet_slide_layout = prs.slide_layouts[1]

def add_title_slide(title, subtitle):
    slide = prs.slides.add_slide(title_slide_layout)
    title_placeholder = slide.shapes.title
    subtitle_placeholder = slide.placeholders[1]
    title_placeholder.text = title
    subtitle_placeholder.text = subtitle

def add_bullet_slide(title, bullets):
    slide = prs.slides.add_slide(bullet_slide_layout)
    title_shape = slide.shapes.title
    body_shape = slide.shapes.placeholders[1]
    title_shape.text = title
    tf = body_shape.text_frame
    tf.clear()
    for i, bullet in enumerate(bullets):
        p = tf.add_paragraph() if i else tf.paragraphs[0]
        p.text = bullet
        p.level = 0
        p.font.size = Pt(18)

# Slide 1
add_title_slide("Learning to Learn from Microbiome Data", 
                "Update Meeting - May 2025\nShayan Ramezani")

# Slide 2: Motivation & Challenges
add_bullet_slide("Why Study Microbiome with ML?",
                 ["Microbiome linked to health, disease, plant & animal ecosystems",
                  "Datasets are small, sparse, compositional & heterogeneous",
                  "High dimensionality → risk of over-fitting traditional ML models"])

# Slide 3: Research Objectives
add_bullet_slide("Research Objectives",
                 ["RQ1 - Does meta-learning beat traditional baselines in few-shot disease classification?",
                  "RQ2 - How sensitive is performance to the number of labelled shots (10 vs 25)?",
                  "RQ3 - Can self-supervised meta-learning (STUNT) exploit unlabelled data better than supervised?"])

# Slide 4: Scope & Contributions
add_bullet_slide("Scope & Key Contributions",
                 ["36 gut-microbiome studies (70-369 samples each)",
                  "Evaluate Prototypical Networks & STUNT on taxonomic abundance tables",
                  "Benchmark vs Balanced RF & XGBoost under 10/25-shot regimes",
                  "Unified pipeline for preprocessing & task generation across studies"])

# Slide 5: Data Overview
add_bullet_slide("Dataset Snapshot",
                 ["Taxonomic abundance (Sun et al. 2024)",
                  "Binary labels: healthy vs diseased (multiple disease groups)",
                  "Class imbalance common; compositional counts",
                  "Feature counts exceed samples in most studies"])

# Slide 6: Pre-processing Pipeline",
add_bullet_slide("Pre-processing Pipeline",
                 ["Intersect metadata & abundance tables",
                  "Cleaning & normalisation",
                  "Abundance & prevalence filtering",
                  "Centric Arcsine Contrast transformation for compositional data"])

# Slide 7: Baseline Models
add_bullet_slide("Baseline Models",
                 ["Random Forest (primary)",
                  "XGBoost, Multi-layer Perceptron",
                  "Dimensionality reduction (PCA / Feature selection) optional",
                  "Nested cross-validation for hyper-parameter tuning"])

# Slide 8: Supervised Meta-learning
add_bullet_slide("Meta-learning - Prototypical Networks",
                 ["Metric-based few-shot learner",
                  "Outer loop builds class prototypes from support set",
                  "Inner loop classifies query samples via distance to prototypes",
                  "Aimed at rapid adaptation across heterogeneous studies"])

# Slide 9: Semi-Supervised Meta-learning
add_bullet_slide("Self-Supervised Meta-learning - STUNT",
                 ["Generates tasks by randomly sampling & permuting feature columns",
                  "Labels clusters via k-means → learn from unlabelled tables",
                  "Trained with same meta-learning pipeline as supervised ProtoNets"])

# Slide 10: Experimental Setup
add_bullet_slide("Experimental Setup",
                 ["N-way k-shot tasks; here N=2 (healthy vs disease)",
                  "Shots evaluated: k = 10 and 25",
                  "10-fold study-wise CV; separate study held-out for testing",
                  "Early stopping & Optuna hyper-parameter search"])

# Slide 11: Baseline Performance (RF)",
add_bullet_slide("Baseline Performance Highlights",
                 ["Within-study RF average AUC 0.759 (40 comparisons)",
                  "Universal RF with 277 species: AUC 0.776 overall, 0.825 for high-risk diseases",
                  "RF generally beats XGBoost & MLP across most studies"])

# Slide 12: Meta-Learning Performance
add_bullet_slide("Meta-Learning Performance Highlights",
                 ["ProtoNets benefit from dimensionality reduction but overall trail RF",
                  "In 10-shot & 25-shot regimes, RF outperforms ProtoNets in most disease groups",
                  "STUNT experiments ongoing - analysis focuses on leveraging unlabelled data"])

# Slide 13: Comparative Insights
add_bullet_slide("Key Insights So Far",
                 ["Traditional RF remains strong baseline in few-shot microbiome tasks",
                  "ProtoNet meta-learning not yet superior; hyper-parameter tuning critical",
                  "Dimensionality reduction impacts both RF & ProtoNets variably",
                  "Next focus: refine STUNT & explore functional abundance data"])

# Slide 14: Questions
add_bullet_slide("Discussion & Questions", [" "] )

# Save presentation
file_path = "./microbiome_update_meeting.pptx"
prs.save(file_path)

file_path

'./microbiome_update_meeting.pptx'